//----------------------------------------------------------------------
//         COPYRIGHT (C) 2022 TINYCHIP SEMICONDUCTOR                    
    //              CONFIDENTIAL & ALL RIGHTS RESERVED                      
//----------------------------------------------------------------------
// File name      : gpt_reg_def.h                                       
// Author         : mfpan                                               
// E-Mail         : mfpan@tinychip.com.cn                               
//----------------------------------------------------------------------
// Description    :                                                     
// Register Header File of GPT                                       
//----------------------------------------------------------------------
// Reversion History:                                                   
// 2022-10-21 17:24:12 -- automatically generated by reg_gen.pl Revision 1.11          
//----------------------------------------------------------------------

#ifndef   GPT_DEF_H__
#define   GPT_DEF_H__

// Register Offset Macro Definition
#define GPT_CTRL_OFFSET                                         0x0000
#define GPT_SW_FORCE_SHDW_OFFSET                                0x0004
#define GPT_PRESCALE_OFFSET                                     0x0008
#define GPT_PERIOD_OFFSET                                       0x000C
#define GPT_REPEAT_VAL_OFFSET                                   0x0010
#define GPT_LATCHED_CNT_OFFSET                                  0x0014
#define GPT_MATCHA_OP_OFFSET                                    0x0018
#define GPT_MATCHA0_VAL_OFFSET                                  0x001C
#define GPT_MATCHA1_VAL_OFFSET                                  0x0020
#define GPT_MATCHA2_VAL_OFFSET                                  0x0024
#define GPT_MATCHA3_VAL_OFFSET                                  0x0028
#define GPT_MATCHB_OP_OFFSET                                    0x002C
#define GPT_MATCHB0_VAL_OFFSET                                  0x0030
#define GPT_MATCHB1_VAL_OFFSET                                  0x0034
#define GPT_MATCHB2_VAL_OFFSET                                  0x0038
#define GPT_MATCHB3_VAL_OFFSET                                  0x003C
#define GPT_DELTA_OFFSET                                        0x0040
#define GPT_INT_MSK_OFFSET                                      0x0044
#define GPT_INT_CLR_OFFSET                                      0x0048
#define GPT_INT_STATUS_OFFSET                                   0x004C
#define GPT_INT_RAW_STATUS_OFFSET                               0x0050

// Register Address Macro Definition
#define GPT_CTRL_ADDR                                           ( GPT_BASE_ADDR + GPT_CTRL_OFFSET)
#define GPT_SW_FORCE_SHDW_ADDR                                  ( GPT_BASE_ADDR + GPT_SW_FORCE_SHDW_OFFSET)
#define GPT_PRESCALE_ADDR                                       ( GPT_BASE_ADDR + GPT_PRESCALE_OFFSET)
#define GPT_PERIOD_ADDR                                         ( GPT_BASE_ADDR + GPT_PERIOD_OFFSET)
#define GPT_REPEAT_VAL_ADDR                                     ( GPT_BASE_ADDR + GPT_REPEAT_VAL_OFFSET)
#define GPT_LATCHED_CNT_ADDR                                    ( GPT_BASE_ADDR + GPT_LATCHED_CNT_OFFSET)
#define GPT_MATCHA_OP_ADDR                                      ( GPT_BASE_ADDR + GPT_MATCHA_OP_OFFSET)
#define GPT_MATCHA0_VAL_ADDR                                    ( GPT_BASE_ADDR + GPT_MATCHA0_VAL_OFFSET)
#define GPT_MATCHA1_VAL_ADDR                                    ( GPT_BASE_ADDR + GPT_MATCHA1_VAL_OFFSET)
#define GPT_MATCHA2_VAL_ADDR                                    ( GPT_BASE_ADDR + GPT_MATCHA2_VAL_OFFSET)
#define GPT_MATCHA3_VAL_ADDR                                    ( GPT_BASE_ADDR + GPT_MATCHA3_VAL_OFFSET)
#define GPT_MATCHB_OP_ADDR                                      ( GPT_BASE_ADDR + GPT_MATCHB_OP_OFFSET)
#define GPT_MATCHB0_VAL_ADDR                                    ( GPT_BASE_ADDR + GPT_MATCHB0_VAL_OFFSET)
#define GPT_MATCHB1_VAL_ADDR                                    ( GPT_BASE_ADDR + GPT_MATCHB1_VAL_OFFSET)
#define GPT_MATCHB2_VAL_ADDR                                    ( GPT_BASE_ADDR + GPT_MATCHB2_VAL_OFFSET)
#define GPT_MATCHB3_VAL_ADDR                                    ( GPT_BASE_ADDR + GPT_MATCHB3_VAL_OFFSET)
#define GPT_DELTA_ADDR                                          ( GPT_BASE_ADDR + GPT_DELTA_OFFSET)
#define GPT_INT_MSK_ADDR                                        ( GPT_BASE_ADDR + GPT_INT_MSK_OFFSET)
#define GPT_INT_CLR_ADDR                                        ( GPT_BASE_ADDR + GPT_INT_CLR_OFFSET)
#define GPT_INT_STATUS_ADDR                                     ( GPT_BASE_ADDR + GPT_INT_STATUS_OFFSET)
#define GPT_INT_RAW_STATUS_ADDR                                 ( GPT_BASE_ADDR + GPT_INT_RAW_STATUS_OFFSET)

// Register Field Macro Definition
#define GPT_CTRL_MODIFY_DONE_SHIFT                                 18
#define GPT_CTRL_MODIFY_DONE_MASK                                  0x00040000
#define GPT_CTRL_MODIFY_DONE_SET(n)                                (((uint32_t)(n) << 18 ) & 0x00040000)
#define GPT_CTRL_MODIFY_DONE_CLR                                   0xFFFBFFFF

#define GPT_CTRL_BRK_STATUS_SHIFT                                  16
#define GPT_CTRL_BRK_STATUS_MASK                                   0x00030000
#define GPT_CTRL_BRK_STATUS_SET(n)                                 (((uint32_t)(n) << 16 ) & 0x00030000)
#define GPT_CTRL_BRK_STATUS_CLR                                    0xFFFCFFFF

#define GPT_CTRL_MATCH_NUM_SHIFT                                   12
#define GPT_CTRL_MATCH_NUM_MASK                                    0x00003000
#define GPT_CTRL_MATCH_NUM_SET(n)                                  (((uint32_t)(n) << 12 ) & 0x00003000)
#define GPT_CTRL_MATCH_NUM_CLR                                     0xFFFFCFFF

#define GPT_CTRL_EXT_BRK_EN_SHIFT                                  10
#define GPT_CTRL_EXT_BRK_EN_MASK                                   0x00000400
#define GPT_CTRL_EXT_BRK_EN_SET(n)                                 (((uint32_t)(n) << 10 ) & 0x00000400)
#define GPT_CTRL_EXT_BRK_EN_CLR                                    0xFFFFFBFF

#define GPT_CTRL_CNT_EN_SEL_SHIFT                                  9
#define GPT_CTRL_CNT_EN_SEL_MASK                                   0x00000200
#define GPT_CTRL_CNT_EN_SEL_SET(n)                                 (((uint32_t)(n) << 9  ) & 0x00000200)
#define GPT_CTRL_CNT_EN_SEL_CLR                                    0xFFFFFDFF

#define GPT_CTRL_CNT_WAVE_SHIFT                                    8
#define GPT_CTRL_CNT_WAVE_MASK                                     0x00000100
#define GPT_CTRL_CNT_WAVE_SET(n)                                   (((uint32_t)(n) << 8  ) & 0x00000100)
#define GPT_CTRL_CNT_WAVE_CLR                                      0xFFFFFEFF

#define GPT_CTRL_LATCH_CNT_CTRL_SHIFT                              7
#define GPT_CTRL_LATCH_CNT_CTRL_MASK                               0x00000080
#define GPT_CTRL_LATCH_CNT_CTRL_SET(n)                             (((uint32_t)(n) << 7  ) & 0x00000080)
#define GPT_CTRL_LATCH_CNT_CTRL_CLR                                0xFFFFFF7F

#define GPT_CTRL_MODE_SHIFT                                        4
#define GPT_CTRL_MODE_MASK                                         0x00000070
#define GPT_CTRL_MODE_SET(n)                                       (((uint32_t)(n) << 4  ) & 0x00000070)
#define GPT_CTRL_MODE_CLR                                          0xFFFFFF8F

#define GPT_CTRL_CNT_EN_SHIFT                                      0
#define GPT_CTRL_CNT_EN_MASK                                       0x00000001
#define GPT_CTRL_CNT_EN_SET(n)                                     (((uint32_t)(n) << 0  ) & 0x00000001)
#define GPT_CTRL_CNT_EN_CLR                                        0xFFFFFFFE

#define GPT_SW_FORCE_SHDW_SW_LATCH_CNT_SHIFT                       2
#define GPT_SW_FORCE_SHDW_SW_LATCH_CNT_MASK                        0x00000004
#define GPT_SW_FORCE_SHDW_SW_LATCH_CNT_SET(n)                      (((uint32_t)(n) << 2  ) & 0x00000004)
#define GPT_SW_FORCE_SHDW_SW_LATCH_CNT_CLR                         0xFFFFFFFB

#define GPT_SW_FORCE_SHDW_SW_FORCE_BRK_SHIFT                       1
#define GPT_SW_FORCE_SHDW_SW_FORCE_BRK_MASK                        0x00000002
#define GPT_SW_FORCE_SHDW_SW_FORCE_BRK_SET(n)                      (((uint32_t)(n) << 1  ) & 0x00000002)
#define GPT_SW_FORCE_SHDW_SW_FORCE_BRK_CLR                         0xFFFFFFFD

#define GPT_SW_FORCE_SHDW_SW_FORCE_SHDW_SHIFT                      0
#define GPT_SW_FORCE_SHDW_SW_FORCE_SHDW_MASK                       0x00000001
#define GPT_SW_FORCE_SHDW_SW_FORCE_SHDW_SET(n)                     (((uint32_t)(n) << 0  ) & 0x00000001)
#define GPT_SW_FORCE_SHDW_SW_FORCE_SHDW_CLR                        0xFFFFFFFE

#define GPT_PRESCALE_PRESCALE_SHIFT                                0
#define GPT_PRESCALE_PRESCALE_MASK                                 0x0000FFFF
#define GPT_PRESCALE_PRESCALE_SET(n)                               (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_PRESCALE_PRESCALE_CLR                                  0xFFFF0000

#define GPT_PERIOD_PERIOD_SHIFT                                    0
#define GPT_PERIOD_PERIOD_MASK                                     0x0000FFFF
#define GPT_PERIOD_PERIOD_SET(n)                                   (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_PERIOD_PERIOD_CLR                                      0xFFFF0000

#define GPT_REPEAT_VAL_REPEAT_VAL_SHIFT                            0
#define GPT_REPEAT_VAL_REPEAT_VAL_MASK                             0x0000FFFF
#define GPT_REPEAT_VAL_REPEAT_VAL_SET(n)                           (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_REPEAT_VAL_REPEAT_VAL_CLR                              0xFFFF0000

#define GPT_LATCHED_CNT_LATCHED_CNT_SHIFT                          0
#define GPT_LATCHED_CNT_LATCHED_CNT_MASK                           0x0000FFFF
#define GPT_LATCHED_CNT_LATCHED_CNT_SET(n)                         (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_LATCHED_CNT_LATCHED_CNT_CLR                            0xFFFF0000

#define GPT_MATCHA_OP_MATCHA3_OP_SHIFT                             12
#define GPT_MATCHA_OP_MATCHA3_OP_MASK                              0x00007000
#define GPT_MATCHA_OP_MATCHA3_OP_SET(n)                            (((uint32_t)(n) << 12 ) & 0x00007000)
#define GPT_MATCHA_OP_MATCHA3_OP_CLR                               0xFFFF8FFF

#define GPT_MATCHA_OP_MATCHA2_OP_SHIFT                             8
#define GPT_MATCHA_OP_MATCHA2_OP_MASK                              0x00000700
#define GPT_MATCHA_OP_MATCHA2_OP_SET(n)                            (((uint32_t)(n) << 8  ) & 0x00000700)
#define GPT_MATCHA_OP_MATCHA2_OP_CLR                               0xFFFFF8FF

#define GPT_MATCHA_OP_MATCHA1_OP_SHIFT                             4
#define GPT_MATCHA_OP_MATCHA1_OP_MASK                              0x00000070
#define GPT_MATCHA_OP_MATCHA1_OP_SET(n)                            (((uint32_t)(n) << 4  ) & 0x00000070)
#define GPT_MATCHA_OP_MATCHA1_OP_CLR                               0xFFFFFF8F

#define GPT_MATCHA_OP_MATCHA0_OP_SHIFT                             0
#define GPT_MATCHA_OP_MATCHA0_OP_MASK                              0x00000007
#define GPT_MATCHA_OP_MATCHA0_OP_SET(n)                            (((uint32_t)(n) << 0  ) & 0x00000007)
#define GPT_MATCHA_OP_MATCHA0_OP_CLR                               0xFFFFFFF8

#define GPT_MATCHA0_VAL_MATCHA0_VAL_SHIFT                          0
#define GPT_MATCHA0_VAL_MATCHA0_VAL_MASK                           0x0000FFFF
#define GPT_MATCHA0_VAL_MATCHA0_VAL_SET(n)                         (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_MATCHA0_VAL_MATCHA0_VAL_CLR                            0xFFFF0000

#define GPT_MATCHA1_VAL_MATCHA1_VAL_SHIFT                          0
#define GPT_MATCHA1_VAL_MATCHA1_VAL_MASK                           0x0000FFFF
#define GPT_MATCHA1_VAL_MATCHA1_VAL_SET(n)                         (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_MATCHA1_VAL_MATCHA1_VAL_CLR                            0xFFFF0000

#define GPT_MATCHA2_VAL_MATCHA2_VAL_SHIFT                          0
#define GPT_MATCHA2_VAL_MATCHA2_VAL_MASK                           0x0000FFFF
#define GPT_MATCHA2_VAL_MATCHA2_VAL_SET(n)                         (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_MATCHA2_VAL_MATCHA2_VAL_CLR                            0xFFFF0000

#define GPT_MATCHA3_VAL_MATCHA3_VAL_SHIFT                          0
#define GPT_MATCHA3_VAL_MATCHA3_VAL_MASK                           0x0000FFFF
#define GPT_MATCHA3_VAL_MATCHA3_VAL_SET(n)                         (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_MATCHA3_VAL_MATCHA3_VAL_CLR                            0xFFFF0000

#define GPT_MATCHB_OP_MATCHB3_OP_SHIFT                             12
#define GPT_MATCHB_OP_MATCHB3_OP_MASK                              0x00007000
#define GPT_MATCHB_OP_MATCHB3_OP_SET(n)                            (((uint32_t)(n) << 12 ) & 0x00007000)
#define GPT_MATCHB_OP_MATCHB3_OP_CLR                               0xFFFF8FFF

#define GPT_MATCHB_OP_MATCHB2_OP_SHIFT                             8
#define GPT_MATCHB_OP_MATCHB2_OP_MASK                              0x00000700
#define GPT_MATCHB_OP_MATCHB2_OP_SET(n)                            (((uint32_t)(n) << 8  ) & 0x00000700)
#define GPT_MATCHB_OP_MATCHB2_OP_CLR                               0xFFFFF8FF

#define GPT_MATCHB_OP_MATCHB1_OP_SHIFT                             4
#define GPT_MATCHB_OP_MATCHB1_OP_MASK                              0x00000070
#define GPT_MATCHB_OP_MATCHB1_OP_SET(n)                            (((uint32_t)(n) << 4  ) & 0x00000070)
#define GPT_MATCHB_OP_MATCHB1_OP_CLR                               0xFFFFFF8F

#define GPT_MATCHB_OP_MATCHB0_OP_SHIFT                             0
#define GPT_MATCHB_OP_MATCHB0_OP_MASK                              0x00000007
#define GPT_MATCHB_OP_MATCHB0_OP_SET(n)                            (((uint32_t)(n) << 0  ) & 0x00000007)
#define GPT_MATCHB_OP_MATCHB0_OP_CLR                               0xFFFFFFF8

#define GPT_MATCHB0_VAL_MATCHB0_VAL_SHIFT                          0
#define GPT_MATCHB0_VAL_MATCHB0_VAL_MASK                           0x0000FFFF
#define GPT_MATCHB0_VAL_MATCHB0_VAL_SET(n)                         (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_MATCHB0_VAL_MATCHB0_VAL_CLR                            0xFFFF0000

#define GPT_MATCHB1_VAL_MATCHB1_VAL_SHIFT                          0
#define GPT_MATCHB1_VAL_MATCHB1_VAL_MASK                           0x0000FFFF
#define GPT_MATCHB1_VAL_MATCHB1_VAL_SET(n)                         (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_MATCHB1_VAL_MATCHB1_VAL_CLR                            0xFFFF0000

#define GPT_MATCHB2_VAL_MATCHB2_VAL_SHIFT                          0
#define GPT_MATCHB2_VAL_MATCHB2_VAL_MASK                           0x0000FFFF
#define GPT_MATCHB2_VAL_MATCHB2_VAL_SET(n)                         (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_MATCHB2_VAL_MATCHB2_VAL_CLR                            0xFFFF0000

#define GPT_MATCHB3_VAL_MATCHB3_VAL_SHIFT                          0
#define GPT_MATCHB3_VAL_MATCHB3_VAL_MASK                           0x0000FFFF
#define GPT_MATCHB3_VAL_MATCHB3_VAL_SET(n)                         (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_MATCHB3_VAL_MATCHB3_VAL_CLR                            0xFFFF0000

#define GPT_DELTA_DELTA_SHIFT                                      0
#define GPT_DELTA_DELTA_MASK                                       0x0000FFFF
#define GPT_DELTA_DELTA_SET(n)                                     (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define GPT_DELTA_DELTA_CLR                                        0xFFFF0000

#define GPT_INT_MSK_INT_MSK_SHIFT                                  0
#define GPT_INT_MSK_INT_MSK_MASK                                   0x00000001
#define GPT_INT_MSK_INT_MSK_SET(n)                                 (((uint32_t)(n) << 0  ) & 0x00000001)
#define GPT_INT_MSK_INT_MSK_CLR                                    0xFFFFFFFE

#define GPT_INT_CLR_INT_CLR_SHIFT                                  0
#define GPT_INT_CLR_INT_CLR_MASK                                   0x00000001
#define GPT_INT_CLR_INT_CLR_SET(n)                                 (((uint32_t)(n) << 0  ) & 0x00000001)
#define GPT_INT_CLR_INT_CLR_CLR                                    0xFFFFFFFE

#define GPT_INT_STATUS_INT_STATUS_SHIFT                            0
#define GPT_INT_STATUS_INT_STATUS_MASK                             0x00000001
#define GPT_INT_STATUS_INT_STATUS_SET(n)                           (((uint32_t)(n) << 0  ) & 0x00000001)
#define GPT_INT_STATUS_INT_STATUS_CLR                              0xFFFFFFFE

#define GPT_INT_RAW_STATUS_INT_RAW_STATUS_SHIFT                    0
#define GPT_INT_RAW_STATUS_INT_RAW_STATUS_MASK                     0x00000001
#define GPT_INT_RAW_STATUS_INT_RAW_STATUS_SET(n)                   (((uint32_t)(n) << 0  ) & 0x00000001)
#define GPT_INT_RAW_STATUS_INT_RAW_STATUS_CLR                      0xFFFFFFFE

// Register Structure Definition
typedef struct
{
    __IO uint32_t CNT_EN          : 1  ; // 0  : 0 
    __IO uint32_t RESERVED3       : 3  ; // 3  : 1 
    __IO uint32_t MODE            : 3  ; // 6  : 4 
    __IO uint32_t LATCH_CNT_CTRL  : 1  ; // 7  : 7 
    __IO uint32_t CNT_WAVE        : 1  ; // 8  : 8 
    __IO uint32_t CNT_EN_SEL      : 1  ; // 9  : 9 
    __IO uint32_t EXT_BRK_EN      : 1  ; // 10 : 10 
    __IO uint32_t RESERVED2       : 1  ; // 11 : 11 
    __IO uint32_t MATCH_NUM       : 2  ; // 13 : 12 
    __IO uint32_t RESERVED1       : 2  ; // 15 : 14 
    __IO uint32_t BRK_STATUS      : 2  ; // 17 : 16 
    __IO uint32_t MODIFY_DONE     : 1  ; // 18 : 18 
    __IO uint32_t RESERVED0       : 13 ; // 31 : 19 
} GPT_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_FORCE_SHDW   : 1  ; // 0  : 0 
    __IO uint32_t SW_FORCE_BRK    : 1  ; // 1  : 1 
    __IO uint32_t SW_LATCH_CNT    : 1  ; // 2  : 2 
    __IO uint32_t RESERVED0       : 29 ; // 31 : 3 
} GPT_SW_FORCE_SHDW_FIELD_T;

typedef struct
{
    __IO uint32_t PRESCALE        : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_PRESCALE_FIELD_T;

typedef struct
{
    __IO uint32_t PERIOD          : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_PERIOD_FIELD_T;

typedef struct
{
    __IO uint32_t REPEAT_VAL      : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_REPEAT_VAL_FIELD_T;

typedef struct
{
    __IO uint32_t LATCHED_CNT     : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_LATCHED_CNT_FIELD_T;

typedef struct
{
    __IO uint32_t MATCHA0_OP      : 3  ; // 2  : 0 
    __IO uint32_t RESERVED3       : 1  ; // 3  : 3 
    __IO uint32_t MATCHA1_OP      : 3  ; // 6  : 4 
    __IO uint32_t RESERVED2       : 1  ; // 7  : 7 
    __IO uint32_t MATCHA2_OP      : 3  ; // 10 : 8 
    __IO uint32_t RESERVED1       : 1  ; // 11 : 11 
    __IO uint32_t MATCHA3_OP      : 3  ; // 14 : 12 
    __IO uint32_t RESERVED0       : 17 ; // 31 : 15 
} GPT_MATCHA_OP_FIELD_T;

typedef struct
{
    __IO uint32_t MATCHA0_VAL     : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_MATCHA0_VAL_FIELD_T;

typedef struct
{
    __IO uint32_t MATCHA1_VAL     : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_MATCHA1_VAL_FIELD_T;

typedef struct
{
    __IO uint32_t MATCHA2_VAL     : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_MATCHA2_VAL_FIELD_T;

typedef struct
{
    __IO uint32_t MATCHA3_VAL     : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_MATCHA3_VAL_FIELD_T;

typedef struct
{
    __IO uint32_t MATCHB0_OP      : 3  ; // 2  : 0 
    __IO uint32_t RESERVED3       : 1  ; // 3  : 3 
    __IO uint32_t MATCHB1_OP      : 3  ; // 6  : 4 
    __IO uint32_t RESERVED2       : 1  ; // 7  : 7 
    __IO uint32_t MATCHB2_OP      : 3  ; // 10 : 8 
    __IO uint32_t RESERVED1       : 1  ; // 11 : 11 
    __IO uint32_t MATCHB3_OP      : 3  ; // 14 : 12 
    __IO uint32_t RESERVED0       : 17 ; // 31 : 15 
} GPT_MATCHB_OP_FIELD_T;

typedef struct
{
    __IO uint32_t MATCHB0_VAL     : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_MATCHB0_VAL_FIELD_T;

typedef struct
{
    __IO uint32_t MATCHB1_VAL     : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_MATCHB1_VAL_FIELD_T;

typedef struct
{
    __IO uint32_t MATCHB2_VAL     : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_MATCHB2_VAL_FIELD_T;

typedef struct
{
    __IO uint32_t MATCHB3_VAL     : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_MATCHB3_VAL_FIELD_T;

typedef struct
{
    __IO uint32_t DELTA           : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} GPT_DELTA_FIELD_T;

typedef struct
{
    __IO uint32_t INT_MSK         : 1  ; // 0  : 0 
    __IO uint32_t RESERVED0       : 31 ; // 31 : 1 
} GPT_INT_MSK_FIELD_T;

typedef struct
{
    __IO uint32_t INT_CLR         : 1  ; // 0  : 0 
    __IO uint32_t RESERVED0       : 31 ; // 31 : 1 
} GPT_INT_CLR_FIELD_T;

typedef struct
{
    __IO uint32_t INT_STATUS      : 1  ; // 0  : 0 
    __IO uint32_t RESERVED0       : 31 ; // 31 : 1 
} GPT_INT_STATUS_FIELD_T;

typedef struct
{
    __IO uint32_t INT_RAW_STATUS  : 1  ; // 0  : 0 
    __IO uint32_t RESERVED0       : 31 ; // 31 : 1 
} GPT_INT_RAW_STATUS_FIELD_T;

// Register Map Structure Definition
typedef struct
{
    union 
    { 
        __IO  uint32_t CTRL                            ; // 0x0000
        GPT_CTRL_FIELD_T CTRL_F                        ;
    };

    union 
    { 
        __IO  uint32_t SW_FORCE_SHDW                   ; // 0x0004
        GPT_SW_FORCE_SHDW_FIELD_T SW_FORCE_SHDW_F      ;
    };

    union 
    { 
        __IO  uint32_t PRESCALE                        ; // 0x0008
        GPT_PRESCALE_FIELD_T PRESCALE_F                ;
    };

    union 
    { 
        __IO  uint32_t PERIOD                          ; // 0x000C
        GPT_PERIOD_FIELD_T PERIOD_F                    ;
    };

    union 
    { 
        __IO  uint32_t REPEAT_VAL                      ; // 0x0010
        GPT_REPEAT_VAL_FIELD_T REPEAT_VAL_F            ;
    };

    union 
    { 
        __IO  uint32_t LATCHED_CNT                     ; // 0x0014
        GPT_LATCHED_CNT_FIELD_T LATCHED_CNT_F          ;
    };

    union 
    { 
        __IO  uint32_t MATCHA_OP                       ; // 0x0018
        GPT_MATCHA_OP_FIELD_T MATCHA_OP_F              ;
    };

    union 
    { 
        __IO  uint32_t MATCHA0_VAL                     ; // 0x001C
        GPT_MATCHA0_VAL_FIELD_T MATCHA0_VAL_F          ;
    };

    union 
    { 
        __IO  uint32_t MATCHA1_VAL                     ; // 0x0020
        GPT_MATCHA1_VAL_FIELD_T MATCHA1_VAL_F          ;
    };

    union 
    { 
        __IO  uint32_t MATCHA2_VAL                     ; // 0x0024
        GPT_MATCHA2_VAL_FIELD_T MATCHA2_VAL_F          ;
    };

    union 
    { 
        __IO  uint32_t MATCHA3_VAL                     ; // 0x0028
        GPT_MATCHA3_VAL_FIELD_T MATCHA3_VAL_F          ;
    };

    union 
    { 
        __IO  uint32_t MATCHB_OP                       ; // 0x002C
        GPT_MATCHB_OP_FIELD_T MATCHB_OP_F              ;
    };

    union 
    { 
        __IO  uint32_t MATCHB0_VAL                     ; // 0x0030
        GPT_MATCHB0_VAL_FIELD_T MATCHB0_VAL_F          ;
    };

    union 
    { 
        __IO  uint32_t MATCHB1_VAL                     ; // 0x0034
        GPT_MATCHB1_VAL_FIELD_T MATCHB1_VAL_F          ;
    };

    union 
    { 
        __IO  uint32_t MATCHB2_VAL                     ; // 0x0038
        GPT_MATCHB2_VAL_FIELD_T MATCHB2_VAL_F          ;
    };

    union 
    { 
        __IO  uint32_t MATCHB3_VAL                     ; // 0x003C
        GPT_MATCHB3_VAL_FIELD_T MATCHB3_VAL_F          ;
    };

    union 
    { 
        __IO  uint32_t DELTA                           ; // 0x0040
        GPT_DELTA_FIELD_T DELTA_F                      ;
    };

    union 
    { 
        __IO  uint32_t INT_MSK                         ; // 0x0044
        GPT_INT_MSK_FIELD_T INT_MSK_F                  ;
    };

    union 
    { 
        __IO  uint32_t INT_CLR                         ; // 0x0048
        GPT_INT_CLR_FIELD_T INT_CLR_F                  ;
    };

    union 
    { 
        __IO  uint32_t INT_STATUS                      ; // 0x004C
        GPT_INT_STATUS_FIELD_T INT_STATUS_F            ;
    };

    union 
    { 
        __IO  uint32_t INT_RAW_STATUS                  ; // 0x0050
        GPT_INT_RAW_STATUS_FIELD_T INT_RAW_STATUS_F    ;
    };

} GPT_REG_TypeDef;

#endif
