//----------------------------------------------------------------------
//         COPYRIGHT (C) 2022 TINYCHIP SEMICONDUCTOR                    
    //              CONFIDENTIAL & ALL RIGHTS RESERVED                      
//----------------------------------------------------------------------
// File name      : spi_reg_def.h                                       
// Author         : mfpan                                               
// E-Mail         : mfpan@tinychip.com.cn                               
//----------------------------------------------------------------------
// Description    :                                                     
// Register Header File of SPI                                       
//----------------------------------------------------------------------
// Reversion History:                                                   
// 2022-10-21 17:24:14 -- automatically generated by reg_gen.pl Revision 1.11          
//----------------------------------------------------------------------

#ifndef   SPI_DEF_H__
#define   SPI_DEF_H__

// Register Offset Macro Definition
#define SPI_CR0_OFFSET                                          0x0000
#define SPI_CR1_OFFSET                                          0x0004
#define SPI_DR_OFFSET                                           0x0008
#define SPI_SR_OFFSET                                           0x000C
#define SPI_CPSR_OFFSET                                         0x0010
#define SPI_IMSCR_OFFSET                                        0x0014
#define SPI_RIS_OFFSET                                          0x0018
#define SPI_MIS_OFFSET                                          0x001C
#define SPI_ICR_OFFSET                                          0x0020
#define SPI_DMACR_OFFSET                                        0x0024

// Register Address Macro Definition
#define SPI_CR0_ADDR                                            ( SPI_BASE_ADDR + SPI_CR0_OFFSET)
#define SPI_CR1_ADDR                                            ( SPI_BASE_ADDR + SPI_CR1_OFFSET)
#define SPI_DR_ADDR                                             ( SPI_BASE_ADDR + SPI_DR_OFFSET)
#define SPI_SR_ADDR                                             ( SPI_BASE_ADDR + SPI_SR_OFFSET)
#define SPI_CPSR_ADDR                                           ( SPI_BASE_ADDR + SPI_CPSR_OFFSET)
#define SPI_IMSCR_ADDR                                          ( SPI_BASE_ADDR + SPI_IMSCR_OFFSET)
#define SPI_RIS_ADDR                                            ( SPI_BASE_ADDR + SPI_RIS_OFFSET)
#define SPI_MIS_ADDR                                            ( SPI_BASE_ADDR + SPI_MIS_OFFSET)
#define SPI_ICR_ADDR                                            ( SPI_BASE_ADDR + SPI_ICR_OFFSET)
#define SPI_DMACR_ADDR                                          ( SPI_BASE_ADDR + SPI_DMACR_OFFSET)

// Register Field Macro Definition
#define SPI_CR0_SCR_SHIFT                                 8
#define SPI_CR0_SCR_MASK                                  0x0000FF00
#define SPI_CR0_SCR_SET(n)                                (((uint32_t)(n) << 8  ) & 0x0000FF00)
#define SPI_CR0_SCR_CLR                                   0xFFFF00FF

#define SPI_CR0_SPH_SHIFT                                 7
#define SPI_CR0_SPH_MASK                                  0x00000080
#define SPI_CR0_SPH_SET(n)                                (((uint32_t)(n) << 7  ) & 0x00000080)
#define SPI_CR0_SPH_CLR                                   0xFFFFFF7F

#define SPI_CR0_SPO_SHIFT                                 6
#define SPI_CR0_SPO_MASK                                  0x00000040
#define SPI_CR0_SPO_SET(n)                                (((uint32_t)(n) << 6  ) & 0x00000040)
#define SPI_CR0_SPO_CLR                                   0xFFFFFFBF

#define SPI_CR0_FRF_SHIFT                                 4
#define SPI_CR0_FRF_MASK                                  0x00000030
#define SPI_CR0_FRF_SET(n)                                (((uint32_t)(n) << 4  ) & 0x00000030)
#define SPI_CR0_FRF_CLR                                   0xFFFFFFCF

#define SPI_CR0_DSS_SHIFT                                 0
#define SPI_CR0_DSS_MASK                                  0x0000000F
#define SPI_CR0_DSS_SET(n)                                (((uint32_t)(n) << 0  ) & 0x0000000F)
#define SPI_CR0_DSS_CLR                                   0xFFFFFFF0

#define SPI_CR1_LFRM_SHIFT                                4
#define SPI_CR1_LFRM_MASK                                 0x00000010
#define SPI_CR1_LFRM_SET(n)                               (((uint32_t)(n) << 4  ) & 0x00000010)
#define SPI_CR1_LFRM_CLR                                  0xFFFFFFEF

#define SPI_CR1_SOD_SHIFT                                 3
#define SPI_CR1_SOD_MASK                                  0x00000008
#define SPI_CR1_SOD_SET(n)                                (((uint32_t)(n) << 3  ) & 0x00000008)
#define SPI_CR1_SOD_CLR                                   0xFFFFFFF7

#define SPI_CR1_MS_SHIFT                                  2
#define SPI_CR1_MS_MASK                                   0x00000004
#define SPI_CR1_MS_SET(n)                                 (((uint32_t)(n) << 2  ) & 0x00000004)
#define SPI_CR1_MS_CLR                                    0xFFFFFFFB

#define SPI_CR1_SSE_SHIFT                                 1
#define SPI_CR1_SSE_MASK                                  0x00000002
#define SPI_CR1_SSE_SET(n)                                (((uint32_t)(n) << 1  ) & 0x00000002)
#define SPI_CR1_SSE_CLR                                   0xFFFFFFFD

#define SPI_CR1_LBM_SHIFT                                 0
#define SPI_CR1_LBM_MASK                                  0x00000001
#define SPI_CR1_LBM_SET(n)                                (((uint32_t)(n) << 0  ) & 0x00000001)
#define SPI_CR1_LBM_CLR                                   0xFFFFFFFE

#define SPI_DR_DATA_SHIFT                                 0
#define SPI_DR_DATA_MASK                                  0xFFFFFFFF
#define SPI_DR_DATA_SET(n)                                (((uint32_t)(n) << 0  ) & 0xFFFFFFFF)
#define SPI_DR_DATA_CLR                                   0x00000000

#define SPI_SR_BSY_SHIFT                                  4
#define SPI_SR_BSY_MASK                                   0x00000010
#define SPI_SR_BSY_SET(n)                                 (((uint32_t)(n) << 4  ) & 0x00000010)
#define SPI_SR_BSY_CLR                                    0xFFFFFFEF

#define SPI_SR_RFF_SHIFT                                  3
#define SPI_SR_RFF_MASK                                   0x00000008
#define SPI_SR_RFF_SET(n)                                 (((uint32_t)(n) << 3  ) & 0x00000008)
#define SPI_SR_RFF_CLR                                    0xFFFFFFF7

#define SPI_SR_RNE_SHIFT                                  2
#define SPI_SR_RNE_MASK                                   0x00000004
#define SPI_SR_RNE_SET(n)                                 (((uint32_t)(n) << 2  ) & 0x00000004)
#define SPI_SR_RNE_CLR                                    0xFFFFFFFB

#define SPI_SR_TNF_SHIFT                                  1
#define SPI_SR_TNF_MASK                                   0x00000002
#define SPI_SR_TNF_SET(n)                                 (((uint32_t)(n) << 1  ) & 0x00000002)
#define SPI_SR_TNF_CLR                                    0xFFFFFFFD

#define SPI_SR_TFE_SHIFT                                  0
#define SPI_SR_TFE_MASK                                   0x00000001
#define SPI_SR_TFE_SET(n)                                 (((uint32_t)(n) << 0  ) & 0x00000001)
#define SPI_SR_TFE_CLR                                    0xFFFFFFFE

#define SPI_CPSR_CPSDIVSR_SHIFT                           0
#define SPI_CPSR_CPSDIVSR_MASK                            0x000000FF
#define SPI_CPSR_CPSDIVSR_SET(n)                          (((uint32_t)(n) << 0  ) & 0x000000FF)
#define SPI_CPSR_CPSDIVSR_CLR                             0xFFFFFF00

#define SPI_IMSCR_TXIM_SHIFT                              3
#define SPI_IMSCR_TXIM_MASK                               0x00000008
#define SPI_IMSCR_TXIM_SET(n)                             (((uint32_t)(n) << 3  ) & 0x00000008)
#define SPI_IMSCR_TXIM_CLR                                0xFFFFFFF7

#define SPI_IMSCR_RXIM_SHIFT                              2
#define SPI_IMSCR_RXIM_MASK                               0x00000004
#define SPI_IMSCR_RXIM_SET(n)                             (((uint32_t)(n) << 2  ) & 0x00000004)
#define SPI_IMSCR_RXIM_CLR                                0xFFFFFFFB

#define SPI_IMSCR_RTIM_SHIFT                              1
#define SPI_IMSCR_RTIM_MASK                               0x00000002
#define SPI_IMSCR_RTIM_SET(n)                             (((uint32_t)(n) << 1  ) & 0x00000002)
#define SPI_IMSCR_RTIM_CLR                                0xFFFFFFFD

#define SPI_IMSCR_RORIM_SHIFT                             0
#define SPI_IMSCR_RORIM_MASK                              0x00000001
#define SPI_IMSCR_RORIM_SET(n)                            (((uint32_t)(n) << 0  ) & 0x00000001)
#define SPI_IMSCR_RORIM_CLR                               0xFFFFFFFE

#define SPI_RIS_TXRIS_SHIFT                               3
#define SPI_RIS_TXRIS_MASK                                0x00000008
#define SPI_RIS_TXRIS_SET(n)                              (((uint32_t)(n) << 3  ) & 0x00000008)
#define SPI_RIS_TXRIS_CLR                                 0xFFFFFFF7

#define SPI_RIS_RXRIS_SHIFT                               2
#define SPI_RIS_RXRIS_MASK                                0x00000004
#define SPI_RIS_RXRIS_SET(n)                              (((uint32_t)(n) << 2  ) & 0x00000004)
#define SPI_RIS_RXRIS_CLR                                 0xFFFFFFFB

#define SPI_RIS_RTRIS_SHIFT                               1
#define SPI_RIS_RTRIS_MASK                                0x00000002
#define SPI_RIS_RTRIS_SET(n)                              (((uint32_t)(n) << 1  ) & 0x00000002)
#define SPI_RIS_RTRIS_CLR                                 0xFFFFFFFD

#define SPI_RIS_RORRIS_SHIFT                              0
#define SPI_RIS_RORRIS_MASK                               0x00000001
#define SPI_RIS_RORRIS_SET(n)                             (((uint32_t)(n) << 0  ) & 0x00000001)
#define SPI_RIS_RORRIS_CLR                                0xFFFFFFFE

#define SPI_MIS_TXMIS_SHIFT                               3
#define SPI_MIS_TXMIS_MASK                                0x00000008
#define SPI_MIS_TXMIS_SET(n)                              (((uint32_t)(n) << 3  ) & 0x00000008)
#define SPI_MIS_TXMIS_CLR                                 0xFFFFFFF7

#define SPI_MIS_RXMIS_SHIFT                               2
#define SPI_MIS_RXMIS_MASK                                0x00000004
#define SPI_MIS_RXMIS_SET(n)                              (((uint32_t)(n) << 2  ) & 0x00000004)
#define SPI_MIS_RXMIS_CLR                                 0xFFFFFFFB

#define SPI_MIS_RTMIS_SHIFT                               1
#define SPI_MIS_RTMIS_MASK                                0x00000002
#define SPI_MIS_RTMIS_SET(n)                              (((uint32_t)(n) << 1  ) & 0x00000002)
#define SPI_MIS_RTMIS_CLR                                 0xFFFFFFFD

#define SPI_MIS_RORMIS_SHIFT                              0
#define SPI_MIS_RORMIS_MASK                               0x00000001
#define SPI_MIS_RORMIS_SET(n)                             (((uint32_t)(n) << 0  ) & 0x00000001)
#define SPI_MIS_RORMIS_CLR                                0xFFFFFFFE

#define SPI_ICR_RTIC_SHIFT                                1
#define SPI_ICR_RTIC_MASK                                 0x00000002
#define SPI_ICR_RTIC_SET(n)                               (((uint32_t)(n) << 1  ) & 0x00000002)
#define SPI_ICR_RTIC_CLR                                  0xFFFFFFFD

#define SPI_ICR_RORIC_SHIFT                               0
#define SPI_ICR_RORIC_MASK                                0x00000001
#define SPI_ICR_RORIC_SET(n)                              (((uint32_t)(n) << 0  ) & 0x00000001)
#define SPI_ICR_RORIC_CLR                                 0xFFFFFFFE

#define SPI_DMACR_TXDMAE_SHIFT                            1
#define SPI_DMACR_TXDMAE_MASK                             0x00000002
#define SPI_DMACR_TXDMAE_SET(n)                           (((uint32_t)(n) << 1  ) & 0x00000002)
#define SPI_DMACR_TXDMAE_CLR                              0xFFFFFFFD

#define SPI_DMACR_RXDMAE_SHIFT                            0
#define SPI_DMACR_RXDMAE_MASK                             0x00000001
#define SPI_DMACR_RXDMAE_SET(n)                           (((uint32_t)(n) << 0  ) & 0x00000001)
#define SPI_DMACR_RXDMAE_CLR                              0xFFFFFFFE

// Register Structure Definition
typedef struct
{
    __IO uint32_t DSS             : 4  ; // 3  : 0 
    __IO uint32_t FRF             : 2  ; // 5  : 4 
    __IO uint32_t SPO             : 1  ; // 6  : 6 
    __IO uint32_t SPH             : 1  ; // 7  : 7 
    __IO uint32_t SCR             : 8  ; // 15 : 8 
    __IO uint32_t RESERVED0       : 16 ; // 31 : 16 
} SPI_CR0_FIELD_T;

typedef struct
{
    __IO uint32_t LBM             : 1  ; // 0  : 0 
    __IO uint32_t SSE             : 1  ; // 1  : 1 
    __IO uint32_t MS              : 1  ; // 2  : 2 
    __IO uint32_t SOD             : 1  ; // 3  : 3 
    __IO uint32_t LFRM            : 1  ; // 4  : 4 
    __IO uint32_t RESERVED0       : 27 ; // 31 : 5 
} SPI_CR1_FIELD_T;

typedef struct
{
    __IO uint32_t DATA            : 32 ; // 31 : 0 
} SPI_DR_FIELD_T;

typedef struct
{
    __IO uint32_t TFE             : 1  ; // 0  : 0 
    __IO uint32_t TNF             : 1  ; // 1  : 1 
    __IO uint32_t RNE             : 1  ; // 2  : 2 
    __IO uint32_t RFF             : 1  ; // 3  : 3 
    __IO uint32_t BSY             : 1  ; // 4  : 4 
    __IO uint32_t RESERVED0       : 27 ; // 31 : 5 
} SPI_SR_FIELD_T;

typedef struct
{
    __IO uint32_t CPSDIVSR        : 8  ; // 7  : 0 
    __IO uint32_t RESERVED0       : 24 ; // 31 : 8 
} SPI_CPSR_FIELD_T;

typedef struct
{
    __IO uint32_t RORIM           : 1  ; // 0  : 0 
    __IO uint32_t RTIM            : 1  ; // 1  : 1 
    __IO uint32_t RXIM            : 1  ; // 2  : 2 
    __IO uint32_t TXIM            : 1  ; // 3  : 3 
    __IO uint32_t RESERVED0       : 28 ; // 31 : 4 
} SPI_IMSCR_FIELD_T;

typedef struct
{
    __IO uint32_t RORRIS          : 1  ; // 0  : 0 
    __IO uint32_t RTRIS           : 1  ; // 1  : 1 
    __IO uint32_t RXRIS           : 1  ; // 2  : 2 
    __IO uint32_t TXRIS           : 1  ; // 3  : 3 
    __IO uint32_t RESERVED0       : 28 ; // 31 : 4 
} SPI_RIS_FIELD_T;

typedef struct
{
    __IO uint32_t RORMIS          : 1  ; // 0  : 0 
    __IO uint32_t RTMIS           : 1  ; // 1  : 1 
    __IO uint32_t RXMIS           : 1  ; // 2  : 2 
    __IO uint32_t TXMIS           : 1  ; // 3  : 3 
    __IO uint32_t RESERVED0       : 28 ; // 31 : 4 
} SPI_MIS_FIELD_T;

typedef struct
{
    __IO uint32_t RORIC           : 1  ; // 0  : 0 
    __IO uint32_t RTIC            : 1  ; // 1  : 1 
    __IO uint32_t RESERVED0       : 30 ; // 31 : 2 
} SPI_ICR_FIELD_T;

typedef struct
{
    __IO uint32_t RXDMAE          : 1  ; // 0  : 0 
    __IO uint32_t TXDMAE          : 1  ; // 1  : 1 
    __IO uint32_t RESERVED0       : 30 ; // 31 : 2 
} SPI_DMACR_FIELD_T;

// Register Map Structure Definition
typedef struct
{
    union 
    { 
        __IO  uint32_t CR0           ; // 0x0000
        SPI_CR0_FIELD_T CR0_F        ;
    };

    union 
    { 
        __IO  uint32_t CR1           ; // 0x0004
        SPI_CR1_FIELD_T CR1_F        ;
    };

    union 
    { 
        __IO  uint32_t DR            ; // 0x0008
        SPI_DR_FIELD_T DR_F          ;
    };

    union 
    { 
        __IO  uint32_t SR            ; // 0x000C
        SPI_SR_FIELD_T SR_F          ;
    };

    union 
    { 
        __IO  uint32_t CPSR          ; // 0x0010
        SPI_CPSR_FIELD_T CPSR_F      ;
    };

    union 
    { 
        __IO  uint32_t IMSCR         ; // 0x0014
        SPI_IMSCR_FIELD_T IMSCR_F    ;
    };

    union 
    { 
        __IO  uint32_t RIS           ; // 0x0018
        SPI_RIS_FIELD_T RIS_F        ;
    };

    union 
    { 
        __IO  uint32_t MIS           ; // 0x001C
        SPI_MIS_FIELD_T MIS_F        ;
    };

    union 
    { 
        __IO  uint32_t ICR           ; // 0x0020
        SPI_ICR_FIELD_T ICR_F        ;
    };

    union 
    { 
        __IO  uint32_t DMACR         ; // 0x0024
        SPI_DMACR_FIELD_T DMACR_F    ;
    };

} SPI_REG_TypeDef;

#endif
