//----------------------------------------------------------------------
//         COPYRIGHT (C) 2022 TINYCHIP SEMICONDUCTOR                    
    //              CONFIDENTIAL & ALL RIGHTS RESERVED                      
//----------------------------------------------------------------------
// File name      : syscfg_reg_def.h                                    
// Author         : mfpan                                               
// E-Mail         : mfpan@tinychip.com.cn                               
//----------------------------------------------------------------------
// Description    :                                                     
// Register Header File of SYSCFG                                    
//----------------------------------------------------------------------
// Reversion History:                                                   
// 2022-10-21 17:24:14 -- automatically generated by reg_gen.pl Revision 1.11          
//----------------------------------------------------------------------

#ifndef   SYSCFG_DEF_H__
#define   SYSCFG_DEF_H__

// Register Offset Macro Definition
#define SYSCFG_AONTOP_CLKRST_CTRL_OFFSET                        0x0000
#define SYSCFG_PMU_CTRL_OFFSET                                  0x0004
#define SYSCFG_M0_CLKRST_CTRL_OFFSET                            0x0008
#define SYSCFG_HCLK_PCLK_CTRL_OFFSET                            0x000C
#define SYSCFG_AHB2APB_CLKRST_CTRL_OFFSET                       0x0010
#define SYSCFG_RTC_CLKRST_CTRL_OFFSET                           0x0014
#define SYSCFG_I2C0_CLKRST_CTRL_OFFSET                          0x0018
#define SYSCFG_UART0_CLKRST_CTRL_OFFSET                         0x001C
#define SYSCFG_UART1_CLKRST_CTRL_OFFSET                         0x0020
#define SYSCFG_WDG_CLKRST_CTRL_OFFSET                           0x0024
#define SYSCFG_LVD_CLKRST_CTRL_OFFSET                           0x0028
#define SYSCFG_SARADC_CLKRST_CTRL_OFFSET                        0x002C
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_OFFSET                      0x0030
#define SYSCFG_SPI_CLKRST_CTRL_OFFSET                           0x0034
#define SYSCFG_GPT0_CLKRST_CTRL_OFFSET                          0x0038
#define SYSCFG_GPT1_CLKRST_CTRL_OFFSET                          0x003C
#define SYSCFG_GPT2_CLKRST_CTRL_OFFSET                          0x0040
#define SYSCFG_GPT3_CLKRST_CTRL_OFFSET                          0x0044
#define SYSCFG_GPT4_CLKRST_CTRL_OFFSET                          0x0048
#define SYSCFG_PWM_CTRL_OFFSET                                  0x004C
#define SYSCFG_TP_OFFSET                                        0x0050
#define SYSCFG_TEST_CTRL_OFFSET                                 0x0054
#define SYSCFG_WR_LOCK_CTRL_OFFSET                              0xFFFC

// Register Address Macro Definition
#define SYSCFG_AONTOP_CLKRST_CTRL_ADDR                          ( SYSCFG_BASE_ADDR + SYSCFG_AONTOP_CLKRST_CTRL_OFFSET)
#define SYSCFG_PMU_CTRL_ADDR                                    ( SYSCFG_BASE_ADDR + SYSCFG_PMU_CTRL_OFFSET)
#define SYSCFG_M0_CLKRST_CTRL_ADDR                              ( SYSCFG_BASE_ADDR + SYSCFG_M0_CLKRST_CTRL_OFFSET)
#define SYSCFG_HCLK_PCLK_CTRL_ADDR                              ( SYSCFG_BASE_ADDR + SYSCFG_HCLK_PCLK_CTRL_OFFSET)
#define SYSCFG_AHB2APB_CLKRST_CTRL_ADDR                         ( SYSCFG_BASE_ADDR + SYSCFG_AHB2APB_CLKRST_CTRL_OFFSET)
#define SYSCFG_RTC_CLKRST_CTRL_ADDR                             ( SYSCFG_BASE_ADDR + SYSCFG_RTC_CLKRST_CTRL_OFFSET)
#define SYSCFG_I2C0_CLKRST_CTRL_ADDR                            ( SYSCFG_BASE_ADDR + SYSCFG_I2C0_CLKRST_CTRL_OFFSET)
#define SYSCFG_UART0_CLKRST_CTRL_ADDR                           ( SYSCFG_BASE_ADDR + SYSCFG_UART0_CLKRST_CTRL_OFFSET)
#define SYSCFG_UART1_CLKRST_CTRL_ADDR                           ( SYSCFG_BASE_ADDR + SYSCFG_UART1_CLKRST_CTRL_OFFSET)
#define SYSCFG_WDG_CLKRST_CTRL_ADDR                             ( SYSCFG_BASE_ADDR + SYSCFG_WDG_CLKRST_CTRL_OFFSET)
#define SYSCFG_LVD_CLKRST_CTRL_ADDR                             ( SYSCFG_BASE_ADDR + SYSCFG_LVD_CLKRST_CTRL_OFFSET)
#define SYSCFG_SARADC_CLKRST_CTRL_ADDR                          ( SYSCFG_BASE_ADDR + SYSCFG_SARADC_CLKRST_CTRL_OFFSET)
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_ADDR                        ( SYSCFG_BASE_ADDR + SYSCFG_CAPTOUCH_CLKRST_CTRL_OFFSET)
#define SYSCFG_SPI_CLKRST_CTRL_ADDR                             ( SYSCFG_BASE_ADDR + SYSCFG_SPI_CLKRST_CTRL_OFFSET)
#define SYSCFG_GPT0_CLKRST_CTRL_ADDR                            ( SYSCFG_BASE_ADDR + SYSCFG_GPT0_CLKRST_CTRL_OFFSET)
#define SYSCFG_GPT1_CLKRST_CTRL_ADDR                            ( SYSCFG_BASE_ADDR + SYSCFG_GPT1_CLKRST_CTRL_OFFSET)
#define SYSCFG_GPT2_CLKRST_CTRL_ADDR                            ( SYSCFG_BASE_ADDR + SYSCFG_GPT2_CLKRST_CTRL_OFFSET)
#define SYSCFG_GPT3_CLKRST_CTRL_ADDR                            ( SYSCFG_BASE_ADDR + SYSCFG_GPT3_CLKRST_CTRL_OFFSET)
#define SYSCFG_GPT4_CLKRST_CTRL_ADDR                            ( SYSCFG_BASE_ADDR + SYSCFG_GPT4_CLKRST_CTRL_OFFSET)
#define SYSCFG_PWM_CTRL_ADDR                                    ( SYSCFG_BASE_ADDR + SYSCFG_PWM_CTRL_OFFSET)
#define SYSCFG_TP_ADDR                                          ( SYSCFG_BASE_ADDR + SYSCFG_TP_OFFSET)
#define SYSCFG_TEST_CTRL_ADDR                                   ( SYSCFG_BASE_ADDR + SYSCFG_TEST_CTRL_OFFSET)
#define SYSCFG_WR_LOCK_CTRL_ADDR                                ( SYSCFG_BASE_ADDR + SYSCFG_WR_LOCK_CTRL_OFFSET)

// Register Field Macro Definition
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_FCLK_EN_GPIOB_SHIFT                          14
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_FCLK_EN_GPIOB_MASK                           0x00004000
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_FCLK_EN_GPIOB_SET(n)                         (((uint32_t)(n) << 14 ) & 0x00004000)
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_FCLK_EN_GPIOB_CLR                            0xFFFFBFFF

#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_GPIOB_SHIFT                          13
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_GPIOB_MASK                           0x00002000
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_GPIOB_SET(n)                         (((uint32_t)(n) << 13 ) & 0x00002000)
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_GPIOB_CLR                            0xFFFFDFFF

#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_GPIOB_SHIFT                              12
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_GPIOB_MASK                               0x00001000
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_GPIOB_SET(n)                             (((uint32_t)(n) << 12 ) & 0x00001000)
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_GPIOB_CLR                                0xFFFFEFFF

#define SYSCFG_AONTOP_CLKRST_CTRL_SW_FCLK_EN_GPIOA_SHIFT                          10
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_FCLK_EN_GPIOA_MASK                           0x00000400
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_FCLK_EN_GPIOA_SET(n)                         (((uint32_t)(n) << 10 ) & 0x00000400)
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_FCLK_EN_GPIOA_CLR                            0xFFFFFBFF

#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_GPIOA_SHIFT                          9
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_GPIOA_MASK                           0x00000200
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_GPIOA_SET(n)                         (((uint32_t)(n) << 9  ) & 0x00000200)
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_GPIOA_CLR                            0xFFFFFDFF

#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_GPIOA_SHIFT                              8
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_GPIOA_MASK                               0x00000100
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_GPIOA_SET(n)                             (((uint32_t)(n) << 8  ) & 0x00000100)
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_GPIOA_CLR                                0xFFFFFEFF

#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_ACFG_SHIFT                               6
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_ACFG_MASK                                0x00000040
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_ACFG_SET(n)                              (((uint32_t)(n) << 6  ) & 0x00000040)
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_ACFG_CLR                                 0xFFFFFFBF

#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_APINMUX_SHIFT                            5
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_APINMUX_MASK                             0x00000020
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_APINMUX_SET(n)                           (((uint32_t)(n) << 5  ) & 0x00000020)
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_RST_APINMUX_CLR                              0xFFFFFFDF

#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_AON_SHIFT                            1
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_AON_MASK                             0x00000002
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_AON_SET(n)                           (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_AONTOP_CLKRST_CTRL_SW_PCLK_EN_AON_CLR                              0xFFFFFFFD

#define SYSCFG_PMU_CTRL_SW_EFLASH_INIT_CYCLE_SHIFT                                24
#define SYSCFG_PMU_CTRL_SW_EFLASH_INIT_CYCLE_MASK                                 0xFF000000
#define SYSCFG_PMU_CTRL_SW_EFLASH_INIT_CYCLE_SET(n)                               (((uint32_t)(n) << 24 ) & 0xFF000000)
#define SYSCFG_PMU_CTRL_SW_EFLASH_INIT_CYCLE_CLR                                  0x00FFFFFF

#define SYSCFG_PMU_CTRL_SW_EFLASH_PUP_CYCLE_SHIFT                                 16
#define SYSCFG_PMU_CTRL_SW_EFLASH_PUP_CYCLE_MASK                                  0x00FF0000
#define SYSCFG_PMU_CTRL_SW_EFLASH_PUP_CYCLE_SET(n)                                (((uint32_t)(n) << 16 ) & 0x00FF0000)
#define SYSCFG_PMU_CTRL_SW_EFLASH_PUP_CYCLE_CLR                                   0xFF00FFFF

#define SYSCFG_PMU_CTRL_SW_PUP_CYCLE_SHIFT                                        8
#define SYSCFG_PMU_CTRL_SW_PUP_CYCLE_MASK                                         0x0000FF00
#define SYSCFG_PMU_CTRL_SW_PUP_CYCLE_SET(n)                                       (((uint32_t)(n) << 8  ) & 0x0000FF00)
#define SYSCFG_PMU_CTRL_SW_PUP_CYCLE_CLR                                          0xFFFF00FF

#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_DIV_SYSTICK_SHIFT                           19
#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_DIV_SYSTICK_MASK                            0x00780000
#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_DIV_SYSTICK_SET(n)                          (((uint32_t)(n) << 19 ) & 0x00780000)
#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_DIV_SYSTICK_CLR                             0xFF87FFFF

#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_SEL_SYSTICK_SHIFT                           17
#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_SEL_SYSTICK_MASK                            0x00060000
#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_SEL_SYSTICK_SET(n)                          (((uint32_t)(n) << 17 ) & 0x00060000)
#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_SEL_SYSTICK_CLR                             0xFFF9FFFF

#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_EN_SYSTICK_SHIFT                            16
#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_EN_SYSTICK_MASK                             0x00010000
#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_EN_SYSTICK_SET(n)                           (((uint32_t)(n) << 16 ) & 0x00010000)
#define SYSCFG_M0_CLKRST_CTRL_SW_FCLK_EN_SYSTICK_CLR                              0xFFFEFFFF

#define SYSCFG_M0_CLKRST_CTRL_SW_HCLK_DIV_M0_LOAD_SHIFT                           6
#define SYSCFG_M0_CLKRST_CTRL_SW_HCLK_DIV_M0_LOAD_MASK                            0x00000040
#define SYSCFG_M0_CLKRST_CTRL_SW_HCLK_DIV_M0_LOAD_SET(n)                          (((uint32_t)(n) << 6  ) & 0x00000040)
#define SYSCFG_M0_CLKRST_CTRL_SW_HCLK_DIV_M0_LOAD_CLR                             0xFFFFFFBF

#define SYSCFG_M0_CLKRST_CTRL_SW_HCLK_DIV_M0_SHIFT                                2
#define SYSCFG_M0_CLKRST_CTRL_SW_HCLK_DIV_M0_MASK                                 0x0000003C
#define SYSCFG_M0_CLKRST_CTRL_SW_HCLK_DIV_M0_SET(n)                               (((uint32_t)(n) << 2  ) & 0x0000003C)
#define SYSCFG_M0_CLKRST_CTRL_SW_HCLK_DIV_M0_CLR                                  0xFFFFFFC3

#define SYSCFG_M0_CLKRST_CTRL_SW_M0_LOCKUP_EN_SHIFT                               1
#define SYSCFG_M0_CLKRST_CTRL_SW_M0_LOCKUP_EN_MASK                                0x00000002
#define SYSCFG_M0_CLKRST_CTRL_SW_M0_LOCKUP_EN_SET(n)                              (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_M0_CLKRST_CTRL_SW_M0_LOCKUP_EN_CLR                                 0xFFFFFFFD

#define SYSCFG_M0_CLKRST_CTRL_SW_RST_M0_SHIFT                                     0
#define SYSCFG_M0_CLKRST_CTRL_SW_RST_M0_MASK                                      0x00000001
#define SYSCFG_M0_CLKRST_CTRL_SW_RST_M0_SET(n)                                    (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_M0_CLKRST_CTRL_SW_RST_M0_CLR                                       0xFFFFFFFE

#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_SRAMC_SHIFT                              6
#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_SRAMC_MASK                               0x00000040
#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_SRAMC_SET(n)                             (((uint32_t)(n) << 6  ) & 0x00000040)
#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_SRAMC_CLR                                0xFFFFFFBF

#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_FLASH_SHIFT                              4
#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_FLASH_MASK                               0x00000010
#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_FLASH_SET(n)                             (((uint32_t)(n) << 4  ) & 0x00000010)
#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_FLASH_CLR                                0xFFFFFFEF

#define SYSCFG_HCLK_PCLK_CTRL_SW_RST_FLASH_SHIFT                                  3
#define SYSCFG_HCLK_PCLK_CTRL_SW_RST_FLASH_MASK                                   0x00000008
#define SYSCFG_HCLK_PCLK_CTRL_SW_RST_FLASH_SET(n)                                 (((uint32_t)(n) << 3  ) & 0x00000008)
#define SYSCFG_HCLK_PCLK_CTRL_SW_RST_FLASH_CLR                                    0xFFFFFFF7

#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_FAB_SHIFT                                2
#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_FAB_MASK                                 0x00000004
#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_FAB_SET(n)                               (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_HCLK_PCLK_CTRL_SW_HCLK_EN_FAB_CLR                                  0xFFFFFFFB

#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_DIV_LOAD_SHIFT                         7
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_DIV_LOAD_MASK                          0x00000080
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_DIV_LOAD_SET(n)                        (((uint32_t)(n) << 7  ) & 0x00000080)
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_DIV_LOAD_CLR                           0xFFFFFF7F

#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_EN_BRIDGE_LPMODE_SHIFT                      6
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_EN_BRIDGE_LPMODE_MASK                       0x00000040
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_EN_BRIDGE_LPMODE_SET(n)                     (((uint32_t)(n) << 6  ) & 0x00000040)
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_EN_BRIDGE_LPMODE_CLR                        0xFFFFFFBF

#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_AUTOCG_BRIDGE_SHIFT                    5
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_AUTOCG_BRIDGE_MASK                     0x00000020
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_AUTOCG_BRIDGE_SET(n)                   (((uint32_t)(n) << 5  ) & 0x00000020)
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_AUTOCG_BRIDGE_CLR                      0xFFFFFFDF

#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_HCLK_AUTOCG_BRIDGE_SHIFT                    4
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_HCLK_AUTOCG_BRIDGE_MASK                     0x00000010
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_HCLK_AUTOCG_BRIDGE_SET(n)                   (((uint32_t)(n) << 4  ) & 0x00000010)
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_HCLK_AUTOCG_BRIDGE_CLR                      0xFFFFFFEF

#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_DIV_SHIFT                              1
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_DIV_MASK                               0x0000000E
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_DIV_SET(n)                             (((uint32_t)(n) << 1  ) & 0x0000000E)
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_PCLK_DIV_CLR                                0xFFFFFFF1

#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_RST_BRIDGE_SHIFT                            0
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_RST_BRIDGE_MASK                             0x00000001
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_RST_BRIDGE_SET(n)                           (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_AHB2APB_CLKRST_CTRL_SW_RST_BRIDGE_CLR                              0xFFFFFFFE

#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_DIV_RTC_SHIFT                              5
#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_DIV_RTC_MASK                               0x00001FE0
#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_DIV_RTC_SET(n)                             (((uint32_t)(n) << 5  ) & 0x00001FE0)
#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_DIV_RTC_CLR                                0xFFFFE01F

#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_SEL_RTC_SHIFT                              3
#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_SEL_RTC_MASK                               0x00000018
#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_SEL_RTC_SET(n)                             (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_SEL_RTC_CLR                                0xFFFFFFE7

#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_EN_RTC_SHIFT                               2
#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_EN_RTC_MASK                                0x00000004
#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_EN_RTC_SET(n)                              (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_RTC_CLKRST_CTRL_SW_FCLK_EN_RTC_CLR                                 0xFFFFFFFB

#define SYSCFG_RTC_CLKRST_CTRL_SW_RST_RTC_SHIFT                                   0
#define SYSCFG_RTC_CLKRST_CTRL_SW_RST_RTC_MASK                                    0x00000001
#define SYSCFG_RTC_CLKRST_CTRL_SW_RST_RTC_SET(n)                                  (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_RTC_CLKRST_CTRL_SW_RST_RTC_CLR                                     0xFFFFFFFE

#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_DIV_I2C0_SHIFT                            5
#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_DIV_I2C0_MASK                             0x000001E0
#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_DIV_I2C0_SET(n)                           (((uint32_t)(n) << 5  ) & 0x000001E0)
#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_DIV_I2C0_CLR                              0xFFFFFE1F

#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_SEL_I2C0_SHIFT                            3
#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_SEL_I2C0_MASK                             0x00000018
#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_SEL_I2C0_SET(n)                           (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_SEL_I2C0_CLR                              0xFFFFFFE7

#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_EN_I2C0_SHIFT                             2
#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_EN_I2C0_MASK                              0x00000004
#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_EN_I2C0_SET(n)                            (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_I2C0_CLKRST_CTRL_SW_FCLK_EN_I2C0_CLR                               0xFFFFFFFB

#define SYSCFG_I2C0_CLKRST_CTRL_SW_PCLK_EN_I2C0_SHIFT                             1
#define SYSCFG_I2C0_CLKRST_CTRL_SW_PCLK_EN_I2C0_MASK                              0x00000002
#define SYSCFG_I2C0_CLKRST_CTRL_SW_PCLK_EN_I2C0_SET(n)                            (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_I2C0_CLKRST_CTRL_SW_PCLK_EN_I2C0_CLR                               0xFFFFFFFD

#define SYSCFG_I2C0_CLKRST_CTRL_SW_RST_I2C0_SHIFT                                 0
#define SYSCFG_I2C0_CLKRST_CTRL_SW_RST_I2C0_MASK                                  0x00000001
#define SYSCFG_I2C0_CLKRST_CTRL_SW_RST_I2C0_SET(n)                                (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_I2C0_CLKRST_CTRL_SW_RST_I2C0_CLR                                   0xFFFFFFFE

#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_DIV_UART0_SHIFT                          5
#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_DIV_UART0_MASK                           0x000001E0
#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_DIV_UART0_SET(n)                         (((uint32_t)(n) << 5  ) & 0x000001E0)
#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_DIV_UART0_CLR                            0xFFFFFE1F

#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_SEL_UART0_SHIFT                          3
#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_SEL_UART0_MASK                           0x00000018
#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_SEL_UART0_SET(n)                         (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_SEL_UART0_CLR                            0xFFFFFFE7

#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_EN_UART0_SHIFT                           2
#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_EN_UART0_MASK                            0x00000004
#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_EN_UART0_SET(n)                          (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_UART0_CLKRST_CTRL_SW_FCLK_EN_UART0_CLR                             0xFFFFFFFB

#define SYSCFG_UART0_CLKRST_CTRL_SW_PCLK_EN_UART0_SHIFT                           1
#define SYSCFG_UART0_CLKRST_CTRL_SW_PCLK_EN_UART0_MASK                            0x00000002
#define SYSCFG_UART0_CLKRST_CTRL_SW_PCLK_EN_UART0_SET(n)                          (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_UART0_CLKRST_CTRL_SW_PCLK_EN_UART0_CLR                             0xFFFFFFFD

#define SYSCFG_UART0_CLKRST_CTRL_SW_RST_UART0_SHIFT                               0
#define SYSCFG_UART0_CLKRST_CTRL_SW_RST_UART0_MASK                                0x00000001
#define SYSCFG_UART0_CLKRST_CTRL_SW_RST_UART0_SET(n)                              (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_UART0_CLKRST_CTRL_SW_RST_UART0_CLR                                 0xFFFFFFFE

#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_DIV_UART1_SHIFT                          5
#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_DIV_UART1_MASK                           0x000001E0
#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_DIV_UART1_SET(n)                         (((uint32_t)(n) << 5  ) & 0x000001E0)
#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_DIV_UART1_CLR                            0xFFFFFE1F

#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_SEL_UART1_SHIFT                          3
#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_SEL_UART1_MASK                           0x00000018
#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_SEL_UART1_SET(n)                         (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_SEL_UART1_CLR                            0xFFFFFFE7

#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_EN_UART1_SHIFT                           2
#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_EN_UART1_MASK                            0x00000004
#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_EN_UART1_SET(n)                          (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_UART1_CLKRST_CTRL_SW_FCLK_EN_UART1_CLR                             0xFFFFFFFB

#define SYSCFG_UART1_CLKRST_CTRL_SW_PCLK_EN_UART1_SHIFT                           1
#define SYSCFG_UART1_CLKRST_CTRL_SW_PCLK_EN_UART1_MASK                            0x00000002
#define SYSCFG_UART1_CLKRST_CTRL_SW_PCLK_EN_UART1_SET(n)                          (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_UART1_CLKRST_CTRL_SW_PCLK_EN_UART1_CLR                             0xFFFFFFFD

#define SYSCFG_UART1_CLKRST_CTRL_SW_RST_UART1_SHIFT                               0
#define SYSCFG_UART1_CLKRST_CTRL_SW_RST_UART1_MASK                                0x00000001
#define SYSCFG_UART1_CLKRST_CTRL_SW_RST_UART1_SET(n)                              (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_UART1_CLKRST_CTRL_SW_RST_UART1_CLR                                 0xFFFFFFFE

#define SYSCFG_WDG_CLKRST_CTRL_SW_FCLK_DIV_WDG_SHIFT                              5
#define SYSCFG_WDG_CLKRST_CTRL_SW_FCLK_DIV_WDG_MASK                               0x00001FE0
#define SYSCFG_WDG_CLKRST_CTRL_SW_FCLK_DIV_WDG_SET(n)                             (((uint32_t)(n) << 5  ) & 0x00001FE0)
#define SYSCFG_WDG_CLKRST_CTRL_SW_FCLK_DIV_WDG_CLR                                0xFFFFE01F

#define SYSCFG_WDG_CLKRST_CTRL_SW_FCLK_SEL_WDG_SHIFT                              3
#define SYSCFG_WDG_CLKRST_CTRL_SW_FCLK_SEL_WDG_MASK                               0x00000018
#define SYSCFG_WDG_CLKRST_CTRL_SW_FCLK_SEL_WDG_SET(n)                             (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_WDG_CLKRST_CTRL_SW_FCLK_SEL_WDG_CLR                                0xFFFFFFE7

#define SYSCFG_WDG_CLKRST_CTRL_SW_PCLK_EN_WDG_SHIFT                               1
#define SYSCFG_WDG_CLKRST_CTRL_SW_PCLK_EN_WDG_MASK                                0x00000002
#define SYSCFG_WDG_CLKRST_CTRL_SW_PCLK_EN_WDG_SET(n)                              (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_WDG_CLKRST_CTRL_SW_PCLK_EN_WDG_CLR                                 0xFFFFFFFD

#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_DIV_LVD_SHIFT                              5
#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_DIV_LVD_MASK                               0x0001FFE0
#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_DIV_LVD_SET(n)                             (((uint32_t)(n) << 5  ) & 0x0001FFE0)
#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_DIV_LVD_CLR                                0xFFFE001F

#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_SEL_LVD_SHIFT                              3
#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_SEL_LVD_MASK                               0x00000018
#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_SEL_LVD_SET(n)                             (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_SEL_LVD_CLR                                0xFFFFFFE7

#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_EN_LVD_SHIFT                               2
#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_EN_LVD_MASK                                0x00000004
#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_EN_LVD_SET(n)                              (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_LVD_CLKRST_CTRL_SW_FCLK_EN_LVD_CLR                                 0xFFFFFFFB

#define SYSCFG_LVD_CLKRST_CTRL_SW_PCLK_EN_LVD_SHIFT                               1
#define SYSCFG_LVD_CLKRST_CTRL_SW_PCLK_EN_LVD_MASK                                0x00000002
#define SYSCFG_LVD_CLKRST_CTRL_SW_PCLK_EN_LVD_SET(n)                              (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_LVD_CLKRST_CTRL_SW_PCLK_EN_LVD_CLR                                 0xFFFFFFFD

#define SYSCFG_LVD_CLKRST_CTRL_SW_RST_LVD_SHIFT                                   0
#define SYSCFG_LVD_CLKRST_CTRL_SW_RST_LVD_MASK                                    0x00000001
#define SYSCFG_LVD_CLKRST_CTRL_SW_RST_LVD_SET(n)                                  (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_LVD_CLKRST_CTRL_SW_RST_LVD_CLR                                     0xFFFFFFFE

#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_DIV_SARADC_SHIFT                        5
#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_DIV_SARADC_MASK                         0x0001FFE0
#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_DIV_SARADC_SET(n)                       (((uint32_t)(n) << 5  ) & 0x0001FFE0)
#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_DIV_SARADC_CLR                          0xFFFE001F

#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_SEL_SARADC_SHIFT                        3
#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_SEL_SARADC_MASK                         0x00000018
#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_SEL_SARADC_SET(n)                       (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_SEL_SARADC_CLR                          0xFFFFFFE7

#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_EN_SARADC_SHIFT                         2
#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_EN_SARADC_MASK                          0x00000004
#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_EN_SARADC_SET(n)                        (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_SARADC_CLKRST_CTRL_SW_FCLK_EN_SARADC_CLR                           0xFFFFFFFB

#define SYSCFG_SARADC_CLKRST_CTRL_SW_PCLK_EN_SARADC_SHIFT                         1
#define SYSCFG_SARADC_CLKRST_CTRL_SW_PCLK_EN_SARADC_MASK                          0x00000002
#define SYSCFG_SARADC_CLKRST_CTRL_SW_PCLK_EN_SARADC_SET(n)                        (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_SARADC_CLKRST_CTRL_SW_PCLK_EN_SARADC_CLR                           0xFFFFFFFD

#define SYSCFG_SARADC_CLKRST_CTRL_SW_RST_SARADC_SHIFT                             0
#define SYSCFG_SARADC_CLKRST_CTRL_SW_RST_SARADC_MASK                              0x00000001
#define SYSCFG_SARADC_CLKRST_CTRL_SW_RST_SARADC_SET(n)                            (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_SARADC_CLKRST_CTRL_SW_RST_SARADC_CLR                               0xFFFFFFFE

#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_DIV_CAPTOUCH_SHIFT                    5
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_DIV_CAPTOUCH_MASK                     0x0001FFE0
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_DIV_CAPTOUCH_SET(n)                   (((uint32_t)(n) << 5  ) & 0x0001FFE0)
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_DIV_CAPTOUCH_CLR                      0xFFFE001F

#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_SEL_CAPTOUCH_SHIFT                    3
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_SEL_CAPTOUCH_MASK                     0x00000018
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_SEL_CAPTOUCH_SET(n)                   (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_SEL_CAPTOUCH_CLR                      0xFFFFFFE7

#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_EN_CAPTOUCH_SHIFT                     2
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_EN_CAPTOUCH_MASK                      0x00000004
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_EN_CAPTOUCH_SET(n)                    (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_FCLK_EN_CAPTOUCH_CLR                       0xFFFFFFFB

#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_PCLK_EN_CAPTOUCH_SHIFT                     1
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_PCLK_EN_CAPTOUCH_MASK                      0x00000002
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_PCLK_EN_CAPTOUCH_SET(n)                    (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_PCLK_EN_CAPTOUCH_CLR                       0xFFFFFFFD

#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_RST_CAPTOUCH_SHIFT                         0
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_RST_CAPTOUCH_MASK                          0x00000001
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_RST_CAPTOUCH_SET(n)                        (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_CAPTOUCH_CLKRST_CTRL_SW_RST_CAPTOUCH_CLR                           0xFFFFFFFE

#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_DIV_SPI_SHIFT                              5
#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_DIV_SPI_MASK                               0x000001E0
#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_DIV_SPI_SET(n)                             (((uint32_t)(n) << 5  ) & 0x000001E0)
#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_DIV_SPI_CLR                                0xFFFFFE1F

#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_SEL_SPI_SHIFT                              3
#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_SEL_SPI_MASK                               0x00000018
#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_SEL_SPI_SET(n)                             (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_SEL_SPI_CLR                                0xFFFFFFE7

#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_EN_SPI_SHIFT                               2
#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_EN_SPI_MASK                                0x00000004
#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_EN_SPI_SET(n)                              (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_SPI_CLKRST_CTRL_SW_FCLK_EN_SPI_CLR                                 0xFFFFFFFB

#define SYSCFG_SPI_CLKRST_CTRL_SW_PCLK_EN_SPI_SHIFT                               1
#define SYSCFG_SPI_CLKRST_CTRL_SW_PCLK_EN_SPI_MASK                                0x00000002
#define SYSCFG_SPI_CLKRST_CTRL_SW_PCLK_EN_SPI_SET(n)                              (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_SPI_CLKRST_CTRL_SW_PCLK_EN_SPI_CLR                                 0xFFFFFFFD

#define SYSCFG_SPI_CLKRST_CTRL_SW_RST_SPI_SHIFT                                   0
#define SYSCFG_SPI_CLKRST_CTRL_SW_RST_SPI_MASK                                    0x00000001
#define SYSCFG_SPI_CLKRST_CTRL_SW_RST_SPI_SET(n)                                  (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_SPI_CLKRST_CTRL_SW_RST_SPI_CLR                                     0xFFFFFFFE

#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_DIV_GPT0_SHIFT                            5
#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_DIV_GPT0_MASK                             0x000001E0
#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_DIV_GPT0_SET(n)                           (((uint32_t)(n) << 5  ) & 0x000001E0)
#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_DIV_GPT0_CLR                              0xFFFFFE1F

#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_SEL_GPT0_SHIFT                            3
#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_SEL_GPT0_MASK                             0x00000018
#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_SEL_GPT0_SET(n)                           (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_SEL_GPT0_CLR                              0xFFFFFFE7

#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_EN_GPT0_SHIFT                             2
#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_EN_GPT0_MASK                              0x00000004
#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_EN_GPT0_SET(n)                            (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_GPT0_CLKRST_CTRL_SW_FCLK_EN_GPT0_CLR                               0xFFFFFFFB

#define SYSCFG_GPT0_CLKRST_CTRL_SW_PCLK_EN_GPT0_SHIFT                             1
#define SYSCFG_GPT0_CLKRST_CTRL_SW_PCLK_EN_GPT0_MASK                              0x00000002
#define SYSCFG_GPT0_CLKRST_CTRL_SW_PCLK_EN_GPT0_SET(n)                            (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_GPT0_CLKRST_CTRL_SW_PCLK_EN_GPT0_CLR                               0xFFFFFFFD

#define SYSCFG_GPT0_CLKRST_CTRL_SW_RST_GPT0_SHIFT                                 0
#define SYSCFG_GPT0_CLKRST_CTRL_SW_RST_GPT0_MASK                                  0x00000001
#define SYSCFG_GPT0_CLKRST_CTRL_SW_RST_GPT0_SET(n)                                (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_GPT0_CLKRST_CTRL_SW_RST_GPT0_CLR                                   0xFFFFFFFE

#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_DIV_GPT1_SHIFT                            5
#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_DIV_GPT1_MASK                             0x000001E0
#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_DIV_GPT1_SET(n)                           (((uint32_t)(n) << 5  ) & 0x000001E0)
#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_DIV_GPT1_CLR                              0xFFFFFE1F

#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_SEL_GPT1_SHIFT                            3
#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_SEL_GPT1_MASK                             0x00000018
#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_SEL_GPT1_SET(n)                           (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_SEL_GPT1_CLR                              0xFFFFFFE7

#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_EN_GPT1_SHIFT                             2
#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_EN_GPT1_MASK                              0x00000004
#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_EN_GPT1_SET(n)                            (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_GPT1_CLKRST_CTRL_SW_FCLK_EN_GPT1_CLR                               0xFFFFFFFB

#define SYSCFG_GPT1_CLKRST_CTRL_SW_PCLK_EN_GPT1_SHIFT                             1
#define SYSCFG_GPT1_CLKRST_CTRL_SW_PCLK_EN_GPT1_MASK                              0x00000002
#define SYSCFG_GPT1_CLKRST_CTRL_SW_PCLK_EN_GPT1_SET(n)                            (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_GPT1_CLKRST_CTRL_SW_PCLK_EN_GPT1_CLR                               0xFFFFFFFD

#define SYSCFG_GPT1_CLKRST_CTRL_SW_RST_GPT1_SHIFT                                 0
#define SYSCFG_GPT1_CLKRST_CTRL_SW_RST_GPT1_MASK                                  0x00000001
#define SYSCFG_GPT1_CLKRST_CTRL_SW_RST_GPT1_SET(n)                                (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_GPT1_CLKRST_CTRL_SW_RST_GPT1_CLR                                   0xFFFFFFFE

#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_DIV_GPT2_SHIFT                            5
#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_DIV_GPT2_MASK                             0x000001E0
#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_DIV_GPT2_SET(n)                           (((uint32_t)(n) << 5  ) & 0x000001E0)
#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_DIV_GPT2_CLR                              0xFFFFFE1F

#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_SEL_GPT2_SHIFT                            3
#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_SEL_GPT2_MASK                             0x00000018
#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_SEL_GPT2_SET(n)                           (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_SEL_GPT2_CLR                              0xFFFFFFE7

#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_EN_GPT2_SHIFT                             2
#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_EN_GPT2_MASK                              0x00000004
#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_EN_GPT2_SET(n)                            (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_GPT2_CLKRST_CTRL_SW_FCLK_EN_GPT2_CLR                               0xFFFFFFFB

#define SYSCFG_GPT2_CLKRST_CTRL_SW_PCLK_EN_GPT2_SHIFT                             1
#define SYSCFG_GPT2_CLKRST_CTRL_SW_PCLK_EN_GPT2_MASK                              0x00000002
#define SYSCFG_GPT2_CLKRST_CTRL_SW_PCLK_EN_GPT2_SET(n)                            (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_GPT2_CLKRST_CTRL_SW_PCLK_EN_GPT2_CLR                               0xFFFFFFFD

#define SYSCFG_GPT2_CLKRST_CTRL_SW_RST_GPT2_SHIFT                                 0
#define SYSCFG_GPT2_CLKRST_CTRL_SW_RST_GPT2_MASK                                  0x00000001
#define SYSCFG_GPT2_CLKRST_CTRL_SW_RST_GPT2_SET(n)                                (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_GPT2_CLKRST_CTRL_SW_RST_GPT2_CLR                                   0xFFFFFFFE

#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_DIV_GPT3_SHIFT                            5
#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_DIV_GPT3_MASK                             0x000001E0
#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_DIV_GPT3_SET(n)                           (((uint32_t)(n) << 5  ) & 0x000001E0)
#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_DIV_GPT3_CLR                              0xFFFFFE1F

#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_SEL_GPT3_SHIFT                            3
#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_SEL_GPT3_MASK                             0x00000018
#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_SEL_GPT3_SET(n)                           (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_SEL_GPT3_CLR                              0xFFFFFFE7

#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_EN_GPT3_SHIFT                             2
#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_EN_GPT3_MASK                              0x00000004
#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_EN_GPT3_SET(n)                            (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_GPT3_CLKRST_CTRL_SW_FCLK_EN_GPT3_CLR                               0xFFFFFFFB

#define SYSCFG_GPT3_CLKRST_CTRL_SW_PCLK_EN_GPT3_SHIFT                             1
#define SYSCFG_GPT3_CLKRST_CTRL_SW_PCLK_EN_GPT3_MASK                              0x00000002
#define SYSCFG_GPT3_CLKRST_CTRL_SW_PCLK_EN_GPT3_SET(n)                            (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_GPT3_CLKRST_CTRL_SW_PCLK_EN_GPT3_CLR                               0xFFFFFFFD

#define SYSCFG_GPT3_CLKRST_CTRL_SW_RST_GPT3_SHIFT                                 0
#define SYSCFG_GPT3_CLKRST_CTRL_SW_RST_GPT3_MASK                                  0x00000001
#define SYSCFG_GPT3_CLKRST_CTRL_SW_RST_GPT3_SET(n)                                (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_GPT3_CLKRST_CTRL_SW_RST_GPT3_CLR                                   0xFFFFFFFE

#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_DIV_GPT4_SHIFT                            5
#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_DIV_GPT4_MASK                             0x000001E0
#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_DIV_GPT4_SET(n)                           (((uint32_t)(n) << 5  ) & 0x000001E0)
#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_DIV_GPT4_CLR                              0xFFFFFE1F

#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_SEL_GPT4_SHIFT                            3
#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_SEL_GPT4_MASK                             0x00000018
#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_SEL_GPT4_SET(n)                           (((uint32_t)(n) << 3  ) & 0x00000018)
#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_SEL_GPT4_CLR                              0xFFFFFFE7

#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_EN_GPT4_SHIFT                             2
#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_EN_GPT4_MASK                              0x00000004
#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_EN_GPT4_SET(n)                            (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_GPT4_CLKRST_CTRL_SW_FCLK_EN_GPT4_CLR                               0xFFFFFFFB

#define SYSCFG_GPT4_CLKRST_CTRL_SW_PCLK_EN_GPT4_SHIFT                             1
#define SYSCFG_GPT4_CLKRST_CTRL_SW_PCLK_EN_GPT4_MASK                              0x00000002
#define SYSCFG_GPT4_CLKRST_CTRL_SW_PCLK_EN_GPT4_SET(n)                            (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_GPT4_CLKRST_CTRL_SW_PCLK_EN_GPT4_CLR                               0xFFFFFFFD

#define SYSCFG_GPT4_CLKRST_CTRL_SW_RST_GPT4_SHIFT                                 0
#define SYSCFG_GPT4_CLKRST_CTRL_SW_RST_GPT4_MASK                                  0x00000001
#define SYSCFG_GPT4_CLKRST_CTRL_SW_RST_GPT4_SET(n)                                (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_GPT4_CLKRST_CTRL_SW_RST_GPT4_CLR                                   0xFFFFFFFE

#define SYSCFG_PWM_CTRL_PWM4_EN_SHIFT                                             4
#define SYSCFG_PWM_CTRL_PWM4_EN_MASK                                              0x00000010
#define SYSCFG_PWM_CTRL_PWM4_EN_SET(n)                                            (((uint32_t)(n) << 4  ) & 0x00000010)
#define SYSCFG_PWM_CTRL_PWM4_EN_CLR                                               0xFFFFFFEF

#define SYSCFG_PWM_CTRL_PWM3_EN_SHIFT                                             3
#define SYSCFG_PWM_CTRL_PWM3_EN_MASK                                              0x00000008
#define SYSCFG_PWM_CTRL_PWM3_EN_SET(n)                                            (((uint32_t)(n) << 3  ) & 0x00000008)
#define SYSCFG_PWM_CTRL_PWM3_EN_CLR                                               0xFFFFFFF7

#define SYSCFG_PWM_CTRL_PWM2_EN_SHIFT                                             2
#define SYSCFG_PWM_CTRL_PWM2_EN_MASK                                              0x00000004
#define SYSCFG_PWM_CTRL_PWM2_EN_SET(n)                                            (((uint32_t)(n) << 2  ) & 0x00000004)
#define SYSCFG_PWM_CTRL_PWM2_EN_CLR                                               0xFFFFFFFB

#define SYSCFG_PWM_CTRL_PWM1_EN_SHIFT                                             1
#define SYSCFG_PWM_CTRL_PWM1_EN_MASK                                              0x00000002
#define SYSCFG_PWM_CTRL_PWM1_EN_SET(n)                                            (((uint32_t)(n) << 1  ) & 0x00000002)
#define SYSCFG_PWM_CTRL_PWM1_EN_CLR                                               0xFFFFFFFD

#define SYSCFG_PWM_CTRL_PWM0_EN_SHIFT                                             0
#define SYSCFG_PWM_CTRL_PWM0_EN_MASK                                              0x00000001
#define SYSCFG_PWM_CTRL_PWM0_EN_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_PWM_CTRL_PWM0_EN_CLR                                               0xFFFFFFFE

#define SYSCFG_TP_TP_SEL_SHIFT                                                    29
#define SYSCFG_TP_TP_SEL_MASK                                                     0xE0000000
#define SYSCFG_TP_TP_SEL_SET(n)                                                   (((uint32_t)(n) << 29 ) & 0xE0000000)
#define SYSCFG_TP_TP_SEL_CLR                                                      0x1FFFFFFF

#define SYSCFG_TP_TP_EN_SHIFT                                                     0
#define SYSCFG_TP_TP_EN_MASK                                                      0x1FFFFFFF
#define SYSCFG_TP_TP_EN_SET(n)                                                    (((uint32_t)(n) << 0  ) & 0x1FFFFFFF)
#define SYSCFG_TP_TP_EN_CLR                                                       0xE0000000

#define SYSCFG_TEST_CTRL_TEST_CLK_DIV2_EN_SHIFT                                   13
#define SYSCFG_TEST_CTRL_TEST_CLK_DIV2_EN_MASK                                    0x00002000
#define SYSCFG_TEST_CTRL_TEST_CLK_DIV2_EN_SET(n)                                  (((uint32_t)(n) << 13 ) & 0x00002000)
#define SYSCFG_TEST_CTRL_TEST_CLK_DIV2_EN_CLR                                     0xFFFFDFFF

#define SYSCFG_TEST_CTRL_TEST_BUS_NIBBLE_SWAP_SHIFT                               12
#define SYSCFG_TEST_CTRL_TEST_BUS_NIBBLE_SWAP_MASK                                0x00001000
#define SYSCFG_TEST_CTRL_TEST_BUS_NIBBLE_SWAP_SET(n)                              (((uint32_t)(n) << 12 ) & 0x00001000)
#define SYSCFG_TEST_CTRL_TEST_BUS_NIBBLE_SWAP_CLR                                 0xFFFFEFFF

#define SYSCFG_TEST_CTRL_TEST_BUS_MSB_SEL_SHIFT                                   11
#define SYSCFG_TEST_CTRL_TEST_BUS_MSB_SEL_MASK                                    0x00000800
#define SYSCFG_TEST_CTRL_TEST_BUS_MSB_SEL_SET(n)                                  (((uint32_t)(n) << 11 ) & 0x00000800)
#define SYSCFG_TEST_CTRL_TEST_BUS_MSB_SEL_CLR                                     0xFFFFF7FF

#define SYSCFG_TEST_CTRL_TEST_CLK_SEL_SHIFT                                       8
#define SYSCFG_TEST_CTRL_TEST_CLK_SEL_MASK                                        0x00000700
#define SYSCFG_TEST_CTRL_TEST_CLK_SEL_SET(n)                                      (((uint32_t)(n) << 8  ) & 0x00000700)
#define SYSCFG_TEST_CTRL_TEST_CLK_SEL_CLR                                         0xFFFFF8FF

#define SYSCFG_TEST_CTRL_TEST_IP_SEL_SHIFT                                        4
#define SYSCFG_TEST_CTRL_TEST_IP_SEL_MASK                                         0x000000F0
#define SYSCFG_TEST_CTRL_TEST_IP_SEL_SET(n)                                       (((uint32_t)(n) << 4  ) & 0x000000F0)
#define SYSCFG_TEST_CTRL_TEST_IP_SEL_CLR                                          0xFFFFFF0F

#define SYSCFG_TEST_CTRL_TEST_BUS_EN_SHIFT                                        3
#define SYSCFG_TEST_CTRL_TEST_BUS_EN_MASK                                         0x00000008
#define SYSCFG_TEST_CTRL_TEST_BUS_EN_SET(n)                                       (((uint32_t)(n) << 3  ) & 0x00000008)
#define SYSCFG_TEST_CTRL_TEST_BUS_EN_CLR                                          0xFFFFFFF7

#define SYSCFG_TEST_CTRL_TEST_BUS_SEL_SHIFT                                       1
#define SYSCFG_TEST_CTRL_TEST_BUS_SEL_MASK                                        0x00000006
#define SYSCFG_TEST_CTRL_TEST_BUS_SEL_SET(n)                                      (((uint32_t)(n) << 1  ) & 0x00000006)
#define SYSCFG_TEST_CTRL_TEST_BUS_SEL_CLR                                         0xFFFFFFF9

#define SYSCFG_TEST_CTRL_TEST_CLK32_OUT_EN_SHIFT                                  0
#define SYSCFG_TEST_CTRL_TEST_CLK32_OUT_EN_MASK                                   0x00000001
#define SYSCFG_TEST_CTRL_TEST_CLK32_OUT_EN_SET(n)                                 (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_TEST_CTRL_TEST_CLK32_OUT_EN_CLR                                    0xFFFFFFFE

#define SYSCFG_WR_LOCK_CTRL_WR_LOCK_SHIFT                                         0
#define SYSCFG_WR_LOCK_CTRL_WR_LOCK_MASK                                          0x00000001
#define SYSCFG_WR_LOCK_CTRL_WR_LOCK_SET(n)                                        (((uint32_t)(n) << 0  ) & 0x00000001)
#define SYSCFG_WR_LOCK_CTRL_WR_LOCK_CLR                                           0xFFFFFFFE

// Register Structure Definition
typedef struct
{
    __IO uint32_t RESERVED5             : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_AON        : 1  ; // 1  : 1 
    __IO uint32_t RESERVED4             : 3  ; // 4  : 2 
    __IO uint32_t SW_RST_APINMUX        : 1  ; // 5  : 5 
    __IO uint32_t SW_RST_ACFG           : 1  ; // 6  : 6 
    __IO uint32_t RESERVED3             : 1  ; // 7  : 7 
    __IO uint32_t SW_RST_GPIOA          : 1  ; // 8  : 8 
    __IO uint32_t SW_PCLK_EN_GPIOA      : 1  ; // 9  : 9 
    __IO uint32_t SW_FCLK_EN_GPIOA      : 1  ; // 10 : 10 
    __IO uint32_t RESERVED2             : 1  ; // 11 : 11 
    __IO uint32_t SW_RST_GPIOB          : 1  ; // 12 : 12 
    __IO uint32_t SW_PCLK_EN_GPIOB      : 1  ; // 13 : 13 
    __IO uint32_t SW_FCLK_EN_GPIOB      : 1  ; // 14 : 14 
    __IO uint32_t RESERVED1             : 1  ; // 15 : 15 
    __IO uint32_t RESERVED0             : 16 ; // 31 : 16 
} SYSCFG_AONTOP_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t RESERVED0             : 8  ; // 7  : 0 
    __IO uint32_t SW_PUP_CYCLE          : 8  ; // 15 : 8 
    __IO uint32_t SW_EFLASH_PUP_CYCLE   : 8  ; // 23 : 16 
    __IO uint32_t SW_EFLASH_INIT_CYCLE  : 8  ; // 31 : 24 
} SYSCFG_PMU_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_M0             : 1  ; // 0  : 0 
    __IO uint32_t SW_M0_LOCKUP_EN       : 1  ; // 1  : 1 
    __IO uint32_t SW_HCLK_DIV_M0        : 4  ; // 5  : 2 
    __IO uint32_t SW_HCLK_DIV_M0_LOAD   : 1  ; // 6  : 6 
    __IO uint32_t RESERVED1             : 9  ; // 15 : 7 
    __IO uint32_t SW_FCLK_EN_SYSTICK    : 1  ; // 16 : 16 
    __IO uint32_t SW_FCLK_SEL_SYSTICK   : 2  ; // 18 : 17 
    __IO uint32_t SW_FCLK_DIV_SYSTICK   : 4  ; // 22 : 19 
    __IO uint32_t RESERVED0             : 9  ; // 31 : 23 
} SYSCFG_M0_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t RESERVED3             : 1  ; // 0  : 0 
    __IO uint32_t RESERVED2             : 1  ; // 1  : 1 
    __IO uint32_t SW_HCLK_EN_FAB        : 1  ; // 2  : 2 
    __IO uint32_t SW_RST_FLASH          : 1  ; // 3  : 3 
    __IO uint32_t SW_HCLK_EN_FLASH      : 1  ; // 4  : 4 
    __IO uint32_t RESERVED1             : 1  ; // 5  : 5 
    __IO uint32_t SW_HCLK_EN_SRAMC      : 1  ; // 6  : 6 
    __IO uint32_t RESERVED0             : 25 ; // 31 : 7 
} SYSCFG_HCLK_PCLK_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_BRIDGE         : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_DIV           : 3  ; // 3  : 1 
    __IO uint32_t SW_HCLK_AUTOCG_BRIDGE : 1  ; // 4  : 4 
    __IO uint32_t SW_PCLK_AUTOCG_BRIDGE : 1  ; // 5  : 5 
    __IO uint32_t SW_EN_BRIDGE_LPMODE   : 1  ; // 6  : 6 
    __IO uint32_t SW_PCLK_DIV_LOAD      : 1  ; // 7  : 7 
    __IO uint32_t RESERVED0             : 24 ; // 31 : 8 
} SYSCFG_AHB2APB_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_RTC            : 1  ; // 0  : 0 
    __IO uint32_t RESERVED1             : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_RTC        : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_RTC       : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_RTC       : 8  ; // 12 : 5 
    __IO uint32_t RESERVED0             : 19 ; // 31 : 13 
} SYSCFG_RTC_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_I2C0           : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_I2C0       : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_I2C0       : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_I2C0      : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_I2C0      : 4  ; // 8  : 5 
    __IO uint32_t RESERVED0             : 23 ; // 31 : 9 
} SYSCFG_I2C0_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_UART0          : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_UART0      : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_UART0      : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_UART0     : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_UART0     : 4  ; // 8  : 5 
    __IO uint32_t RESERVED0             : 23 ; // 31 : 9 
} SYSCFG_UART0_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_UART1          : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_UART1      : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_UART1      : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_UART1     : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_UART1     : 4  ; // 8  : 5 
    __IO uint32_t RESERVED0             : 23 ; // 31 : 9 
} SYSCFG_UART1_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t RESERVED2             : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_WDG        : 1  ; // 1  : 1 
    __IO uint32_t RESERVED1             : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_WDG       : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_WDG       : 8  ; // 12 : 5 
    __IO uint32_t RESERVED0             : 19 ; // 31 : 13 
} SYSCFG_WDG_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_LVD            : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_LVD        : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_LVD        : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_LVD       : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_LVD       : 12 ; // 16 : 5 
    __IO uint32_t RESERVED0             : 15 ; // 31 : 17 
} SYSCFG_LVD_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_SARADC         : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_SARADC     : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_SARADC     : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_SARADC    : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_SARADC    : 12 ; // 16 : 5 
    __IO uint32_t RESERVED0             : 15 ; // 31 : 17 
} SYSCFG_SARADC_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_CAPTOUCH       : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_CAPTOUCH   : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_CAPTOUCH   : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_CAPTOUCH  : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_CAPTOUCH  : 12 ; // 16 : 5 
    __IO uint32_t RESERVED0             : 15 ; // 31 : 17 
} SYSCFG_CAPTOUCH_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_SPI            : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_SPI        : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_SPI        : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_SPI       : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_SPI       : 4  ; // 8  : 5 
    __IO uint32_t RESERVED0             : 23 ; // 31 : 9 
} SYSCFG_SPI_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_GPT0           : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_GPT0       : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_GPT0       : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_GPT0      : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_GPT0      : 4  ; // 8  : 5 
    __IO uint32_t RESERVED0             : 23 ; // 31 : 9 
} SYSCFG_GPT0_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_GPT1           : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_GPT1       : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_GPT1       : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_GPT1      : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_GPT1      : 4  ; // 8  : 5 
    __IO uint32_t RESERVED0             : 23 ; // 31 : 9 
} SYSCFG_GPT1_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_GPT2           : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_GPT2       : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_GPT2       : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_GPT2      : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_GPT2      : 4  ; // 8  : 5 
    __IO uint32_t RESERVED0             : 23 ; // 31 : 9 
} SYSCFG_GPT2_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_GPT3           : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_GPT3       : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_GPT3       : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_GPT3      : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_GPT3      : 4  ; // 8  : 5 
    __IO uint32_t RESERVED0             : 23 ; // 31 : 9 
} SYSCFG_GPT3_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t SW_RST_GPT4           : 1  ; // 0  : 0 
    __IO uint32_t SW_PCLK_EN_GPT4       : 1  ; // 1  : 1 
    __IO uint32_t SW_FCLK_EN_GPT4       : 1  ; // 2  : 2 
    __IO uint32_t SW_FCLK_SEL_GPT4      : 2  ; // 4  : 3 
    __IO uint32_t SW_FCLK_DIV_GPT4      : 4  ; // 8  : 5 
    __IO uint32_t RESERVED0             : 23 ; // 31 : 9 
} SYSCFG_GPT4_CLKRST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t PWM0_EN               : 1  ; // 0  : 0 
    __IO uint32_t PWM1_EN               : 1  ; // 1  : 1 
    __IO uint32_t PWM2_EN               : 1  ; // 2  : 2 
    __IO uint32_t PWM3_EN               : 1  ; // 3  : 3 
    __IO uint32_t PWM4_EN               : 1  ; // 4  : 4 
    __IO uint32_t RESERVED0             : 27 ; // 31 : 5 
} SYSCFG_PWM_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t TP_EN                 : 29 ; // 28 : 0 
    __IO uint32_t TP_SEL                : 3  ; // 31 : 29 
} SYSCFG_TP_FIELD_T;

typedef struct
{
    __IO uint32_t TEST_CLK32_OUT_EN     : 1  ; // 0  : 0 
    __IO uint32_t TEST_BUS_SEL          : 2  ; // 2  : 1 
    __IO uint32_t TEST_BUS_EN           : 1  ; // 3  : 3 
    __IO uint32_t TEST_IP_SEL           : 4  ; // 7  : 4 
    __IO uint32_t TEST_CLK_SEL          : 3  ; // 10 : 8 
    __IO uint32_t TEST_BUS_MSB_SEL      : 1  ; // 11 : 11 
    __IO uint32_t TEST_BUS_NIBBLE_SWAP  : 1  ; // 12 : 12 
    __IO uint32_t TEST_CLK_DIV2_EN      : 1  ; // 13 : 13 
    __IO uint32_t RESERVED0             : 18 ; // 31 : 14 
} SYSCFG_TEST_CTRL_FIELD_T;

typedef struct
{
    __IO uint32_t WR_LOCK               : 1  ; // 0  : 0 
    __IO uint32_t RESERVED0             : 31 ; // 31 : 1 
} SYSCFG_WR_LOCK_CTRL_FIELD_T;

// Register Map Structure Definition
typedef struct
{
    union 
    { 
        __IO  uint32_t AONTOP_CLKRST_CTRL                          ; // 0x0000
        SYSCFG_AONTOP_CLKRST_CTRL_FIELD_T AONTOP_CLKRST_CTRL_F     ;
    };

    union 
    { 
        __IO  uint32_t PMU_CTRL                                    ; // 0x0004
        SYSCFG_PMU_CTRL_FIELD_T PMU_CTRL_F                         ;
    };

    union 
    { 
        __IO  uint32_t M0_CLKRST_CTRL                              ; // 0x0008
        SYSCFG_M0_CLKRST_CTRL_FIELD_T M0_CLKRST_CTRL_F             ;
    };

    union 
    { 
        __IO  uint32_t HCLK_PCLK_CTRL                              ; // 0x000C
        SYSCFG_HCLK_PCLK_CTRL_FIELD_T HCLK_PCLK_CTRL_F             ;
    };

    union 
    { 
        __IO  uint32_t AHB2APB_CLKRST_CTRL                         ; // 0x0010
        SYSCFG_AHB2APB_CLKRST_CTRL_FIELD_T AHB2APB_CLKRST_CTRL_F   ;
    };

    union 
    { 
        __IO  uint32_t RTC_CLKRST_CTRL                             ; // 0x0014
        SYSCFG_RTC_CLKRST_CTRL_FIELD_T RTC_CLKRST_CTRL_F           ;
    };

    union 
    { 
        __IO  uint32_t I2C0_CLKRST_CTRL                            ; // 0x0018
        SYSCFG_I2C0_CLKRST_CTRL_FIELD_T I2C0_CLKRST_CTRL_F         ;
    };

    union 
    { 
        __IO  uint32_t UART0_CLKRST_CTRL                           ; // 0x001C
        SYSCFG_UART0_CLKRST_CTRL_FIELD_T UART0_CLKRST_CTRL_F       ;
    };

    union 
    { 
        __IO  uint32_t UART1_CLKRST_CTRL                           ; // 0x0020
        SYSCFG_UART1_CLKRST_CTRL_FIELD_T UART1_CLKRST_CTRL_F       ;
    };

    union 
    { 
        __IO  uint32_t WDG_CLKRST_CTRL                             ; // 0x0024
        SYSCFG_WDG_CLKRST_CTRL_FIELD_T WDG_CLKRST_CTRL_F           ;
    };

    union 
    { 
        __IO  uint32_t LVD_CLKRST_CTRL                             ; // 0x0028
        SYSCFG_LVD_CLKRST_CTRL_FIELD_T LVD_CLKRST_CTRL_F           ;
    };

    union 
    { 
        __IO  uint32_t SARADC_CLKRST_CTRL                          ; // 0x002C
        SYSCFG_SARADC_CLKRST_CTRL_FIELD_T SARADC_CLKRST_CTRL_F     ;
    };

    union 
    { 
        __IO  uint32_t CAPTOUCH_CLKRST_CTRL                        ; // 0x0030
        SYSCFG_CAPTOUCH_CLKRST_CTRL_FIELD_T CAPTOUCH_CLKRST_CTRL_F ;
    };

    union 
    { 
        __IO  uint32_t SPI_CLKRST_CTRL                             ; // 0x0034
        SYSCFG_SPI_CLKRST_CTRL_FIELD_T SPI_CLKRST_CTRL_F           ;
    };

    union 
    { 
        __IO  uint32_t GPT0_CLKRST_CTRL                            ; // 0x0038
        SYSCFG_GPT0_CLKRST_CTRL_FIELD_T GPT0_CLKRST_CTRL_F         ;
    };

    union 
    { 
        __IO  uint32_t GPT1_CLKRST_CTRL                            ; // 0x003C
        SYSCFG_GPT1_CLKRST_CTRL_FIELD_T GPT1_CLKRST_CTRL_F         ;
    };

    union 
    { 
        __IO  uint32_t GPT2_CLKRST_CTRL                            ; // 0x0040
        SYSCFG_GPT2_CLKRST_CTRL_FIELD_T GPT2_CLKRST_CTRL_F         ;
    };

    union 
    { 
        __IO  uint32_t GPT3_CLKRST_CTRL                            ; // 0x0044
        SYSCFG_GPT3_CLKRST_CTRL_FIELD_T GPT3_CLKRST_CTRL_F         ;
    };

    union 
    { 
        __IO  uint32_t GPT4_CLKRST_CTRL                            ; // 0x0048
        SYSCFG_GPT4_CLKRST_CTRL_FIELD_T GPT4_CLKRST_CTRL_F         ;
    };

    union 
    { 
        __IO  uint32_t PWM_CTRL                                    ; // 0x004C
        SYSCFG_PWM_CTRL_FIELD_T PWM_CTRL_F                         ;
    };

    union 
    { 
        __IO  uint32_t TP                                          ; // 0x0050
        SYSCFG_TP_FIELD_T TP_F                                     ;
    };

    union 
    { 
        __IO  uint32_t TEST_CTRL                                   ; // 0x0054
        SYSCFG_TEST_CTRL_FIELD_T TEST_CTRL_F                       ;
    };

    uint32_t RESERVED0[16361]                                          ;

    union 
    { 
        __IO  uint32_t WR_LOCK_CTRL                                ; // 0xFFFC
        SYSCFG_WR_LOCK_CTRL_FIELD_T WR_LOCK_CTRL_F                 ;
    };

} SYSCFG_REG_TypeDef;

#endif
