//----------------------------------------------------------------------
//         COPYRIGHT (C) 2022 TINYCHIP SEMICONDUCTOR                    
    //              CONFIDENTIAL & ALL RIGHTS RESERVED                      
//----------------------------------------------------------------------
// File name      : pdma_reg_def.h                                      
// Author         : mfpan                                               
// E-Mail         : mfpan@tinychip.com.cn                               
//----------------------------------------------------------------------
// Description    :                                                     
// Register Header File of PDMA                                      
//----------------------------------------------------------------------
// Reversion History:                                                   
// 2022-10-21 17:24:12 -- automatically generated by reg_gen.pl Revision 1.11          
//----------------------------------------------------------------------

#ifndef   PDMA_DEF_H__
#define   PDMA_DEF_H__

// Register Offset Macro Definition
#define PDMA_DCSR0_OFFSET                                       0x0000
#define PDMA_DCSR1_OFFSET                                       0x0004
#define PDMA_DCSR2_OFFSET                                       0x0008
#define PDMA_DALGN0_OFFSET                                      0x0040
#define PDMA_DALGN1_OFFSET                                      0x0044
#define PDMA_DALGN2_OFFSET                                      0x0048
#define PDMA_DRQSR0_OFFSET                                      0x0080
#define PDMA_DRQSR1_OFFSET                                      0x0084
#define PDMA_DRQSR2_OFFSET                                      0x0088
#define PDMA_DINT_OFFSET                                        0x008C
#define PDMA_DRCMR0_OFFSET                                      0x0100
#define PDMA_DRCMR1_OFFSET                                      0x0104
#define PDMA_DRCMR2_OFFSET                                      0x0108
#define PDMA_DRCMR3_OFFSET                                      0x010C
#define PDMA_DRCMR4_OFFSET                                      0x0110
#define PDMA_DRCMR5_OFFSET                                      0x0114
#define PDMA_DRCMR6_OFFSET                                      0x0118
#define PDMA_DRCMR7_OFFSET                                      0x011C
#define PDMA_DRCMR8_OFFSET                                      0x0120
#define PDMA_DRCMR9_OFFSET                                      0x0124
#define PDMA_DRCMR10_OFFSET                                     0x0128
#define PDMA_DESC0_DDADR_OFFSET                                 0x0200
#define PDMA_DESC0_DSADR_OFFSET                                 0x0204
#define PDMA_DESC0_DTADR_OFFSET                                 0x0208
#define PDMA_DESC0_DCMD_OFFSET                                  0x020C
#define PDMA_DESC1_DDADR_OFFSET                                 0x0210
#define PDMA_DESC1_DSADR_OFFSET                                 0x0214
#define PDMA_DESC1_DTADR_OFFSET                                 0x0218
#define PDMA_DESC1_DCMD_OFFSET                                  0x021C
#define PDMA_DESC2_DDADR_OFFSET                                 0x0220
#define PDMA_DESC2_DSADR_OFFSET                                 0x0224
#define PDMA_DESC2_DTADR_OFFSET                                 0x0228
#define PDMA_DESC2_DCMD_OFFSET                                  0x022C

// Register Address Macro Definition
#define PDMA_DCSR0_ADDR                                         ( PDMA_BASE_ADDR + PDMA_DCSR0_OFFSET)
#define PDMA_DCSR1_ADDR                                         ( PDMA_BASE_ADDR + PDMA_DCSR1_OFFSET)
#define PDMA_DCSR2_ADDR                                         ( PDMA_BASE_ADDR + PDMA_DCSR2_OFFSET)
#define PDMA_DALGN0_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DALGN0_OFFSET)
#define PDMA_DALGN1_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DALGN1_OFFSET)
#define PDMA_DALGN2_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DALGN2_OFFSET)
#define PDMA_DRQSR0_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRQSR0_OFFSET)
#define PDMA_DRQSR1_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRQSR1_OFFSET)
#define PDMA_DRQSR2_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRQSR2_OFFSET)
#define PDMA_DINT_ADDR                                          ( PDMA_BASE_ADDR + PDMA_DINT_OFFSET)
#define PDMA_DRCMR0_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRCMR0_OFFSET)
#define PDMA_DRCMR1_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRCMR1_OFFSET)
#define PDMA_DRCMR2_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRCMR2_OFFSET)
#define PDMA_DRCMR3_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRCMR3_OFFSET)
#define PDMA_DRCMR4_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRCMR4_OFFSET)
#define PDMA_DRCMR5_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRCMR5_OFFSET)
#define PDMA_DRCMR6_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRCMR6_OFFSET)
#define PDMA_DRCMR7_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRCMR7_OFFSET)
#define PDMA_DRCMR8_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRCMR8_OFFSET)
#define PDMA_DRCMR9_ADDR                                        ( PDMA_BASE_ADDR + PDMA_DRCMR9_OFFSET)
#define PDMA_DRCMR10_ADDR                                       ( PDMA_BASE_ADDR + PDMA_DRCMR10_OFFSET)
#define PDMA_DESC0_DDADR_ADDR                                   ( PDMA_BASE_ADDR + PDMA_DESC0_DDADR_OFFSET)
#define PDMA_DESC0_DSADR_ADDR                                   ( PDMA_BASE_ADDR + PDMA_DESC0_DSADR_OFFSET)
#define PDMA_DESC0_DTADR_ADDR                                   ( PDMA_BASE_ADDR + PDMA_DESC0_DTADR_OFFSET)
#define PDMA_DESC0_DCMD_ADDR                                    ( PDMA_BASE_ADDR + PDMA_DESC0_DCMD_OFFSET)
#define PDMA_DESC1_DDADR_ADDR                                   ( PDMA_BASE_ADDR + PDMA_DESC1_DDADR_OFFSET)
#define PDMA_DESC1_DSADR_ADDR                                   ( PDMA_BASE_ADDR + PDMA_DESC1_DSADR_OFFSET)
#define PDMA_DESC1_DTADR_ADDR                                   ( PDMA_BASE_ADDR + PDMA_DESC1_DTADR_OFFSET)
#define PDMA_DESC1_DCMD_ADDR                                    ( PDMA_BASE_ADDR + PDMA_DESC1_DCMD_OFFSET)
#define PDMA_DESC2_DDADR_ADDR                                   ( PDMA_BASE_ADDR + PDMA_DESC2_DDADR_OFFSET)
#define PDMA_DESC2_DSADR_ADDR                                   ( PDMA_BASE_ADDR + PDMA_DESC2_DSADR_OFFSET)
#define PDMA_DESC2_DTADR_ADDR                                   ( PDMA_BASE_ADDR + PDMA_DESC2_DTADR_OFFSET)
#define PDMA_DESC2_DCMD_ADDR                                    ( PDMA_BASE_ADDR + PDMA_DESC2_DCMD_OFFSET)

// Register Field Macro Definition
#define PDMA_DCSR0_DCSR0_RUN_SHIFT                                                  31
#define PDMA_DCSR0_DCSR0_RUN_MASK                                                   0x80000000
#define PDMA_DCSR0_DCSR0_RUN_SET(n)                                                 (((uint32_t)(n) << 31 ) & 0x80000000)
#define PDMA_DCSR0_DCSR0_RUN_CLR                                                    0x7FFFFFFF

#define PDMA_DCSR0_DCSR0_ENABLE_SHIFT                                               30
#define PDMA_DCSR0_DCSR0_ENABLE_MASK                                                0x40000000
#define PDMA_DCSR0_DCSR0_ENABLE_SET(n)                                              (((uint32_t)(n) << 30 ) & 0x40000000)
#define PDMA_DCSR0_DCSR0_ENABLE_CLR                                                 0xBFFFFFFF

#define PDMA_DCSR0_DCSR0_STOPIRQEN_SHIFT                                            29
#define PDMA_DCSR0_DCSR0_STOPIRQEN_MASK                                             0x20000000
#define PDMA_DCSR0_DCSR0_STOPIRQEN_SET(n)                                           (((uint32_t)(n) << 29 ) & 0x20000000)
#define PDMA_DCSR0_DCSR0_STOPIRQEN_CLR                                              0xDFFFFFFF

#define PDMA_DCSR0_DCSR0_RASIRQEN_SHIFT                                             23
#define PDMA_DCSR0_DCSR0_RASIRQEN_MASK                                              0x00800000
#define PDMA_DCSR0_DCSR0_RASIRQEN_SET(n)                                            (((uint32_t)(n) << 23 ) & 0x00800000)
#define PDMA_DCSR0_DCSR0_RASIRQEN_CLR                                               0xFF7FFFFF

#define PDMA_DCSR0_DCSR0_MASKRUN_SHIFT                                              22
#define PDMA_DCSR0_DCSR0_MASKRUN_MASK                                               0x00400000
#define PDMA_DCSR0_DCSR0_MASKRUN_SET(n)                                             (((uint32_t)(n) << 22 ) & 0x00400000)
#define PDMA_DCSR0_DCSR0_MASKRUN_CLR                                                0xFFBFFFFF

#define PDMA_DCSR0_DCSR0_REQPEND_SHIFT                                              8
#define PDMA_DCSR0_DCSR0_REQPEND_MASK                                               0x00000100
#define PDMA_DCSR0_DCSR0_REQPEND_SET(n)                                             (((uint32_t)(n) << 8  ) & 0x00000100)
#define PDMA_DCSR0_DCSR0_REQPEND_CLR                                                0xFFFFFEFF

#define PDMA_DCSR0_DCSR0_RASINTR_SHIFT                                              4
#define PDMA_DCSR0_DCSR0_RASINTR_MASK                                               0x00000010
#define PDMA_DCSR0_DCSR0_RASINTR_SET(n)                                             (((uint32_t)(n) << 4  ) & 0x00000010)
#define PDMA_DCSR0_DCSR0_RASINTR_CLR                                                0xFFFFFFEF

#define PDMA_DCSR0_DCSR0_STOPINTR_SHIFT                                             3
#define PDMA_DCSR0_DCSR0_STOPINTR_MASK                                              0x00000008
#define PDMA_DCSR0_DCSR0_STOPINTR_SET(n)                                            (((uint32_t)(n) << 3  ) & 0x00000008)
#define PDMA_DCSR0_DCSR0_STOPINTR_CLR                                               0xFFFFFFF7

#define PDMA_DCSR0_DCSR0_ENDINTR_SHIFT                                              2
#define PDMA_DCSR0_DCSR0_ENDINTR_MASK                                               0x00000004
#define PDMA_DCSR0_DCSR0_ENDINTR_SET(n)                                             (((uint32_t)(n) << 2  ) & 0x00000004)
#define PDMA_DCSR0_DCSR0_ENDINTR_CLR                                                0xFFFFFFFB

#define PDMA_DCSR0_DCSR0_BUSERRINTR_SHIFT                                           0
#define PDMA_DCSR0_DCSR0_BUSERRINTR_MASK                                            0x00000001
#define PDMA_DCSR0_DCSR0_BUSERRINTR_SET(n)                                          (((uint32_t)(n) << 0  ) & 0x00000001)
#define PDMA_DCSR0_DCSR0_BUSERRINTR_CLR                                             0xFFFFFFFE

#define PDMA_DCSR1_DCSR1_RUN_SHIFT                                                  31
#define PDMA_DCSR1_DCSR1_RUN_MASK                                                   0x80000000
#define PDMA_DCSR1_DCSR1_RUN_SET(n)                                                 (((uint32_t)(n) << 31 ) & 0x80000000)
#define PDMA_DCSR1_DCSR1_RUN_CLR                                                    0x7FFFFFFF

#define PDMA_DCSR1_DCSR1_ENABLE_SHIFT                                               30
#define PDMA_DCSR1_DCSR1_ENABLE_MASK                                                0x40000000
#define PDMA_DCSR1_DCSR1_ENABLE_SET(n)                                              (((uint32_t)(n) << 30 ) & 0x40000000)
#define PDMA_DCSR1_DCSR1_ENABLE_CLR                                                 0xBFFFFFFF

#define PDMA_DCSR1_DCSR1_STOPIRQEN_SHIFT                                            29
#define PDMA_DCSR1_DCSR1_STOPIRQEN_MASK                                             0x20000000
#define PDMA_DCSR1_DCSR1_STOPIRQEN_SET(n)                                           (((uint32_t)(n) << 29 ) & 0x20000000)
#define PDMA_DCSR1_DCSR1_STOPIRQEN_CLR                                              0xDFFFFFFF

#define PDMA_DCSR1_DCSR1_RASIRQEN_SHIFT                                             23
#define PDMA_DCSR1_DCSR1_RASIRQEN_MASK                                              0x00800000
#define PDMA_DCSR1_DCSR1_RASIRQEN_SET(n)                                            (((uint32_t)(n) << 23 ) & 0x00800000)
#define PDMA_DCSR1_DCSR1_RASIRQEN_CLR                                               0xFF7FFFFF

#define PDMA_DCSR1_DCSR1_MASKRUN_SHIFT                                              22
#define PDMA_DCSR1_DCSR1_MASKRUN_MASK                                               0x00400000
#define PDMA_DCSR1_DCSR1_MASKRUN_SET(n)                                             (((uint32_t)(n) << 22 ) & 0x00400000)
#define PDMA_DCSR1_DCSR1_MASKRUN_CLR                                                0xFFBFFFFF

#define PDMA_DCSR1_DCSR1_REQPEND_SHIFT                                              8
#define PDMA_DCSR1_DCSR1_REQPEND_MASK                                               0x00000100
#define PDMA_DCSR1_DCSR1_REQPEND_SET(n)                                             (((uint32_t)(n) << 8  ) & 0x00000100)
#define PDMA_DCSR1_DCSR1_REQPEND_CLR                                                0xFFFFFEFF

#define PDMA_DCSR1_DCSR1_RASINTR_SHIFT                                              4
#define PDMA_DCSR1_DCSR1_RASINTR_MASK                                               0x00000010
#define PDMA_DCSR1_DCSR1_RASINTR_SET(n)                                             (((uint32_t)(n) << 4  ) & 0x00000010)
#define PDMA_DCSR1_DCSR1_RASINTR_CLR                                                0xFFFFFFEF

#define PDMA_DCSR1_DCSR1_STOPINTR_SHIFT                                             3
#define PDMA_DCSR1_DCSR1_STOPINTR_MASK                                              0x00000008
#define PDMA_DCSR1_DCSR1_STOPINTR_SET(n)                                            (((uint32_t)(n) << 3  ) & 0x00000008)
#define PDMA_DCSR1_DCSR1_STOPINTR_CLR                                               0xFFFFFFF7

#define PDMA_DCSR1_DCSR1_ENDINTR_SHIFT                                              2
#define PDMA_DCSR1_DCSR1_ENDINTR_MASK                                               0x00000004
#define PDMA_DCSR1_DCSR1_ENDINTR_SET(n)                                             (((uint32_t)(n) << 2  ) & 0x00000004)
#define PDMA_DCSR1_DCSR1_ENDINTR_CLR                                                0xFFFFFFFB

#define PDMA_DCSR1_DCSR1_BUSERRINTR_SHIFT                                           0
#define PDMA_DCSR1_DCSR1_BUSERRINTR_MASK                                            0x00000001
#define PDMA_DCSR1_DCSR1_BUSERRINTR_SET(n)                                          (((uint32_t)(n) << 0  ) & 0x00000001)
#define PDMA_DCSR1_DCSR1_BUSERRINTR_CLR                                             0xFFFFFFFE

#define PDMA_DCSR2_DCSR2_RUN_SHIFT                                                  31
#define PDMA_DCSR2_DCSR2_RUN_MASK                                                   0x80000000
#define PDMA_DCSR2_DCSR2_RUN_SET(n)                                                 (((uint32_t)(n) << 31 ) & 0x80000000)
#define PDMA_DCSR2_DCSR2_RUN_CLR                                                    0x7FFFFFFF

#define PDMA_DCSR2_DCSR2_ENABLE_SHIFT                                               30
#define PDMA_DCSR2_DCSR2_ENABLE_MASK                                                0x40000000
#define PDMA_DCSR2_DCSR2_ENABLE_SET(n)                                              (((uint32_t)(n) << 30 ) & 0x40000000)
#define PDMA_DCSR2_DCSR2_ENABLE_CLR                                                 0xBFFFFFFF

#define PDMA_DCSR2_DCSR2_STOPIRQEN_SHIFT                                            29
#define PDMA_DCSR2_DCSR2_STOPIRQEN_MASK                                             0x20000000
#define PDMA_DCSR2_DCSR2_STOPIRQEN_SET(n)                                           (((uint32_t)(n) << 29 ) & 0x20000000)
#define PDMA_DCSR2_DCSR2_STOPIRQEN_CLR                                              0xDFFFFFFF

#define PDMA_DCSR2_DCSR2_RASIRQEN_SHIFT                                             23
#define PDMA_DCSR2_DCSR2_RASIRQEN_MASK                                              0x00800000
#define PDMA_DCSR2_DCSR2_RASIRQEN_SET(n)                                            (((uint32_t)(n) << 23 ) & 0x00800000)
#define PDMA_DCSR2_DCSR2_RASIRQEN_CLR                                               0xFF7FFFFF

#define PDMA_DCSR2_DCSR2_MASKRUN_SHIFT                                              22
#define PDMA_DCSR2_DCSR2_MASKRUN_MASK                                               0x00400000
#define PDMA_DCSR2_DCSR2_MASKRUN_SET(n)                                             (((uint32_t)(n) << 22 ) & 0x00400000)
#define PDMA_DCSR2_DCSR2_MASKRUN_CLR                                                0xFFBFFFFF

#define PDMA_DCSR2_DCSR2_REQPEND_SHIFT                                              8
#define PDMA_DCSR2_DCSR2_REQPEND_MASK                                               0x00000100
#define PDMA_DCSR2_DCSR2_REQPEND_SET(n)                                             (((uint32_t)(n) << 8  ) & 0x00000100)
#define PDMA_DCSR2_DCSR2_REQPEND_CLR                                                0xFFFFFEFF

#define PDMA_DCSR2_DCSR2_RASINTR_SHIFT                                              4
#define PDMA_DCSR2_DCSR2_RASINTR_MASK                                               0x00000010
#define PDMA_DCSR2_DCSR2_RASINTR_SET(n)                                             (((uint32_t)(n) << 4  ) & 0x00000010)
#define PDMA_DCSR2_DCSR2_RASINTR_CLR                                                0xFFFFFFEF

#define PDMA_DCSR2_DCSR2_STOPINTR_SHIFT                                             3
#define PDMA_DCSR2_DCSR2_STOPINTR_MASK                                              0x00000008
#define PDMA_DCSR2_DCSR2_STOPINTR_SET(n)                                            (((uint32_t)(n) << 3  ) & 0x00000008)
#define PDMA_DCSR2_DCSR2_STOPINTR_CLR                                               0xFFFFFFF7

#define PDMA_DCSR2_DCSR2_ENDINTR_SHIFT                                              2
#define PDMA_DCSR2_DCSR2_ENDINTR_MASK                                               0x00000004
#define PDMA_DCSR2_DCSR2_ENDINTR_SET(n)                                             (((uint32_t)(n) << 2  ) & 0x00000004)
#define PDMA_DCSR2_DCSR2_ENDINTR_CLR                                                0xFFFFFFFB

#define PDMA_DCSR2_DCSR2_BUSERRINTR_SHIFT                                           0
#define PDMA_DCSR2_DCSR2_BUSERRINTR_MASK                                            0x00000001
#define PDMA_DCSR2_DCSR2_BUSERRINTR_SET(n)                                          (((uint32_t)(n) << 0  ) & 0x00000001)
#define PDMA_DCSR2_DCSR2_BUSERRINTR_CLR                                             0xFFFFFFFE

#define PDMA_DALGN0_DALGN0_DALGN_SHIFT                                              0
#define PDMA_DALGN0_DALGN0_DALGN_MASK                                               0x00000001
#define PDMA_DALGN0_DALGN0_DALGN_SET(n)                                             (((uint32_t)(n) << 0  ) & 0x00000001)
#define PDMA_DALGN0_DALGN0_DALGN_CLR                                                0xFFFFFFFE

#define PDMA_DALGN1_DALGN1_DALGN_SHIFT                                              0
#define PDMA_DALGN1_DALGN1_DALGN_MASK                                               0x00000001
#define PDMA_DALGN1_DALGN1_DALGN_SET(n)                                             (((uint32_t)(n) << 0  ) & 0x00000001)
#define PDMA_DALGN1_DALGN1_DALGN_CLR                                                0xFFFFFFFE

#define PDMA_DALGN2_DALGN2_DALGN_SHIFT                                              0
#define PDMA_DALGN2_DALGN2_DALGN_MASK                                               0x00000001
#define PDMA_DALGN2_DALGN2_DALGN_SET(n)                                             (((uint32_t)(n) << 0  ) & 0x00000001)
#define PDMA_DALGN2_DALGN2_DALGN_CLR                                                0xFFFFFFFE

#define PDMA_DRQSR0_DRQSR0_CLR_SHIFT                                                8
#define PDMA_DRQSR0_DRQSR0_CLR_MASK                                                 0x00000100
#define PDMA_DRQSR0_DRQSR0_CLR_SET(n)                                               (((uint32_t)(n) << 8  ) & 0x00000100)
#define PDMA_DRQSR0_DRQSR0_CLR_CLR                                                  0xFFFFFEFF

#define PDMA_DRQSR0_DRQSR0_REQPEND_SHIFT                                            0
#define PDMA_DRQSR0_DRQSR0_REQPEND_MASK                                             0x0000001F
#define PDMA_DRQSR0_DRQSR0_REQPEND_SET(n)                                           (((uint32_t)(n) << 0  ) & 0x0000001F)
#define PDMA_DRQSR0_DRQSR0_REQPEND_CLR                                              0xFFFFFFE0

#define PDMA_DRQSR1_DRQSR1_CLR_SHIFT                                                8
#define PDMA_DRQSR1_DRQSR1_CLR_MASK                                                 0x00000100
#define PDMA_DRQSR1_DRQSR1_CLR_SET(n)                                               (((uint32_t)(n) << 8  ) & 0x00000100)
#define PDMA_DRQSR1_DRQSR1_CLR_CLR                                                  0xFFFFFEFF

#define PDMA_DRQSR1_DRQSR1_REQPEND_SHIFT                                            0
#define PDMA_DRQSR1_DRQSR1_REQPEND_MASK                                             0x0000001F
#define PDMA_DRQSR1_DRQSR1_REQPEND_SET(n)                                           (((uint32_t)(n) << 0  ) & 0x0000001F)
#define PDMA_DRQSR1_DRQSR1_REQPEND_CLR                                              0xFFFFFFE0

#define PDMA_DRQSR2_DRQSR2_CLR_SHIFT                                                8
#define PDMA_DRQSR2_DRQSR2_CLR_MASK                                                 0x00000100
#define PDMA_DRQSR2_DRQSR2_CLR_SET(n)                                               (((uint32_t)(n) << 8  ) & 0x00000100)
#define PDMA_DRQSR2_DRQSR2_CLR_CLR                                                  0xFFFFFEFF

#define PDMA_DRQSR2_DRQSR2_REQPEND_SHIFT                                            0
#define PDMA_DRQSR2_DRQSR2_REQPEND_MASK                                             0x0000001F
#define PDMA_DRQSR2_DRQSR2_REQPEND_SET(n)                                           (((uint32_t)(n) << 0  ) & 0x0000001F)
#define PDMA_DRQSR2_DRQSR2_REQPEND_CLR                                              0xFFFFFFE0

#define PDMA_DINT_CHLINTR_SHIFT                                                     0
#define PDMA_DINT_CHLINTR_MASK                                                      0x000001FF
#define PDMA_DINT_CHLINTR_SET(n)                                                    (((uint32_t)(n) << 0  ) & 0x000001FF)
#define PDMA_DINT_CHLINTR_CLR                                                       0xFFFFFE00

#define PDMA_DRCMR0_DRCMR0_MAPVLD_SHIFT                                             7
#define PDMA_DRCMR0_DRCMR0_MAPVLD_MASK                                              0x00000080
#define PDMA_DRCMR0_DRCMR0_MAPVLD_SET(n)                                            (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR0_DRCMR0_MAPVLD_CLR                                               0xFFFFFF7F

#define PDMA_DRCMR0_DRCMR0_CHLNUM_SHIFT                                             0
#define PDMA_DRCMR0_DRCMR0_CHLNUM_MASK                                              0x0000000F
#define PDMA_DRCMR0_DRCMR0_CHLNUM_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR0_DRCMR0_CHLNUM_CLR                                               0xFFFFFFF0

#define PDMA_DRCMR1_DRCMR1_MAPVLD_SHIFT                                             7
#define PDMA_DRCMR1_DRCMR1_MAPVLD_MASK                                              0x00000080
#define PDMA_DRCMR1_DRCMR1_MAPVLD_SET(n)                                            (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR1_DRCMR1_MAPVLD_CLR                                               0xFFFFFF7F

#define PDMA_DRCMR1_DRCMR1_CHLNUM_SHIFT                                             0
#define PDMA_DRCMR1_DRCMR1_CHLNUM_MASK                                              0x0000000F
#define PDMA_DRCMR1_DRCMR1_CHLNUM_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR1_DRCMR1_CHLNUM_CLR                                               0xFFFFFFF0

#define PDMA_DRCMR2_DRCMR2_MAPVLD_SHIFT                                             7
#define PDMA_DRCMR2_DRCMR2_MAPVLD_MASK                                              0x00000080
#define PDMA_DRCMR2_DRCMR2_MAPVLD_SET(n)                                            (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR2_DRCMR2_MAPVLD_CLR                                               0xFFFFFF7F

#define PDMA_DRCMR2_DRCMR2_CHLNUM_SHIFT                                             0
#define PDMA_DRCMR2_DRCMR2_CHLNUM_MASK                                              0x0000000F
#define PDMA_DRCMR2_DRCMR2_CHLNUM_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR2_DRCMR2_CHLNUM_CLR                                               0xFFFFFFF0

#define PDMA_DRCMR3_DRCMR3_MAPVLD_SHIFT                                             7
#define PDMA_DRCMR3_DRCMR3_MAPVLD_MASK                                              0x00000080
#define PDMA_DRCMR3_DRCMR3_MAPVLD_SET(n)                                            (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR3_DRCMR3_MAPVLD_CLR                                               0xFFFFFF7F

#define PDMA_DRCMR3_DRCMR3_CHLNUM_SHIFT                                             0
#define PDMA_DRCMR3_DRCMR3_CHLNUM_MASK                                              0x0000000F
#define PDMA_DRCMR3_DRCMR3_CHLNUM_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR3_DRCMR3_CHLNUM_CLR                                               0xFFFFFFF0

#define PDMA_DRCMR4_DRCMR4_MAPVLD_SHIFT                                             7
#define PDMA_DRCMR4_DRCMR4_MAPVLD_MASK                                              0x00000080
#define PDMA_DRCMR4_DRCMR4_MAPVLD_SET(n)                                            (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR4_DRCMR4_MAPVLD_CLR                                               0xFFFFFF7F

#define PDMA_DRCMR4_DRCMR4_CHLNUM_SHIFT                                             0
#define PDMA_DRCMR4_DRCMR4_CHLNUM_MASK                                              0x0000000F
#define PDMA_DRCMR4_DRCMR4_CHLNUM_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR4_DRCMR4_CHLNUM_CLR                                               0xFFFFFFF0

#define PDMA_DRCMR5_DRCMR5_MAPVLD_SHIFT                                             7
#define PDMA_DRCMR5_DRCMR5_MAPVLD_MASK                                              0x00000080
#define PDMA_DRCMR5_DRCMR5_MAPVLD_SET(n)                                            (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR5_DRCMR5_MAPVLD_CLR                                               0xFFFFFF7F

#define PDMA_DRCMR5_DRCMR5_CHLNUM_SHIFT                                             0
#define PDMA_DRCMR5_DRCMR5_CHLNUM_MASK                                              0x0000000F
#define PDMA_DRCMR5_DRCMR5_CHLNUM_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR5_DRCMR5_CHLNUM_CLR                                               0xFFFFFFF0

#define PDMA_DRCMR6_DRCMR6_MAPVLD_SHIFT                                             7
#define PDMA_DRCMR6_DRCMR6_MAPVLD_MASK                                              0x00000080
#define PDMA_DRCMR6_DRCMR6_MAPVLD_SET(n)                                            (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR6_DRCMR6_MAPVLD_CLR                                               0xFFFFFF7F

#define PDMA_DRCMR6_DRCMR6_CHLNUM_SHIFT                                             0
#define PDMA_DRCMR6_DRCMR6_CHLNUM_MASK                                              0x0000000F
#define PDMA_DRCMR6_DRCMR6_CHLNUM_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR6_DRCMR6_CHLNUM_CLR                                               0xFFFFFFF0

#define PDMA_DRCMR7_DRCMR7_MAPVLD_SHIFT                                             7
#define PDMA_DRCMR7_DRCMR7_MAPVLD_MASK                                              0x00000080
#define PDMA_DRCMR7_DRCMR7_MAPVLD_SET(n)                                            (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR7_DRCMR7_MAPVLD_CLR                                               0xFFFFFF7F

#define PDMA_DRCMR7_DRCMR7_CHLNUM_SHIFT                                             0
#define PDMA_DRCMR7_DRCMR7_CHLNUM_MASK                                              0x0000000F
#define PDMA_DRCMR7_DRCMR7_CHLNUM_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR7_DRCMR7_CHLNUM_CLR                                               0xFFFFFFF0

#define PDMA_DRCMR8_DRCMR8_MAPVLD_SHIFT                                             7
#define PDMA_DRCMR8_DRCMR8_MAPVLD_MASK                                              0x00000080
#define PDMA_DRCMR8_DRCMR8_MAPVLD_SET(n)                                            (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR8_DRCMR8_MAPVLD_CLR                                               0xFFFFFF7F

#define PDMA_DRCMR8_DRCMR8_CHLNUM_SHIFT                                             0
#define PDMA_DRCMR8_DRCMR8_CHLNUM_MASK                                              0x0000000F
#define PDMA_DRCMR8_DRCMR8_CHLNUM_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR8_DRCMR8_CHLNUM_CLR                                               0xFFFFFFF0

#define PDMA_DRCMR9_DRCMR9_MAPVLD_SHIFT                                             7
#define PDMA_DRCMR9_DRCMR9_MAPVLD_MASK                                              0x00000080
#define PDMA_DRCMR9_DRCMR9_MAPVLD_SET(n)                                            (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR9_DRCMR9_MAPVLD_CLR                                               0xFFFFFF7F

#define PDMA_DRCMR9_DRCMR9_CHLNUM_SHIFT                                             0
#define PDMA_DRCMR9_DRCMR9_CHLNUM_MASK                                              0x0000000F
#define PDMA_DRCMR9_DRCMR9_CHLNUM_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR9_DRCMR9_CHLNUM_CLR                                               0xFFFFFFF0

#define PDMA_DRCMR10_DRCMR10_MAPVLD_SHIFT                                           7
#define PDMA_DRCMR10_DRCMR10_MAPVLD_MASK                                            0x00000080
#define PDMA_DRCMR10_DRCMR10_MAPVLD_SET(n)                                          (((uint32_t)(n) << 7  ) & 0x00000080)
#define PDMA_DRCMR10_DRCMR10_MAPVLD_CLR                                             0xFFFFFF7F

#define PDMA_DRCMR10_DRCMR10_CHLNUM_SHIFT                                           0
#define PDMA_DRCMR10_DRCMR10_CHLNUM_MASK                                            0x0000000F
#define PDMA_DRCMR10_DRCMR10_CHLNUM_SET(n)                                          (((uint32_t)(n) << 0  ) & 0x0000000F)
#define PDMA_DRCMR10_DRCMR10_CHLNUM_CLR                                             0xFFFFFFF0

#define PDMA_DESC0_DSADR_DESC0_SRCADDR_SHIFT                                        0
#define PDMA_DESC0_DSADR_DESC0_SRCADDR_MASK                                         0xFFFFFFFF
#define PDMA_DESC0_DSADR_DESC0_SRCADDR_SET(n)                                       (((uint32_t)(n) << 0  ) & 0xFFFFFFFF)
#define PDMA_DESC0_DSADR_DESC0_SRCADDR_CLR                                          0x00000000

#define PDMA_DESC0_DTADR_DESC0_TRGADDR_SHIFT                                        0
#define PDMA_DESC0_DTADR_DESC0_TRGADDR_MASK                                         0xFFFFFFFF
#define PDMA_DESC0_DTADR_DESC0_TRGADDR_SET(n)                                       (((uint32_t)(n) << 0  ) & 0xFFFFFFFF)
#define PDMA_DESC0_DTADR_DESC0_TRGADDR_CLR                                          0x00000000

#define PDMA_DESC0_DCMD_DESC0_INCSRCADDR_SHIFT                                      31
#define PDMA_DESC0_DCMD_DESC0_INCSRCADDR_MASK                                       0x80000000
#define PDMA_DESC0_DCMD_DESC0_INCSRCADDR_SET(n)                                     (((uint32_t)(n) << 31 ) & 0x80000000)
#define PDMA_DESC0_DCMD_DESC0_INCSRCADDR_CLR                                        0x7FFFFFFF

#define PDMA_DESC0_DCMD_DESC0_INCTRGADDR_SHIFT                                      30
#define PDMA_DESC0_DCMD_DESC0_INCTRGADDR_MASK                                       0x40000000
#define PDMA_DESC0_DCMD_DESC0_INCTRGADDR_SET(n)                                     (((uint32_t)(n) << 30 ) & 0x40000000)
#define PDMA_DESC0_DCMD_DESC0_INCTRGADDR_CLR                                        0xBFFFFFFF

#define PDMA_DESC0_DCMD_DESC0_FLOWSRC_SHIFT                                         29
#define PDMA_DESC0_DCMD_DESC0_FLOWSRC_MASK                                          0x20000000
#define PDMA_DESC0_DCMD_DESC0_FLOWSRC_SET(n)                                        (((uint32_t)(n) << 29 ) & 0x20000000)
#define PDMA_DESC0_DCMD_DESC0_FLOWSRC_CLR                                           0xDFFFFFFF

#define PDMA_DESC0_DCMD_DESC0_FLOWTRG_SHIFT                                         28
#define PDMA_DESC0_DCMD_DESC0_FLOWTRG_MASK                                          0x10000000
#define PDMA_DESC0_DCMD_DESC0_FLOWTRG_SET(n)                                        (((uint32_t)(n) << 28 ) & 0x10000000)
#define PDMA_DESC0_DCMD_DESC0_FLOWTRG_CLR                                           0xEFFFFFFF

#define PDMA_DESC0_DCMD_DESC0_ENDIRQEN_SHIFT                                        21
#define PDMA_DESC0_DCMD_DESC0_ENDIRQEN_MASK                                         0x00200000
#define PDMA_DESC0_DCMD_DESC0_ENDIRQEN_SET(n)                                       (((uint32_t)(n) << 21 ) & 0x00200000)
#define PDMA_DESC0_DCMD_DESC0_ENDIRQEN_CLR                                          0xFFDFFFFF

#define PDMA_DESC0_DCMD_DESC0_SIZE_SHIFT                                            16
#define PDMA_DESC0_DCMD_DESC0_SIZE_MASK                                             0x00070000
#define PDMA_DESC0_DCMD_DESC0_SIZE_SET(n)                                           (((uint32_t)(n) << 16 ) & 0x00070000)
#define PDMA_DESC0_DCMD_DESC0_SIZE_CLR                                              0xFFF8FFFF

#define PDMA_DESC0_DCMD_DESC0_WIDTH_SHIFT                                           14
#define PDMA_DESC0_DCMD_DESC0_WIDTH_MASK                                            0x0000C000
#define PDMA_DESC0_DCMD_DESC0_WIDTH_SET(n)                                          (((uint32_t)(n) << 14 ) & 0x0000C000)
#define PDMA_DESC0_DCMD_DESC0_WIDTH_CLR                                             0xFFFF3FFF

#define PDMA_DESC0_DCMD_DESC0_LEN_SHIFT                                             0
#define PDMA_DESC0_DCMD_DESC0_LEN_MASK                                              0x00001FFF
#define PDMA_DESC0_DCMD_DESC0_LEN_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x00001FFF)
#define PDMA_DESC0_DCMD_DESC0_LEN_CLR                                               0xFFFFE000

#define PDMA_DESC1_DSADR_DESC1_SRCADDR_SHIFT                                        0
#define PDMA_DESC1_DSADR_DESC1_SRCADDR_MASK                                         0xFFFFFFFF
#define PDMA_DESC1_DSADR_DESC1_SRCADDR_SET(n)                                       (((uint32_t)(n) << 0  ) & 0xFFFFFFFF)
#define PDMA_DESC1_DSADR_DESC1_SRCADDR_CLR                                          0x00000000

#define PDMA_DESC1_DTADR_DESC1_TRGADDR_SHIFT                                        0
#define PDMA_DESC1_DTADR_DESC1_TRGADDR_MASK                                         0xFFFFFFFF
#define PDMA_DESC1_DTADR_DESC1_TRGADDR_SET(n)                                       (((uint32_t)(n) << 0  ) & 0xFFFFFFFF)
#define PDMA_DESC1_DTADR_DESC1_TRGADDR_CLR                                          0x00000000

#define PDMA_DESC1_DCMD_DESC1_INCSRCADDR_SHIFT                                      31
#define PDMA_DESC1_DCMD_DESC1_INCSRCADDR_MASK                                       0x80000000
#define PDMA_DESC1_DCMD_DESC1_INCSRCADDR_SET(n)                                     (((uint32_t)(n) << 31 ) & 0x80000000)
#define PDMA_DESC1_DCMD_DESC1_INCSRCADDR_CLR                                        0x7FFFFFFF

#define PDMA_DESC1_DCMD_DESC1_INCTRGADDR_SHIFT                                      30
#define PDMA_DESC1_DCMD_DESC1_INCTRGADDR_MASK                                       0x40000000
#define PDMA_DESC1_DCMD_DESC1_INCTRGADDR_SET(n)                                     (((uint32_t)(n) << 30 ) & 0x40000000)
#define PDMA_DESC1_DCMD_DESC1_INCTRGADDR_CLR                                        0xBFFFFFFF

#define PDMA_DESC1_DCMD_DESC1_FLOWSRC_SHIFT                                         29
#define PDMA_DESC1_DCMD_DESC1_FLOWSRC_MASK                                          0x20000000
#define PDMA_DESC1_DCMD_DESC1_FLOWSRC_SET(n)                                        (((uint32_t)(n) << 29 ) & 0x20000000)
#define PDMA_DESC1_DCMD_DESC1_FLOWSRC_CLR                                           0xDFFFFFFF

#define PDMA_DESC1_DCMD_DESC1_FLOWTRG_SHIFT                                         28
#define PDMA_DESC1_DCMD_DESC1_FLOWTRG_MASK                                          0x10000000
#define PDMA_DESC1_DCMD_DESC1_FLOWTRG_SET(n)                                        (((uint32_t)(n) << 28 ) & 0x10000000)
#define PDMA_DESC1_DCMD_DESC1_FLOWTRG_CLR                                           0xEFFFFFFF

#define PDMA_DESC1_DCMD_DESC1_ENDIRQEN_SHIFT                                        21
#define PDMA_DESC1_DCMD_DESC1_ENDIRQEN_MASK                                         0x00200000
#define PDMA_DESC1_DCMD_DESC1_ENDIRQEN_SET(n)                                       (((uint32_t)(n) << 21 ) & 0x00200000)
#define PDMA_DESC1_DCMD_DESC1_ENDIRQEN_CLR                                          0xFFDFFFFF

#define PDMA_DESC1_DCMD_DESC1_SIZE_SHIFT                                            16
#define PDMA_DESC1_DCMD_DESC1_SIZE_MASK                                             0x00070000
#define PDMA_DESC1_DCMD_DESC1_SIZE_SET(n)                                           (((uint32_t)(n) << 16 ) & 0x00070000)
#define PDMA_DESC1_DCMD_DESC1_SIZE_CLR                                              0xFFF8FFFF

#define PDMA_DESC1_DCMD_DESC1_WIDTH_SHIFT                                           14
#define PDMA_DESC1_DCMD_DESC1_WIDTH_MASK                                            0x0000C000
#define PDMA_DESC1_DCMD_DESC1_WIDTH_SET(n)                                          (((uint32_t)(n) << 14 ) & 0x0000C000)
#define PDMA_DESC1_DCMD_DESC1_WIDTH_CLR                                             0xFFFF3FFF

#define PDMA_DESC1_DCMD_DESC1_LEN_SHIFT                                             0
#define PDMA_DESC1_DCMD_DESC1_LEN_MASK                                              0x00001FFF
#define PDMA_DESC1_DCMD_DESC1_LEN_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x00001FFF)
#define PDMA_DESC1_DCMD_DESC1_LEN_CLR                                               0xFFFFE000

#define PDMA_DESC2_DSADR_DESC2_SRCADDR_SHIFT                                        0
#define PDMA_DESC2_DSADR_DESC2_SRCADDR_MASK                                         0xFFFFFFFF
#define PDMA_DESC2_DSADR_DESC2_SRCADDR_SET(n)                                       (((uint32_t)(n) << 0  ) & 0xFFFFFFFF)
#define PDMA_DESC2_DSADR_DESC2_SRCADDR_CLR                                          0x00000000

#define PDMA_DESC2_DTADR_DESC2_TRGADDR_SHIFT                                        0
#define PDMA_DESC2_DTADR_DESC2_TRGADDR_MASK                                         0xFFFFFFFF
#define PDMA_DESC2_DTADR_DESC2_TRGADDR_SET(n)                                       (((uint32_t)(n) << 0  ) & 0xFFFFFFFF)
#define PDMA_DESC2_DTADR_DESC2_TRGADDR_CLR                                          0x00000000

#define PDMA_DESC2_DCMD_DESC2_INCSRCADDR_SHIFT                                      31
#define PDMA_DESC2_DCMD_DESC2_INCSRCADDR_MASK                                       0x80000000
#define PDMA_DESC2_DCMD_DESC2_INCSRCADDR_SET(n)                                     (((uint32_t)(n) << 31 ) & 0x80000000)
#define PDMA_DESC2_DCMD_DESC2_INCSRCADDR_CLR                                        0x7FFFFFFF

#define PDMA_DESC2_DCMD_DESC2_INCTRGADDR_SHIFT                                      30
#define PDMA_DESC2_DCMD_DESC2_INCTRGADDR_MASK                                       0x40000000
#define PDMA_DESC2_DCMD_DESC2_INCTRGADDR_SET(n)                                     (((uint32_t)(n) << 30 ) & 0x40000000)
#define PDMA_DESC2_DCMD_DESC2_INCTRGADDR_CLR                                        0xBFFFFFFF

#define PDMA_DESC2_DCMD_DESC2_FLOWSRC_SHIFT                                         29
#define PDMA_DESC2_DCMD_DESC2_FLOWSRC_MASK                                          0x20000000
#define PDMA_DESC2_DCMD_DESC2_FLOWSRC_SET(n)                                        (((uint32_t)(n) << 29 ) & 0x20000000)
#define PDMA_DESC2_DCMD_DESC2_FLOWSRC_CLR                                           0xDFFFFFFF

#define PDMA_DESC2_DCMD_DESC2_FLOWTRG_SHIFT                                         28
#define PDMA_DESC2_DCMD_DESC2_FLOWTRG_MASK                                          0x10000000
#define PDMA_DESC2_DCMD_DESC2_FLOWTRG_SET(n)                                        (((uint32_t)(n) << 28 ) & 0x10000000)
#define PDMA_DESC2_DCMD_DESC2_FLOWTRG_CLR                                           0xEFFFFFFF

#define PDMA_DESC2_DCMD_DESC2_ENDIRQEN_SHIFT                                        21
#define PDMA_DESC2_DCMD_DESC2_ENDIRQEN_MASK                                         0x00200000
#define PDMA_DESC2_DCMD_DESC2_ENDIRQEN_SET(n)                                       (((uint32_t)(n) << 21 ) & 0x00200000)
#define PDMA_DESC2_DCMD_DESC2_ENDIRQEN_CLR                                          0xFFDFFFFF

#define PDMA_DESC2_DCMD_DESC2_SIZE_SHIFT                                            16
#define PDMA_DESC2_DCMD_DESC2_SIZE_MASK                                             0x00070000
#define PDMA_DESC2_DCMD_DESC2_SIZE_SET(n)                                           (((uint32_t)(n) << 16 ) & 0x00070000)
#define PDMA_DESC2_DCMD_DESC2_SIZE_CLR                                              0xFFF8FFFF

#define PDMA_DESC2_DCMD_DESC2_WIDTH_SHIFT                                           14
#define PDMA_DESC2_DCMD_DESC2_WIDTH_MASK                                            0x0000C000
#define PDMA_DESC2_DCMD_DESC2_WIDTH_SET(n)                                          (((uint32_t)(n) << 14 ) & 0x0000C000)
#define PDMA_DESC2_DCMD_DESC2_WIDTH_CLR                                             0xFFFF3FFF

#define PDMA_DESC2_DCMD_DESC2_LEN_SHIFT                                             0
#define PDMA_DESC2_DCMD_DESC2_LEN_MASK                                              0x00001FFF
#define PDMA_DESC2_DCMD_DESC2_LEN_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x00001FFF)
#define PDMA_DESC2_DCMD_DESC2_LEN_CLR                                               0xFFFFE000

#define PDMA_MAX_CHANNEL                                                            3
#define PDMA_MAX_REQUEST                                                            11
// Register Structure Definition


typedef struct
{
    __IO uint32_t DCSR_BUSERRINTR                         : 1  ; // 0  : 0 
    __IO uint32_t DCSR_RESERVED3                          : 1  ; // 1  : 1 
    __IO uint32_t DCSR_ENDINTR                            : 1  ; // 2  : 2 
    __IO uint32_t DCSR_STOPINTR                           : 1  ; // 3  : 3 
    __IO uint32_t DCSR_RASINTR                            : 1  ; // 4  : 4 
    __IO uint32_t DCSR_RESERVED2                          : 3  ; // 7  : 5 
    __IO uint32_t DCSR_REQPEND                            : 1  ; // 8  : 8 
    __IO uint32_t DCSR_RESERVED1                          : 13 ; // 21 : 9 
    __IO uint32_t DCSR_MASKRUN                            : 1  ; // 22 : 22 
    __IO uint32_t DCSR_RASIRQEN                           : 1  ; // 23 : 23 
    __IO uint32_t DCSR_RESERVED0                          : 5  ; // 28 : 24 
    __IO uint32_t DCSR_STOPIRQEN                          : 1  ; // 29 : 29 
    __IO uint32_t DCSR_ENABLE                             : 1  ; // 30 : 30 
    __IO uint32_t DCSR_RUN                                : 1  ; // 31 : 31 
} PDMA_DCSR_FIELD_T;

typedef struct
{
    __IO uint32_t DALGN_DALGN                             : 1  ; // 0  : 0 
    __IO uint32_t DALGN_RESERVED0                         : 31 ; // 31 : 1 
} PDMA_DALGN_FIELD_T;

typedef struct
{
    __IO uint32_t DRQSR_REQPEND                           : 5  ; // 4  : 0 
    __IO uint32_t DRQSR_RESERVED1                         : 3  ; // 7  : 5 
    __IO uint32_t DRQSR_CLR                               : 1  ; // 8  : 8 
    __IO uint32_t DRQSR_RESERVED0                         : 23 ; // 31 : 9 
} PDMA_DRQSR_FIELD_T;

typedef struct
{
    __IO uint32_t CHLINTR                                  : 9  ; // 8  : 0 
    __IO uint32_t RESERVED0                                : 23 ; // 31 : 9 
} PDMA_DINT_FIELD_T;

typedef struct
{
    __IO uint32_t DRCMR_CHLNUM                            : 4  ; // 3  : 0 
    __IO uint32_t DRCMR_RESERVED1                         : 3  ; // 6  : 4 
    __IO uint32_t DRCMR_MAPVLD                            : 1  ; // 7  : 7 
    __IO uint32_t DRCMR_RESERVED0                         : 24 ; // 31 : 8 
} PDMA_DRCMR_FIELD_T;

typedef struct
{
    __IO uint32_t DESC_LEN                                : 13 ; // 12 : 0 
    __IO uint32_t DESC_RESERVED2                          : 1  ; // 13 : 13 
    __IO uint32_t DESC_WIDTH                              : 2  ; // 15 : 14 
    __IO uint32_t DESC_BURST                              : 3  ; // 18 : 16 
    __IO uint32_t DESC_RESERVED1                          : 2  ; // 20 : 19 
    __IO uint32_t DESC_ENDIRQEN                           : 1  ; // 21 : 21 
    __IO uint32_t DESC_RESERVED0                          : 6  ; // 27 : 22 
    __IO uint32_t DESC_FLOWTRG                            : 1  ; // 28 : 28 
    __IO uint32_t DESC_FLOWSRC                            : 1  ; // 29 : 29 
    __IO uint32_t DESC_INCTRGADDR                         : 1  ; // 30 : 30 
    __IO uint32_t DESC_INCSRCADDR                         : 1  ; // 31 : 31 
} PDMA_DESC_DCMD_FIELD_T;

typedef struct
{
    uint32_t      DDADR;  // DMA Descriptor Address
    uint32_t      DSADR;  // DMA Source Address
    uint32_t      DTADR;  // DMA Target Address
    union
    {
        uint32_t        DCMD;       // DMA Command Register
        PDMA_DESC_DCMD_FIELD_T       DCMD_F;     
    };
} PDMA_DESC_FIELD_T;

// Register Map Structure Definition
typedef struct
{
    union 
    { 
        __IO  uint32_t DCSR[PDMA_MAX_CHANNEL]; // 0x0000
        PDMA_DCSR_FIELD_T DCSR_F[PDMA_MAX_CHANNEL];
    };

    uint32_t RESERVED0[13];

    union 
    { 
        __IO  uint32_t DALGN[PDMA_MAX_CHANNEL]; // 0x0040
        PDMA_DALGN_FIELD_T DALGN_F[PDMA_MAX_CHANNEL];
    };

    uint32_t RESERVED1[13]            ;

    union 
    { 
        __IO  uint32_t DRQSR[PDMA_MAX_CHANNEL]; // 0x0080
        PDMA_DRQSR_FIELD_T DRQSR_F[PDMA_MAX_CHANNEL];
    };

    union 
    { 
        __IO  uint32_t DINT; // 0x008C
        PDMA_DINT_FIELD_T DINT_F;
    };

    uint32_t RESERVED2[28];

    union 
    { 
        __IO  uint32_t DRCMR[PDMA_MAX_REQUEST]; // 0x0100
        PDMA_DRCMR_FIELD_T DRCMR_F[PDMA_MAX_REQUEST];
    };

    uint32_t RESERVED3[53];

    PDMA_DESC_FIELD_T DESC_F[PDMA_MAX_CHANNEL];

} PDMA_REG_TypeDef;

#endif
