//----------------------------------------------------------------------
//         COPYRIGHT (C) 2022 TINYCHIP SEMICONDUCTOR                    
    //              CONFIDENTIAL & ALL RIGHTS RESERVED                      
//----------------------------------------------------------------------
// File name      : aanareg_reg_def.h                                   
// Author         : mfpan                                               
// E-Mail         : mfpan@tinychip.com.cn                               
//----------------------------------------------------------------------
// Description    :                                                     
// Register Header File of AANAREG                                   
//----------------------------------------------------------------------
// Reversion History:                                                   
// 2022-10-21 17:24:9 -- automatically generated by reg_gen.pl Revision 1.11          
//----------------------------------------------------------------------

#ifndef   AANAREG_DEF_H__
#define   AANAREG_DEF_H__

// Register Offset Macro Definition
#define AANAREG_CHIP_ID_OFFSET                                  0x0000
#define AANAREG_OSCRC_32K_TOP_OFFSET                            0x0004
#define AANAREG_OSCRC_16M_TOP_OFFSET                            0x0008
#define AANAREG_LDO15_TOP_OFFSET                                0x000C
#define AANAREG_LDO3VS_TOP_OFFSET                               0x0010
#define AANAREG_VBIAS_IBIAS_TOP_OFFSET                          0x0014
#define AANAREG_LVD_TOP_OFFSET                                  0x0018
#define AANAREG_LVD_CFG_OFFSET                                  0x001C
#define AANAREG_PORB_AON_BLIAS_OFFSET                           0x0020
#define AANAREG_TEST_MUX_TOP1_OFFSET                            0x0024
#define AANAREG_TEST_MUX_TOP2_OFFSET                            0x0028
#define AANAREG_CHIP_DEFEATURE_OFFSET                           0x002C
#define AANAREG_TRIM_CONSTGM_VALUE_OFFSET                       0x0100
#define AANAREG_TRIM_OSCRC32K_VALUE_OFFSET                      0x0104
#define AANAREG_TRIM_OSCRC16M_VALUE_OFFSET                      0x0108
#define AANAREG_TRIM_VBIAS_IBIAS_VALUE_OFFSET                   0x010C
#define AANAREG_TRIM_BGR_VALUE_OFFSET                           0x0110
#define AANAREG_ANALOG_TRIM_STATUS_OFFSET                       0x0114

// Register Address Macro Definition
#define AANAREG_CHIP_ID_ADDR                                    ( AANAREG_BASE_ADDR + AANAREG_CHIP_ID_OFFSET)
#define AANAREG_OSCRC_32K_TOP_ADDR                              ( AANAREG_BASE_ADDR + AANAREG_OSCRC_32K_TOP_OFFSET)
#define AANAREG_OSCRC_16M_TOP_ADDR                              ( AANAREG_BASE_ADDR + AANAREG_OSCRC_16M_TOP_OFFSET)
#define AANAREG_LDO15_TOP_ADDR                                  ( AANAREG_BASE_ADDR + AANAREG_LDO15_TOP_OFFSET)
#define AANAREG_LDO3VS_TOP_ADDR                                 ( AANAREG_BASE_ADDR + AANAREG_LDO3VS_TOP_OFFSET)
#define AANAREG_VBIAS_IBIAS_TOP_ADDR                            ( AANAREG_BASE_ADDR + AANAREG_VBIAS_IBIAS_TOP_OFFSET)
#define AANAREG_LVD_TOP_ADDR                                    ( AANAREG_BASE_ADDR + AANAREG_LVD_TOP_OFFSET)
#define AANAREG_LVD_CFG_ADDR                                    ( AANAREG_BASE_ADDR + AANAREG_LVD_CFG_OFFSET)
#define AANAREG_PORB_AON_BLIAS_ADDR                             ( AANAREG_BASE_ADDR + AANAREG_PORB_AON_BLIAS_OFFSET)
#define AANAREG_TEST_MUX_TOP1_ADDR                              ( AANAREG_BASE_ADDR + AANAREG_TEST_MUX_TOP1_OFFSET)
#define AANAREG_TEST_MUX_TOP2_ADDR                              ( AANAREG_BASE_ADDR + AANAREG_TEST_MUX_TOP2_OFFSET)
#define AANAREG_CHIP_DEFEATURE_ADDR                             ( AANAREG_BASE_ADDR + AANAREG_CHIP_DEFEATURE_OFFSET)
#define AANAREG_TRIM_CONSTGM_VALUE_ADDR                         ( AANAREG_BASE_ADDR + AANAREG_TRIM_CONSTGM_VALUE_OFFSET)
#define AANAREG_TRIM_OSCRC32K_VALUE_ADDR                        ( AANAREG_BASE_ADDR + AANAREG_TRIM_OSCRC32K_VALUE_OFFSET)
#define AANAREG_TRIM_OSCRC16M_VALUE_ADDR                        ( AANAREG_BASE_ADDR + AANAREG_TRIM_OSCRC16M_VALUE_OFFSET)
#define AANAREG_TRIM_VBIAS_IBIAS_VALUE_ADDR                     ( AANAREG_BASE_ADDR + AANAREG_TRIM_VBIAS_IBIAS_VALUE_OFFSET)
#define AANAREG_TRIM_BGR_VALUE_ADDR                             ( AANAREG_BASE_ADDR + AANAREG_TRIM_BGR_VALUE_OFFSET)
#define AANAREG_ANALOG_TRIM_STATUS_ADDR                         ( AANAREG_BASE_ADDR + AANAREG_ANALOG_TRIM_STATUS_OFFSET)

// Register Field Macro Definition
#define AANAREG_CHIP_ID_A2D_CHIP_ID_1P5V_SHIFT                                               16
#define AANAREG_CHIP_ID_A2D_CHIP_ID_1P5V_MASK                                                0x01FF0000
#define AANAREG_CHIP_ID_A2D_CHIP_ID_1P5V_SET(n)                                              (((uint32_t)(n) << 16 ) & 0x01FF0000)
#define AANAREG_CHIP_ID_A2D_CHIP_ID_1P5V_CLR                                                 0xFE00FFFF

#define AANAREG_CHIP_ID_REAL_CHIP_ID_SHIFT                                                   0
#define AANAREG_CHIP_ID_REAL_CHIP_ID_MASK                                                    0x0000FFFF
#define AANAREG_CHIP_ID_REAL_CHIP_ID_SET(n)                                                  (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define AANAREG_CHIP_ID_REAL_CHIP_ID_CLR                                                     0xFFFF0000

#define AANAREG_OSCRC_32K_TOP_CTRL_DEGLITCH_OSCRC32K_SHIFT                                   3
#define AANAREG_OSCRC_32K_TOP_CTRL_DEGLITCH_OSCRC32K_MASK                                    0x000000F8
#define AANAREG_OSCRC_32K_TOP_CTRL_DEGLITCH_OSCRC32K_SET(n)                                  (((uint32_t)(n) << 3  ) & 0x000000F8)
#define AANAREG_OSCRC_32K_TOP_CTRL_DEGLITCH_OSCRC32K_CLR                                     0xFFFFFF07

#define AANAREG_OSCRC_32K_TOP_CTRL_OSCRC32K_TEST_EN_SHIFT                                    2
#define AANAREG_OSCRC_32K_TOP_CTRL_OSCRC32K_TEST_EN_MASK                                     0x00000004
#define AANAREG_OSCRC_32K_TOP_CTRL_OSCRC32K_TEST_EN_SET(n)                                   (((uint32_t)(n) << 2  ) & 0x00000004)
#define AANAREG_OSCRC_32K_TOP_CTRL_OSCRC32K_TEST_EN_CLR                                      0xFFFFFFFB

#define AANAREG_OSCRC_32K_TOP_CTRL_OSCRC32K_FSEL_SHIFT                                       1
#define AANAREG_OSCRC_32K_TOP_CTRL_OSCRC32K_FSEL_MASK                                        0x00000002
#define AANAREG_OSCRC_32K_TOP_CTRL_OSCRC32K_FSEL_SET(n)                                      (((uint32_t)(n) << 1  ) & 0x00000002)
#define AANAREG_OSCRC_32K_TOP_CTRL_OSCRC32K_FSEL_CLR                                         0xFFFFFFFD

#define AANAREG_OSCRC_16M_TOP_CTRL_FD_EN_1_SHIFT                                             9
#define AANAREG_OSCRC_16M_TOP_CTRL_FD_EN_1_MASK                                              0x00000200
#define AANAREG_OSCRC_16M_TOP_CTRL_FD_EN_1_SET(n)                                            (((uint32_t)(n) << 9  ) & 0x00000200)
#define AANAREG_OSCRC_16M_TOP_CTRL_FD_EN_1_CLR                                               0xFFFFFDFF

#define AANAREG_OSCRC_16M_TOP_CTRL_FD_EN_0_ENABLE_SHIFT                                      8
#define AANAREG_OSCRC_16M_TOP_CTRL_FD_EN_0_ENABLE_MASK                                       0x00000100
#define AANAREG_OSCRC_16M_TOP_CTRL_FD_EN_0_ENABLE_SET(n)                                     (((uint32_t)(n) << 8  ) & 0x00000100)
#define AANAREG_OSCRC_16M_TOP_CTRL_FD_EN_0_ENABLE_CLR                                        0xFFFFFEFF

#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_CLKREADY_SHIFT                                   7
#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_CLKREADY_MASK                                    0x00000080
#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_CLKREADY_SET(n)                                  (((uint32_t)(n) << 7  ) & 0x00000080)
#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_CLKREADY_CLR                                     0xFFFFFF7F

#define AANAREG_OSCRC_16M_TOP_CTRL_DEGLITCH_OSCRC16M_SHIFT                                   2
#define AANAREG_OSCRC_16M_TOP_CTRL_DEGLITCH_OSCRC16M_MASK                                    0x0000007C
#define AANAREG_OSCRC_16M_TOP_CTRL_DEGLITCH_OSCRC16M_SET(n)                                  (((uint32_t)(n) << 2  ) & 0x0000007C)
#define AANAREG_OSCRC_16M_TOP_CTRL_DEGLITCH_OSCRC16M_CLR                                     0xFFFFFF83

#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_1_SHIFT                                          1
#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_1_MASK                                           0x00000002
#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_1_SET(n)                                         (((uint32_t)(n) << 1  ) & 0x00000002)
#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_1_CLR                                            0xFFFFFFFD

#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_0_ENABLE_SHIFT                                   0
#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_0_ENABLE_MASK                                    0x00000001
#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_0_ENABLE_SET(n)                                  (((uint32_t)(n) << 0  ) & 0x00000001)
#define AANAREG_OSCRC_16M_TOP_CTRL_OSCRC16M_0_ENABLE_CLR                                     0xFFFFFFFE

#define AANAREG_LDO15_TOP_CTRL_LDO15_15_4_SHIFT                                              4
#define AANAREG_LDO15_TOP_CTRL_LDO15_15_4_MASK                                               0x0000FFF0
#define AANAREG_LDO15_TOP_CTRL_LDO15_15_4_SET(n)                                             (((uint32_t)(n) << 4  ) & 0x0000FFF0)
#define AANAREG_LDO15_TOP_CTRL_LDO15_15_4_CLR                                                0xFFFF000F

#define AANAREG_LDO15_TOP_CTRL_LDO15_3_OUT_ENABLE_SHIFT                                      3
#define AANAREG_LDO15_TOP_CTRL_LDO15_3_OUT_ENABLE_MASK                                       0x00000008
#define AANAREG_LDO15_TOP_CTRL_LDO15_3_OUT_ENABLE_SET(n)                                     (((uint32_t)(n) << 3  ) & 0x00000008)
#define AANAREG_LDO15_TOP_CTRL_LDO15_3_OUT_ENABLE_CLR                                        0xFFFFFFF7

#define AANAREG_LDO15_TOP_CTRL_LDO15_2_1_SHIFT                                               1
#define AANAREG_LDO15_TOP_CTRL_LDO15_2_1_MASK                                                0x00000006
#define AANAREG_LDO15_TOP_CTRL_LDO15_2_1_SET(n)                                              (((uint32_t)(n) << 1  ) & 0x00000006)
#define AANAREG_LDO15_TOP_CTRL_LDO15_2_1_CLR                                                 0xFFFFFFF9

#define AANAREG_LDO15_TOP_CTRL_LDO15_0_ENABLE_SHIFT                                          0
#define AANAREG_LDO15_TOP_CTRL_LDO15_0_ENABLE_MASK                                           0x00000001
#define AANAREG_LDO15_TOP_CTRL_LDO15_0_ENABLE_SET(n)                                         (((uint32_t)(n) << 0  ) & 0x00000001)
#define AANAREG_LDO15_TOP_CTRL_LDO15_0_ENABLE_CLR                                            0xFFFFFFFE

#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_AUTO_MODE_SHIFT                                       8
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_AUTO_MODE_MASK                                        0x00000100
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_AUTO_MODE_SET(n)                                      (((uint32_t)(n) << 8  ) & 0x00000100)
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_AUTO_MODE_CLR                                         0xFFFFFEFF

#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_DIV_SEL_SHIFT                                         5
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_DIV_SEL_MASK                                          0x000000E0
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_DIV_SEL_SET(n)                                        (((uint32_t)(n) << 5  ) & 0x000000E0)
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_DIV_SEL_CLR                                           0xFFFFFF1F

#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_DIV_ENABLE_SHIFT                                      4
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_DIV_ENABLE_MASK                                       0x00000010
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_DIV_ENABLE_SET(n)                                     (((uint32_t)(n) << 4  ) & 0x00000010)
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_DIV_ENABLE_CLR                                        0xFFFFFFEF

#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_VOL_SEL_SHIFT                                         1
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_VOL_SEL_MASK                                          0x0000000E
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_VOL_SEL_SET(n)                                        (((uint32_t)(n) << 1  ) & 0x0000000E)
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_VOL_SEL_CLR                                           0xFFFFFFF1

#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_0_ENABLE_SHIFT                                        0
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_0_ENABLE_MASK                                         0x00000001
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_0_ENABLE_SET(n)                                       (((uint32_t)(n) << 0  ) & 0x00000001)
#define AANAREG_LDO3VS_TOP_CTRL_LDO3VS_0_ENABLE_CLR                                          0xFFFFFFFE

#define AANAREG_VBIAS_IBIAS_TOP_CTRL_VBIAS_IBIAS_TOP_25_1_SHIFT                              1
#define AANAREG_VBIAS_IBIAS_TOP_CTRL_VBIAS_IBIAS_TOP_25_1_MASK                               0x03FFFFFE
#define AANAREG_VBIAS_IBIAS_TOP_CTRL_VBIAS_IBIAS_TOP_25_1_SET(n)                             (((uint32_t)(n) << 1  ) & 0x03FFFFFE)
#define AANAREG_VBIAS_IBIAS_TOP_CTRL_VBIAS_IBIAS_TOP_25_1_CLR                                0xFC000001

#define AANAREG_VBIAS_IBIAS_TOP_CTRL_VBIAS_IBIAS_TOP_0_ENABLE_SHIFT                          0
#define AANAREG_VBIAS_IBIAS_TOP_CTRL_VBIAS_IBIAS_TOP_0_ENABLE_MASK                           0x00000001
#define AANAREG_VBIAS_IBIAS_TOP_CTRL_VBIAS_IBIAS_TOP_0_ENABLE_SET(n)                         (((uint32_t)(n) << 0  ) & 0x00000001)
#define AANAREG_VBIAS_IBIAS_TOP_CTRL_VBIAS_IBIAS_TOP_0_ENABLE_CLR                            0xFFFFFFFE

#define AANAREG_LVD_TOP_CTRL_LVD5_8_5_TRIP_VOL_SEL_SHIFT                                     5
#define AANAREG_LVD_TOP_CTRL_LVD5_8_5_TRIP_VOL_SEL_MASK                                      0x000001E0
#define AANAREG_LVD_TOP_CTRL_LVD5_8_5_TRIP_VOL_SEL_SET(n)                                    (((uint32_t)(n) << 5  ) & 0x000001E0)
#define AANAREG_LVD_TOP_CTRL_LVD5_8_5_TRIP_VOL_SEL_CLR                                       0xFFFFFE1F

#define AANAREG_LVD_TOP_CTRL_LVD5_4_2_VREF_SEL_SHIFT                                         2
#define AANAREG_LVD_TOP_CTRL_LVD5_4_2_VREF_SEL_MASK                                          0x0000001C
#define AANAREG_LVD_TOP_CTRL_LVD5_4_2_VREF_SEL_SET(n)                                        (((uint32_t)(n) << 2  ) & 0x0000001C)
#define AANAREG_LVD_TOP_CTRL_LVD5_4_2_VREF_SEL_CLR                                           0xFFFFFFE3

#define AANAREG_LVD_TOP_CTRL_LVD5_1_HPM_SHIFT                                                1
#define AANAREG_LVD_TOP_CTRL_LVD5_1_HPM_MASK                                                 0x00000002
#define AANAREG_LVD_TOP_CTRL_LVD5_1_HPM_SET(n)                                               (((uint32_t)(n) << 1  ) & 0x00000002)
#define AANAREG_LVD_TOP_CTRL_LVD5_1_HPM_CLR                                                  0xFFFFFFFD

#define AANAREG_LVD_TOP_CTRL_LVD5_0_ENABLE_SHIFT                                             0
#define AANAREG_LVD_TOP_CTRL_LVD5_0_ENABLE_MASK                                              0x00000001
#define AANAREG_LVD_TOP_CTRL_LVD5_0_ENABLE_SET(n)                                            (((uint32_t)(n) << 0  ) & 0x00000001)
#define AANAREG_LVD_TOP_CTRL_LVD5_0_ENABLE_CLR                                               0xFFFFFFFE

#define AANAREG_LVD_CFG_LVD_FILTER_SHIFT                                                     16
#define AANAREG_LVD_CFG_LVD_FILTER_MASK                                                      0xFFFF0000
#define AANAREG_LVD_CFG_LVD_FILTER_SET(n)                                                    (((uint32_t)(n) << 16 ) & 0xFFFF0000)
#define AANAREG_LVD_CFG_LVD_FILTER_CLR                                                       0x0000FFFF

#define AANAREG_LVD_CFG_LVD_FILTER_EN_SHIFT                                                  15
#define AANAREG_LVD_CFG_LVD_FILTER_EN_MASK                                                   0x00008000
#define AANAREG_LVD_CFG_LVD_FILTER_EN_SET(n)                                                 (((uint32_t)(n) << 15 ) & 0x00008000)
#define AANAREG_LVD_CFG_LVD_FILTER_EN_CLR                                                    0xFFFF7FFF

#define AANAREG_LVD_CFG_A2D_LVD5_SHIFT                                                       13
#define AANAREG_LVD_CFG_A2D_LVD5_MASK                                                        0x00002000
#define AANAREG_LVD_CFG_A2D_LVD5_SET(n)                                                      (((uint32_t)(n) << 13 ) & 0x00002000)
#define AANAREG_LVD_CFG_A2D_LVD5_CLR                                                         0xFFFFDFFF

#define AANAREG_LVD_CFG_LVD_TRIG_EN_SHIFT                                                    12
#define AANAREG_LVD_CFG_LVD_TRIG_EN_MASK                                                     0x00001000
#define AANAREG_LVD_CFG_LVD_TRIG_EN_SET(n)                                                   (((uint32_t)(n) << 12 ) & 0x00001000)
#define AANAREG_LVD_CFG_LVD_TRIG_EN_CLR                                                      0xFFFFEFFF

#define AANAREG_LVD_CFG_LVD_RST_EN_SHIFT                                                     11
#define AANAREG_LVD_CFG_LVD_RST_EN_MASK                                                      0x00000800
#define AANAREG_LVD_CFG_LVD_RST_EN_SET(n)                                                    (((uint32_t)(n) << 11 ) & 0x00000800)
#define AANAREG_LVD_CFG_LVD_RST_EN_CLR                                                       0xFFFFF7FF

#define AANAREG_LVD_CFG_LVD_IRQ_MODE_SHIFT                                                   8
#define AANAREG_LVD_CFG_LVD_IRQ_MODE_MASK                                                    0x00000700
#define AANAREG_LVD_CFG_LVD_IRQ_MODE_SET(n)                                                  (((uint32_t)(n) << 8  ) & 0x00000700)
#define AANAREG_LVD_CFG_LVD_IRQ_MODE_CLR                                                     0xFFFFF8FF

#define AANAREG_LVD_CFG_A2D_LDO15_LVD_SHIFT                                                  5
#define AANAREG_LVD_CFG_A2D_LDO15_LVD_MASK                                                   0x00000020
#define AANAREG_LVD_CFG_A2D_LDO15_LVD_SET(n)                                                 (((uint32_t)(n) << 5  ) & 0x00000020)
#define AANAREG_LVD_CFG_A2D_LDO15_LVD_CLR                                                    0xFFFFFFDF

#define AANAREG_LVD_CFG_LVD15_TRIG_EN_SHIFT                                                  4
#define AANAREG_LVD_CFG_LVD15_TRIG_EN_MASK                                                   0x00000010
#define AANAREG_LVD_CFG_LVD15_TRIG_EN_SET(n)                                                 (((uint32_t)(n) << 4  ) & 0x00000010)
#define AANAREG_LVD_CFG_LVD15_TRIG_EN_CLR                                                    0xFFFFFFEF

#define AANAREG_LVD_CFG_LVD15_RST_EN_SHIFT                                                   3
#define AANAREG_LVD_CFG_LVD15_RST_EN_MASK                                                    0x00000008
#define AANAREG_LVD_CFG_LVD15_RST_EN_SET(n)                                                  (((uint32_t)(n) << 3  ) & 0x00000008)
#define AANAREG_LVD_CFG_LVD15_RST_EN_CLR                                                     0xFFFFFFF7

#define AANAREG_LVD_CFG_LVD15_IRQ_MODE_SHIFT                                                 0
#define AANAREG_LVD_CFG_LVD15_IRQ_MODE_MASK                                                  0x00000007
#define AANAREG_LVD_CFG_LVD15_IRQ_MODE_SET(n)                                                (((uint32_t)(n) << 0  ) & 0x00000007)
#define AANAREG_LVD_CFG_LVD15_IRQ_MODE_CLR                                                   0xFFFFFFF8

#define AANAREG_PORB_AON_BLIAS_LDO15_READY_1V_SHIFT                                          3
#define AANAREG_PORB_AON_BLIAS_LDO15_READY_1V_MASK                                           0x00000008
#define AANAREG_PORB_AON_BLIAS_LDO15_READY_1V_SET(n)                                         (((uint32_t)(n) << 3  ) & 0x00000008)
#define AANAREG_PORB_AON_BLIAS_LDO15_READY_1V_CLR                                            0xFFFFFFF7

#define AANAREG_PORB_AON_BLIAS_PORB_VSW5AON_1V_SHIFT                                         1
#define AANAREG_PORB_AON_BLIAS_PORB_VSW5AON_1V_MASK                                          0x00000002
#define AANAREG_PORB_AON_BLIAS_PORB_VSW5AON_1V_SET(n)                                        (((uint32_t)(n) << 1  ) & 0x00000002)
#define AANAREG_PORB_AON_BLIAS_PORB_VSW5AON_1V_CLR                                           0xFFFFFFFD

#define AANAREG_TEST_MUX_TOP1_CTRL_TESTMUX_AIN_SHIFT                                         0
#define AANAREG_TEST_MUX_TOP1_CTRL_TESTMUX_AIN_MASK                                          0x0000FFFF
#define AANAREG_TEST_MUX_TOP1_CTRL_TESTMUX_AIN_SET(n)                                        (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define AANAREG_TEST_MUX_TOP1_CTRL_TESTMUX_AIN_CLR                                           0xFFFF0000

#define AANAREG_TEST_MUX_TOP2_CTRL_TESTMUX_AOUT_SHIFT                                        0
#define AANAREG_TEST_MUX_TOP2_CTRL_TESTMUX_AOUT_MASK                                         0x0000000F
#define AANAREG_TEST_MUX_TOP2_CTRL_TESTMUX_AOUT_SET(n)                                       (((uint32_t)(n) << 0  ) & 0x0000000F)
#define AANAREG_TEST_MUX_TOP2_CTRL_TESTMUX_AOUT_CLR                                          0xFFFFFFF0

#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_CAPTOUCH_SHIFT                                   4
#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_CAPTOUCH_MASK                                    0x00000010
#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_CAPTOUCH_SET(n)                                  (((uint32_t)(n) << 4  ) & 0x00000010)
#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_CAPTOUCH_CLR                                     0xFFFFFFEF

#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_SARADC_SHIFT                                     3
#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_SARADC_MASK                                      0x00000008
#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_SARADC_SET(n)                                    (((uint32_t)(n) << 3  ) & 0x00000008)
#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_SARADC_CLR                                       0xFFFFFFF7

#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_SWD_SHIFT                                        2
#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_SWD_MASK                                         0x00000004
#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_SWD_SET(n)                                       (((uint32_t)(n) << 2  ) & 0x00000004)
#define AANAREG_CHIP_DEFEATURE_FUSE_DISABLE_SWD_CLR                                          0xFFFFFFFB

#define AANAREG_CHIP_DEFEATURE_FUSE_ENABLE_SRAM_SHRINK_SHIFT                                 1
#define AANAREG_CHIP_DEFEATURE_FUSE_ENABLE_SRAM_SHRINK_MASK                                  0x00000002
#define AANAREG_CHIP_DEFEATURE_FUSE_ENABLE_SRAM_SHRINK_SET(n)                                (((uint32_t)(n) << 1  ) & 0x00000002)
#define AANAREG_CHIP_DEFEATURE_FUSE_ENABLE_SRAM_SHRINK_CLR                                   0xFFFFFFFD

#define AANAREG_CHIP_DEFEATURE_FUSE_ENABLE_FLASH_SHRINK_SHIFT                                0
#define AANAREG_CHIP_DEFEATURE_FUSE_ENABLE_FLASH_SHRINK_MASK                                 0x00000001
#define AANAREG_CHIP_DEFEATURE_FUSE_ENABLE_FLASH_SHRINK_SET(n)                               (((uint32_t)(n) << 0  ) & 0x00000001)
#define AANAREG_CHIP_DEFEATURE_FUSE_ENABLE_FLASH_SHRINK_CLR                                  0xFFFFFFFE

#define AANAREG_TRIM_CONSTGM_VALUE_TRIM_CONSTGM_SHIFT                                        0
#define AANAREG_TRIM_CONSTGM_VALUE_TRIM_CONSTGM_MASK                                         0x000000FF
#define AANAREG_TRIM_CONSTGM_VALUE_TRIM_CONSTGM_SET(n)                                       (((uint32_t)(n) << 0  ) & 0x000000FF)
#define AANAREG_TRIM_CONSTGM_VALUE_TRIM_CONSTGM_CLR                                          0xFFFFFF00

#define AANAREG_TRIM_OSCRC32K_VALUE_OSCRC32K_TRIM_RES_SHIFT                                  0
#define AANAREG_TRIM_OSCRC32K_VALUE_OSCRC32K_TRIM_RES_MASK                                   0x000007FF
#define AANAREG_TRIM_OSCRC32K_VALUE_OSCRC32K_TRIM_RES_SET(n)                                 (((uint32_t)(n) << 0  ) & 0x000007FF)
#define AANAREG_TRIM_OSCRC32K_VALUE_OSCRC32K_TRIM_RES_CLR                                    0xFFFFF800

#define AANAREG_TRIM_OSCRC16M_VALUE_TRIM_OSCRC16M_SHIFT                                      0
#define AANAREG_TRIM_OSCRC16M_VALUE_TRIM_OSCRC16M_MASK                                       0x0000FFFF
#define AANAREG_TRIM_OSCRC16M_VALUE_TRIM_OSCRC16M_SET(n)                                     (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define AANAREG_TRIM_OSCRC16M_VALUE_TRIM_OSCRC16M_CLR                                        0xFFFF0000

#define AANAREG_TRIM_VBIAS_IBIAS_VALUE_TRIM_VBIAS_IBIAS_TOP_SHIFT                            0
#define AANAREG_TRIM_VBIAS_IBIAS_VALUE_TRIM_VBIAS_IBIAS_TOP_MASK                             0x00FFFFFF
#define AANAREG_TRIM_VBIAS_IBIAS_VALUE_TRIM_VBIAS_IBIAS_TOP_SET(n)                           (((uint32_t)(n) << 0  ) & 0x00FFFFFF)
#define AANAREG_TRIM_VBIAS_IBIAS_VALUE_TRIM_VBIAS_IBIAS_TOP_CLR                              0xFF000000

#define AANAREG_TRIM_BGR_VALUE_TRIM_BGR_SHIFT                                                0
#define AANAREG_TRIM_BGR_VALUE_TRIM_BGR_MASK                                                 0x3FFFFFFF
#define AANAREG_TRIM_BGR_VALUE_TRIM_BGR_SET(n)                                               (((uint32_t)(n) << 0  ) & 0x3FFFFFFF)
#define AANAREG_TRIM_BGR_VALUE_TRIM_BGR_CLR                                                  0xC0000000

#define AANAREG_ANALOG_TRIM_STATUS_TRIM_STATUS_SHIFT                                         0
#define AANAREG_ANALOG_TRIM_STATUS_TRIM_STATUS_MASK                                          0x0000FFFF
#define AANAREG_ANALOG_TRIM_STATUS_TRIM_STATUS_SET(n)                                        (((uint32_t)(n) << 0  ) & 0x0000FFFF)
#define AANAREG_ANALOG_TRIM_STATUS_TRIM_STATUS_CLR                                           0xFFFF0000

// Register Structure Definition
typedef struct
{
    __IO uint32_t REAL_CHIP_ID                  : 16 ; // 15 : 0 
    __IO uint32_t A2D_CHIP_ID_1P5V              : 9  ; // 24 : 16 
    __IO uint32_t RESERVED0                     : 7  ; // 31 : 25 
} AANAREG_CHIP_ID_FIELD_T;

typedef struct
{
    __IO uint32_t RESERVED1                     : 1  ; // 0  : 0 
    __IO uint32_t CTRL_OSCRC32K_FSEL            : 1  ; // 1  : 1 
    __IO uint32_t CTRL_OSCRC32K_TEST_EN         : 1  ; // 2  : 2 
    __IO uint32_t CTRL_DEGLITCH_OSCRC32K        : 5  ; // 7  : 3 
    __IO uint32_t RESERVED0                     : 24 ; // 31 : 8 
} AANAREG_OSCRC_32K_TOP_FIELD_T;

typedef struct
{
    __IO uint32_t CTRL_OSCRC16M_0_ENABLE        : 1  ; // 0  : 0 
    __IO uint32_t CTRL_OSCRC16M_1               : 1  ; // 1  : 1 
    __IO uint32_t CTRL_DEGLITCH_OSCRC16M        : 5  ; // 6  : 2 
    __IO uint32_t CTRL_OSCRC16M_CLKREADY        : 1  ; // 7  : 7 
    __IO uint32_t CTRL_FD_EN_0_ENABLE           : 1  ; // 8  : 8 
    __IO uint32_t CTRL_FD_EN_1                  : 1  ; // 9  : 9 
    __IO uint32_t RESERVED0                     : 22 ; // 31 : 10 
} AANAREG_OSCRC_16M_TOP_FIELD_T;

typedef struct
{
    __IO uint32_t CTRL_LDO15_0_ENABLE           : 1  ; // 0  : 0 
    __IO uint32_t CTRL_LDO15_2_1                : 2  ; // 2  : 1 
    __IO uint32_t CTRL_LDO15_3_OUT_ENABLE       : 1  ; // 3  : 3 
    __IO uint32_t CTRL_LDO15_15_4               : 12 ; // 15 : 4 
    __IO uint32_t RESERVED0                     : 16 ; // 31 : 16 
} AANAREG_LDO15_TOP_FIELD_T;

typedef struct
{
    __IO uint32_t CTRL_LDO3VS_0_ENABLE          : 1  ; // 0  : 0 
    __IO uint32_t CTRL_LDO3VS_VOL_SEL           : 3  ; // 3  : 1 
    __IO uint32_t CTRL_LDO3VS_DIV_ENABLE        : 1  ; // 4  : 4 
    __IO uint32_t CTRL_LDO3VS_DIV_SEL           : 3  ; // 7  : 5 
    __IO uint32_t CTRL_LDO3VS_AUTO_MODE         : 1  ; // 8  : 8 
    __IO uint32_t RESERVED0                     : 23 ; // 31 : 9 
} AANAREG_LDO3VS_TOP_FIELD_T;

typedef struct
{
    __IO uint32_t CTRL_VBIAS_IBIAS_TOP_0_ENABLE : 1  ; // 0  : 0 
    __IO uint32_t CTRL_VBIAS_IBIAS_TOP_25_1     : 25 ; // 25 : 1 
    __IO uint32_t RESERVED0                     : 6  ; // 31 : 26 
} AANAREG_VBIAS_IBIAS_TOP_FIELD_T;

typedef struct
{
    __IO uint32_t CTRL_LVD5_0_ENABLE            : 1  ; // 0  : 0 
    __IO uint32_t CTRL_LVD5_1_HPM               : 1  ; // 1  : 1 
    __IO uint32_t CTRL_LVD5_4_2_VREF_SEL        : 3  ; // 4  : 2 
    __IO uint32_t CTRL_LVD5_8_5_TRIP_VOL_SEL    : 4  ; // 8  : 5 
    __IO uint32_t RESERVED0                     : 23 ; // 31 : 9 
} AANAREG_LVD_TOP_FIELD_T;

typedef struct
{
    __IO uint32_t LVD15_IRQ_MODE                : 3  ; // 2  : 0 
    __IO uint32_t LVD15_RST_EN                  : 1  ; // 3  : 3 
    __IO uint32_t LVD15_TRIG_EN                 : 1  ; // 4  : 4 
    __IO uint32_t A2D_LDO15_LVD                 : 1  ; // 5  : 5 
    __IO uint32_t RESERVED1                     : 2  ; // 7  : 6 
    __IO uint32_t LVD_IRQ_MODE                  : 3  ; // 10 : 8 
    __IO uint32_t LVD_RST_EN                    : 1  ; // 11 : 11 
    __IO uint32_t LVD_TRIG_EN                   : 1  ; // 12 : 12 
    __IO uint32_t A2D_LVD5                      : 1  ; // 13 : 13 
    __IO uint32_t RESERVED0                     : 1  ; // 14 : 14 
    __IO uint32_t LVD_FILTER_EN                 : 1  ; // 15 : 15 
    __IO uint32_t LVD_FILTER                    : 16 ; // 31 : 16 
} AANAREG_LVD_CFG_FIELD_T;

typedef struct
{
    __IO uint32_t RESERVED2                     : 1  ; // 0  : 0 
    __IO uint32_t PORB_VSW5AON_1V               : 1  ; // 1  : 1 
    __IO uint32_t RESERVED1                     : 1  ; // 2  : 2 
    __IO uint32_t LDO15_READY_1V                : 1  ; // 3  : 3 
    __IO uint32_t RESERVED0                     : 28 ; // 31 : 4 
} AANAREG_PORB_AON_BLIAS_FIELD_T;

typedef struct
{
    __IO uint32_t CTRL_TESTMUX_AIN              : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0                     : 16 ; // 31 : 16 
} AANAREG_TEST_MUX_TOP1_FIELD_T;

typedef struct
{
    __IO uint32_t CTRL_TESTMUX_AOUT             : 4  ; // 3  : 0 
    __IO uint32_t RESERVED0                     : 28 ; // 31 : 4 
} AANAREG_TEST_MUX_TOP2_FIELD_T;

typedef struct
{
    __IO uint32_t FUSE_ENABLE_FLASH_SHRINK      : 1  ; // 0  : 0 
    __IO uint32_t FUSE_ENABLE_SRAM_SHRINK       : 1  ; // 1  : 1 
    __IO uint32_t FUSE_DISABLE_SWD              : 1  ; // 2  : 2 
    __IO uint32_t FUSE_DISABLE_SARADC           : 1  ; // 3  : 3 
    __IO uint32_t FUSE_DISABLE_CAPTOUCH         : 1  ; // 4  : 4 
    __IO uint32_t RESERVED0                     : 27 ; // 31 : 5 
} AANAREG_CHIP_DEFEATURE_FIELD_T;

typedef struct
{
    __IO uint32_t TRIM_CONSTGM                  : 8  ; // 7  : 0 
    __IO uint32_t RESERVED0                     : 24 ; // 31 : 8 
} AANAREG_TRIM_CONSTGM_VALUE_FIELD_T;

typedef struct
{
    __IO uint32_t OSCRC32K_TRIM_RES             : 11 ; // 10 : 0 
    __IO uint32_t RESERVED0                     : 21 ; // 31 : 11 
} AANAREG_TRIM_OSCRC32K_VALUE_FIELD_T;

typedef struct
{
    __IO uint32_t TRIM_OSCRC16M                 : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0                     : 16 ; // 31 : 16 
} AANAREG_TRIM_OSCRC16M_VALUE_FIELD_T;

typedef struct
{
    __IO uint32_t TRIM_VBIAS_IBIAS_TOP          : 24 ; // 23 : 0 
    __IO uint32_t RESERVED0                     : 8  ; // 31 : 24 
} AANAREG_TRIM_VBIAS_IBIAS_VALUE_FIELD_T;

typedef struct
{
    __IO uint32_t TRIM_BGR                      : 30 ; // 29 : 0 
    __IO uint32_t RESERVED0                     : 2  ; // 31 : 30 
} AANAREG_TRIM_BGR_VALUE_FIELD_T;

typedef struct
{
    __IO uint32_t TRIM_STATUS                   : 16 ; // 15 : 0 
    __IO uint32_t RESERVED0                     : 16 ; // 31 : 16 
} AANAREG_ANALOG_TRIM_STATUS_FIELD_T;

// Register Map Structure Definition
typedef struct
{
    union 
    { 
        __IO  uint32_t CHIP_ID                                         ; // 0x0000
        AANAREG_CHIP_ID_FIELD_T CHIP_ID_F                              ;
    };

    union 
    { 
        __IO  uint32_t OSCRC_32K_TOP                                   ; // 0x0004
        AANAREG_OSCRC_32K_TOP_FIELD_T OSCRC_32K_TOP_F                  ;
    };

    union 
    { 
        __IO  uint32_t OSCRC_16M_TOP                                   ; // 0x0008
        AANAREG_OSCRC_16M_TOP_FIELD_T OSCRC_16M_TOP_F                  ;
    };

    union 
    { 
        __IO  uint32_t LDO15_TOP                                       ; // 0x000C
        AANAREG_LDO15_TOP_FIELD_T LDO15_TOP_F                          ;
    };

    union 
    { 
        __IO  uint32_t LDO3VS_TOP                                      ; // 0x0010
        AANAREG_LDO3VS_TOP_FIELD_T LDO3VS_TOP_F                        ;
    };

    union 
    { 
        __IO  uint32_t VBIAS_IBIAS_TOP                                 ; // 0x0014
        AANAREG_VBIAS_IBIAS_TOP_FIELD_T VBIAS_IBIAS_TOP_F              ;
    };

    union 
    { 
        __IO  uint32_t LVD_TOP                                         ; // 0x0018
        AANAREG_LVD_TOP_FIELD_T LVD_TOP_F                              ;
    };

    union 
    { 
        __IO  uint32_t LVD_CFG                                         ; // 0x001C
        AANAREG_LVD_CFG_FIELD_T LVD_CFG_F                              ;
    };

    union 
    { 
        __IO  uint32_t PORB_AON_BLIAS                                  ; // 0x0020
        AANAREG_PORB_AON_BLIAS_FIELD_T PORB_AON_BLIAS_F                ;
    };

    union 
    { 
        __IO  uint32_t TEST_MUX_TOP1                                   ; // 0x0024
        AANAREG_TEST_MUX_TOP1_FIELD_T TEST_MUX_TOP1_F                  ;
    };

    union 
    { 
        __IO  uint32_t TEST_MUX_TOP2                                   ; // 0x0028
        AANAREG_TEST_MUX_TOP2_FIELD_T TEST_MUX_TOP2_F                  ;
    };

    union 
    { 
        __IO  uint32_t CHIP_DEFEATURE                                  ; // 0x002C
        AANAREG_CHIP_DEFEATURE_FIELD_T CHIP_DEFEATURE_F                ;
    };

    uint32_t RESERVED0[52]                                              ;

    union 
    { 
        __IO  uint32_t TRIM_CONSTGM_VALUE                              ; // 0x0100
        AANAREG_TRIM_CONSTGM_VALUE_FIELD_T TRIM_CONSTGM_VALUE_F        ;
    };

    union 
    { 
        __IO  uint32_t TRIM_OSCRC32K_VALUE                             ; // 0x0104
        AANAREG_TRIM_OSCRC32K_VALUE_FIELD_T TRIM_OSCRC32K_VALUE_F      ;
    };

    union 
    { 
        __IO  uint32_t TRIM_OSCRC16M_VALUE                             ; // 0x0108
        AANAREG_TRIM_OSCRC16M_VALUE_FIELD_T TRIM_OSCRC16M_VALUE_F      ;
    };

    union 
    { 
        __IO  uint32_t TRIM_VBIAS_IBIAS_VALUE                          ; // 0x010C
        AANAREG_TRIM_VBIAS_IBIAS_VALUE_FIELD_T TRIM_VBIAS_IBIAS_VALUE_F;
    };

    union 
    { 
        __IO  uint32_t TRIM_BGR_VALUE                                  ; // 0x0110
        AANAREG_TRIM_BGR_VALUE_FIELD_T TRIM_BGR_VALUE_F                ;
    };

    union 
    { 
        __IO  uint32_t ANALOG_TRIM_STATUS                              ; // 0x0114
        AANAREG_ANALOG_TRIM_STATUS_FIELD_T ANALOG_TRIM_STATUS_F        ;
    };

} AANAREG_REG_TypeDef;

#endif
