//----------------------------------------------------------------------
//         COPYRIGHT (C) 2022 TINYCHIP SEMICONDUCTOR
//              CONFIDENTIAL & ALL RIGHTS RESERVED
//----------------------------------------------------------------------
// File name      : captouch_reg_def.h
// Author         : mfpan
// E-Mail         : mfpan@tinychip.com.cn
//----------------------------------------------------------------------
// Description    :
// Register Header File of CAPTOUCH
//----------------------------------------------------------------------
// Reversion History:
// 2022-10-21 17:24:10 -- automatically generated by reg_gen.pl Revision 1.11
//----------------------------------------------------------------------

#ifndef   CAPTOUCH_DEF_H__
#define   CAPTOUCH_DEF_H__

// Register Offset Macro Definition
#define CAPTOUCH_CTRL_CONV_0_OFFSET                             0x0000
#define CAPTOUCH_CTRL_INIT_0_OFFSET                             0x0004
#define CAPTOUCH_CTRL_ADC_0_OFFSET                              0x0008
#define CAPTOUCH_CTRL_HOP_0_OFFSET                              0x000C
#define CAPTOUCH_CTRL_SCAN_0_OFFSET                             0x0010
#define CAPTOUCH_CTRL_OUT_0_OFFSET                              0x0014
#define CAPTOUCH_CTRL_FIFO_0_OFFSET                             0x0018
#define CAPTOUCH_FIFO_DATA_0_OFFSET                             0x001C
#define CAPTOUCH_CTRL_CONV_1_OFFSET                             0x0020
#define CAPTOUCH_CTRL_INIT_1_OFFSET                             0x0024
#define CAPTOUCH_CTRL_ADC_1_OFFSET                              0x0028
#define CAPTOUCH_CTRL_HOP_1_OFFSET                              0x002C
#define CAPTOUCH_CTRL_SCAN_1_OFFSET                             0x0030
#define CAPTOUCH_CTRL_OUT_1_OFFSET                              0x0034
#define CAPTOUCH_CTRL_FIFO_1_OFFSET                             0x0038
#define CAPTOUCH_FIFO_DATA_1_OFFSET                             0x003C
#define CAPTOUCH_IMR_OFFSET                                     0x0040
#define CAPTOUCH_ICR_OFFSET                                     0x0044
#define CAPTOUCH_ISR_OFFSET                                     0x0048
#define CAPTOUCH_IRSR_OFFSET                                    0x004C
#define CAPTOUCH_CTRL_ANASW_OFFSET                              0x0050

// Register Address Macro Definition
#define CAPTOUCH_CTRL_CONV_0_ADDR                               ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_CONV_0_OFFSET)
#define CAPTOUCH_CTRL_INIT_0_ADDR                               ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_INIT_0_OFFSET)
#define CAPTOUCH_CTRL_ADC_0_ADDR                                ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_ADC_0_OFFSET)
#define CAPTOUCH_CTRL_HOP_0_ADDR                                ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_HOP_0_OFFSET)
#define CAPTOUCH_CTRL_SCAN_0_ADDR                               ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_SCAN_0_OFFSET)
#define CAPTOUCH_CTRL_OUT_0_ADDR                                ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_OUT_0_OFFSET)
#define CAPTOUCH_CTRL_FIFO_0_ADDR                               ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_FIFO_0_OFFSET)
#define CAPTOUCH_FIFO_DATA_0_ADDR                               ( CAPTOUCH_BASE_ADDR + CAPTOUCH_FIFO_DATA_0_OFFSET)
#define CAPTOUCH_CTRL_CONV_1_ADDR                               ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_CONV_1_OFFSET)
#define CAPTOUCH_CTRL_INIT_1_ADDR                               ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_INIT_1_OFFSET)
#define CAPTOUCH_CTRL_ADC_1_ADDR                                ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_ADC_1_OFFSET)
#define CAPTOUCH_CTRL_HOP_1_ADDR                                ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_HOP_1_OFFSET)
#define CAPTOUCH_CTRL_SCAN_1_ADDR                               ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_SCAN_1_OFFSET)
#define CAPTOUCH_CTRL_OUT_1_ADDR                                ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_OUT_1_OFFSET)
#define CAPTOUCH_CTRL_FIFO_1_ADDR                               ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_FIFO_1_OFFSET)
#define CAPTOUCH_FIFO_DATA_1_ADDR                               ( CAPTOUCH_BASE_ADDR + CAPTOUCH_FIFO_DATA_1_OFFSET)
#define CAPTOUCH_IMR_ADDR                                       ( CAPTOUCH_BASE_ADDR + CAPTOUCH_IMR_OFFSET)
#define CAPTOUCH_ICR_ADDR                                       ( CAPTOUCH_BASE_ADDR + CAPTOUCH_ICR_OFFSET)
#define CAPTOUCH_ISR_ADDR                                       ( CAPTOUCH_BASE_ADDR + CAPTOUCH_ISR_OFFSET)
#define CAPTOUCH_IRSR_ADDR                                      ( CAPTOUCH_BASE_ADDR + CAPTOUCH_IRSR_OFFSET)
#define CAPTOUCH_CTRL_ANASW_ADDR                                ( CAPTOUCH_BASE_ADDR + CAPTOUCH_CTRL_ANASW_OFFSET)

// Register Field Macro Definition
#define CAPTOUCH_CTRL_CONV_0_TW_TRIG_EN_0_SHIFT                       12
#define CAPTOUCH_CTRL_CONV_0_TW_TRIG_EN_0_MASK                        0x00001000
#define CAPTOUCH_CTRL_CONV_0_TW_TRIG_EN_0_SET(n)                      (((uint32_t)(n) << 12 ) & 0x00001000)
#define CAPTOUCH_CTRL_CONV_0_TW_TRIG_EN_0_CLR                         0xFFFFEFFF

#define CAPTOUCH_CTRL_CONV_0_SW_CTRL_CONV_0_SHIFT                     11
#define CAPTOUCH_CTRL_CONV_0_SW_CTRL_CONV_0_MASK                      0x00000800
#define CAPTOUCH_CTRL_CONV_0_SW_CTRL_CONV_0_SET(n)                    (((uint32_t)(n) << 11 ) & 0x00000800)
#define CAPTOUCH_CTRL_CONV_0_SW_CTRL_CONV_0_CLR                       0xFFFFF7FF

#define CAPTOUCH_CTRL_CONV_0_CONV_LOOP_0_SHIFT                        8
#define CAPTOUCH_CTRL_CONV_0_CONV_LOOP_0_MASK                         0x00000700
#define CAPTOUCH_CTRL_CONV_0_CONV_LOOP_0_SET(n)                       (((uint32_t)(n) << 8  ) & 0x00000700)
#define CAPTOUCH_CTRL_CONV_0_CONV_LOOP_0_CLR                          0xFFFFF8FF

#define CAPTOUCH_CTRL_CONV_0_SW_CHNL_SEL_0_SHIFT                      4
#define CAPTOUCH_CTRL_CONV_0_SW_CHNL_SEL_0_MASK                       0x000000F0
#define CAPTOUCH_CTRL_CONV_0_SW_CHNL_SEL_0_SET(n)                     (((uint32_t)(n) << 4  ) & 0x000000F0)
#define CAPTOUCH_CTRL_CONV_0_SW_CHNL_SEL_0_CLR                        0xFFFFFF0F

#define CAPTOUCH_CTRL_CONV_0_SW_TRIG_0_SHIFT                          3
#define CAPTOUCH_CTRL_CONV_0_SW_TRIG_0_MASK                           0x00000008
#define CAPTOUCH_CTRL_CONV_0_SW_TRIG_0_SET(n)                         (((uint32_t)(n) << 3  ) & 0x00000008)
#define CAPTOUCH_CTRL_CONV_0_SW_TRIG_0_CLR                            0xFFFFFFF7

#define CAPTOUCH_CTRL_CONV_0_CAPTOUCH_MODE_0_SHIFT                    1
#define CAPTOUCH_CTRL_CONV_0_CAPTOUCH_MODE_0_MASK                     0x00000006
#define CAPTOUCH_CTRL_CONV_0_CAPTOUCH_MODE_0_SET(n)                   (((uint32_t)(n) << 1  ) & 0x00000006)
#define CAPTOUCH_CTRL_CONV_0_CAPTOUCH_MODE_0_CLR                      0xFFFFFFF9

#define CAPTOUCH_CTRL_CONV_0_CAPTOUCH_EN_0_SHIFT                      0
#define CAPTOUCH_CTRL_CONV_0_CAPTOUCH_EN_0_MASK                       0x00000001
#define CAPTOUCH_CTRL_CONV_0_CAPTOUCH_EN_0_SET(n)                     (((uint32_t)(n) << 0  ) & 0x00000001)
#define CAPTOUCH_CTRL_CONV_0_CAPTOUCH_EN_0_CLR                        0xFFFFFFFE

#define CAPTOUCH_CTRL_INIT_0_DISCHRG_CYCLE_0_SHIFT                    24
#define CAPTOUCH_CTRL_INIT_0_DISCHRG_CYCLE_0_MASK                     0xFF000000
#define CAPTOUCH_CTRL_INIT_0_DISCHRG_CYCLE_0_SET(n)                   (((uint32_t)(n) << 24 ) & 0xFF000000)
#define CAPTOUCH_CTRL_INIT_0_DISCHRG_CYCLE_0_CLR                      0x00FFFFFF

#define CAPTOUCH_CTRL_INIT_0_INIT_CYCLE_0_SHIFT                       16
#define CAPTOUCH_CTRL_INIT_0_INIT_CYCLE_0_MASK                        0x00FF0000
#define CAPTOUCH_CTRL_INIT_0_INIT_CYCLE_0_SET(n)                      (((uint32_t)(n) << 16 ) & 0x00FF0000)
#define CAPTOUCH_CTRL_INIT_0_INIT_CYCLE_0_CLR                         0xFF00FFFF

#define CAPTOUCH_CTRL_INIT_0_TRANS_CYCLE_0_SHIFT                      12
#define CAPTOUCH_CTRL_INIT_0_TRANS_CYCLE_0_MASK                       0x00007000
#define CAPTOUCH_CTRL_INIT_0_TRANS_CYCLE_0_SET(n)                     (((uint32_t)(n) << 12 ) & 0x00007000)
#define CAPTOUCH_CTRL_INIT_0_TRANS_CYCLE_0_CLR                        0xFFFF8FFF

#define CAPTOUCH_CTRL_INIT_0_CHRG_CYCLE_0_SHIFT                       8
#define CAPTOUCH_CTRL_INIT_0_CHRG_CYCLE_0_MASK                        0x00000700
#define CAPTOUCH_CTRL_INIT_0_CHRG_CYCLE_0_SET(n)                      (((uint32_t)(n) << 8  ) & 0x00000700)
#define CAPTOUCH_CTRL_INIT_0_CHRG_CYCLE_0_CLR                         0xFFFFF8FF

#define CAPTOUCH_CTRL_INIT_0_SW_PD_MODE_0_SHIFT                       7
#define CAPTOUCH_CTRL_INIT_0_SW_PD_MODE_0_MASK                        0x00000080
#define CAPTOUCH_CTRL_INIT_0_SW_PD_MODE_0_SET(n)                      (((uint32_t)(n) << 7  ) & 0x00000080)
#define CAPTOUCH_CTRL_INIT_0_SW_PD_MODE_0_CLR                         0xFFFFFF7F

#define CAPTOUCH_CTRL_INIT_0_SW_PD_CTRL_0_SHIFT                       0
#define CAPTOUCH_CTRL_INIT_0_SW_PD_CTRL_0_MASK                        0x0000007F
#define CAPTOUCH_CTRL_INIT_0_SW_PD_CTRL_0_SET(n)                      (((uint32_t)(n) << 0  ) & 0x0000007F)
#define CAPTOUCH_CTRL_INIT_0_SW_PD_CTRL_0_CLR                         0xFFFFFF80

#define CAPTOUCH_CTRL_ADC_0_MAX_CNT_DET_EN_0_SHIFT                    28
#define CAPTOUCH_CTRL_ADC_0_MAX_CNT_DET_EN_0_MASK                     0x10000000
#define CAPTOUCH_CTRL_ADC_0_MAX_CNT_DET_EN_0_SET(n)                   (((uint32_t)(n) << 28 ) & 0x10000000)
#define CAPTOUCH_CTRL_ADC_0_MAX_CNT_DET_EN_0_CLR                      0xEFFFFFFF

#define CAPTOUCH_CTRL_ADC_0_MAX_CNT_0_SHIFT                           16
#define CAPTOUCH_CTRL_ADC_0_MAX_CNT_0_MASK                            0x0FFF0000
#define CAPTOUCH_CTRL_ADC_0_MAX_CNT_0_SET(n)                          (((uint32_t)(n) << 16 ) & 0x0FFF0000)
#define CAPTOUCH_CTRL_ADC_0_MAX_CNT_0_CLR                             0xF000FFFF

#define CAPTOUCH_CTRL_ADC_0_ADC_CHNL_CLR_0_SHIFT                      13
#define CAPTOUCH_CTRL_ADC_0_ADC_CHNL_CLR_0_MASK                       0x00002000
#define CAPTOUCH_CTRL_ADC_0_ADC_CHNL_CLR_0_SET(n)                     (((uint32_t)(n) << 13 ) & 0x00002000)
#define CAPTOUCH_CTRL_ADC_0_ADC_CHNL_CLR_0_CLR                        0xFFFFDFFF

#define CAPTOUCH_CTRL_ADC_0_ADC_CHNL_RDY_0_SHIFT                      12
#define CAPTOUCH_CTRL_ADC_0_ADC_CHNL_RDY_0_MASK                       0x00001000
#define CAPTOUCH_CTRL_ADC_0_ADC_CHNL_RDY_0_SET(n)                     (((uint32_t)(n) << 12 ) & 0x00001000)
#define CAPTOUCH_CTRL_ADC_0_ADC_CHNL_RDY_0_CLR                        0xFFFFEFFF

#define CAPTOUCH_CTRL_ADC_0_ADC_CYCLE_0_SHIFT                         0
#define CAPTOUCH_CTRL_ADC_0_ADC_CYCLE_0_MASK                          0x00000FFF
#define CAPTOUCH_CTRL_ADC_0_ADC_CYCLE_0_SET(n)                        (((uint32_t)(n) << 0  ) & 0x00000FFF)
#define CAPTOUCH_CTRL_ADC_0_ADC_CYCLE_0_CLR                           0xFFFFF000

#define CAPTOUCH_CTRL_HOP_0_HOP_PERIOD_0_SHIFT                        24
#define CAPTOUCH_CTRL_HOP_0_HOP_PERIOD_0_MASK                         0x07000000
#define CAPTOUCH_CTRL_HOP_0_HOP_PERIOD_0_SET(n)                       (((uint32_t)(n) << 24 ) & 0x07000000)
#define CAPTOUCH_CTRL_HOP_0_HOP_PERIOD_0_CLR                          0xF8FFFFFF

#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_7_0_SHIFT                         21
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_7_0_MASK                          0x00E00000
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_7_0_SET(n)                        (((uint32_t)(n) << 21 ) & 0x00E00000)
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_7_0_CLR                           0xFF1FFFFF

#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_6_0_SHIFT                         18
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_6_0_MASK                          0x001C0000
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_6_0_SET(n)                        (((uint32_t)(n) << 18 ) & 0x001C0000)
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_6_0_CLR                           0xFFE3FFFF

#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_5_0_SHIFT                         15
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_5_0_MASK                          0x00038000
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_5_0_SET(n)                        (((uint32_t)(n) << 15 ) & 0x00038000)
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_5_0_CLR                           0xFFFC7FFF

#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_4_0_SHIFT                         12
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_4_0_MASK                          0x00007000
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_4_0_SET(n)                        (((uint32_t)(n) << 12 ) & 0x00007000)
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_4_0_CLR                           0xFFFF8FFF

#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_3_0_SHIFT                         9
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_3_0_MASK                          0x00000E00
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_3_0_SET(n)                        (((uint32_t)(n) << 9  ) & 0x00000E00)
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_3_0_CLR                           0xFFFFF1FF

#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_2_0_SHIFT                         6
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_2_0_MASK                          0x000001C0
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_2_0_SET(n)                        (((uint32_t)(n) << 6  ) & 0x000001C0)
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_2_0_CLR                           0xFFFFFE3F

#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_1_0_SHIFT                         3
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_1_0_MASK                          0x00000038
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_1_0_SET(n)                        (((uint32_t)(n) << 3  ) & 0x00000038)
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_1_0_CLR                           0xFFFFFFC7

#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_0_0_SHIFT                         0
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_0_0_MASK                          0x00000007
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_0_0_SET(n)                        (((uint32_t)(n) << 0  ) & 0x00000007)
#define CAPTOUCH_CTRL_HOP_0_HOP_CNT_0_0_CLR                           0xFFFFFFF8

#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_NUM_0_SHIFT                    28
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_NUM_0_MASK                     0x70000000
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_NUM_0_SET(n)                   (((uint32_t)(n) << 28 ) & 0x70000000)
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_NUM_0_CLR                      0x8FFFFFFF

#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_6_0_SHIFT                      24
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_6_0_MASK                       0x0F000000
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_6_0_SET(n)                     (((uint32_t)(n) << 24 ) & 0x0F000000)
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_6_0_CLR                        0xF0FFFFFF

#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_5_0_SHIFT                      20
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_5_0_MASK                       0x00F00000
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_5_0_SET(n)                     (((uint32_t)(n) << 20 ) & 0x00F00000)
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_5_0_CLR                        0xFF0FFFFF

#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_4_0_SHIFT                      16
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_4_0_MASK                       0x000F0000
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_4_0_SET(n)                     (((uint32_t)(n) << 16 ) & 0x000F0000)
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_4_0_CLR                        0xFFF0FFFF

#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_3_0_SHIFT                      12
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_3_0_MASK                       0x0000F000
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_3_0_SET(n)                     (((uint32_t)(n) << 12 ) & 0x0000F000)
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_3_0_CLR                        0xFFFF0FFF

#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_2_0_SHIFT                      8
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_2_0_MASK                       0x00000F00
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_2_0_SET(n)                     (((uint32_t)(n) << 8  ) & 0x00000F00)
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_2_0_CLR                        0xFFFFF0FF

#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_1_0_SHIFT                      4
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_1_0_MASK                       0x000000F0
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_1_0_SET(n)                     (((uint32_t)(n) << 4  ) & 0x000000F0)
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_1_0_CLR                        0xFFFFFF0F

#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_0_0_SHIFT                      0
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_0_0_MASK                       0x0000000F
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_0_0_SET(n)                     (((uint32_t)(n) << 0  ) & 0x0000000F)
#define CAPTOUCH_CTRL_SCAN_0_SCAN_CHNL_0_0_CLR                        0xFFFFFFF0

#define CAPTOUCH_CTRL_OUT_0_CAPTOUCH_BUSY_0_SHIFT                     16
#define CAPTOUCH_CTRL_OUT_0_CAPTOUCH_BUSY_0_MASK                      0x00010000
#define CAPTOUCH_CTRL_OUT_0_CAPTOUCH_BUSY_0_SET(n)                    (((uint32_t)(n) << 16 ) & 0x00010000)
#define CAPTOUCH_CTRL_OUT_0_CAPTOUCH_BUSY_0_CLR                       0xFFFEFFFF

#define CAPTOUCH_CTRL_OUT_0_CHNL_STATUS_0_SHIFT                       12
#define CAPTOUCH_CTRL_OUT_0_CHNL_STATUS_0_MASK                        0x0000F000
#define CAPTOUCH_CTRL_OUT_0_CHNL_STATUS_0_SET(n)                      (((uint32_t)(n) << 12 ) & 0x0000F000)
#define CAPTOUCH_CTRL_OUT_0_CHNL_STATUS_0_CLR                         0xFFFF0FFF

#define CAPTOUCH_CTRL_OUT_0_CHNL_OUT_0_SHIFT                          0
#define CAPTOUCH_CTRL_OUT_0_CHNL_OUT_0_MASK                           0x00000FFF
#define CAPTOUCH_CTRL_OUT_0_CHNL_OUT_0_SET(n)                         (((uint32_t)(n) << 0  ) & 0x00000FFF)
#define CAPTOUCH_CTRL_OUT_0_CHNL_OUT_0_CLR                            0xFFFFF000

#define CAPTOUCH_CTRL_FIFO_0_ENTRY_VALID_0_SHIFT                      8
#define CAPTOUCH_CTRL_FIFO_0_ENTRY_VALID_0_MASK                       0x00000F00
#define CAPTOUCH_CTRL_FIFO_0_ENTRY_VALID_0_SET(n)                     (((uint32_t)(n) << 8  ) & 0x00000F00)
#define CAPTOUCH_CTRL_FIFO_0_ENTRY_VALID_0_CLR                        0xFFFFF0FF

#define CAPTOUCH_CTRL_FIFO_0_FIFO_THRHLD_0_SHIFT                      4
#define CAPTOUCH_CTRL_FIFO_0_FIFO_THRHLD_0_MASK                       0x00000070
#define CAPTOUCH_CTRL_FIFO_0_FIFO_THRHLD_0_SET(n)                     (((uint32_t)(n) << 4  ) & 0x00000070)
#define CAPTOUCH_CTRL_FIFO_0_FIFO_THRHLD_0_CLR                        0xFFFFFF8F

#define CAPTOUCH_CTRL_FIFO_0_DMAREQ_EN_0_SHIFT                        1
#define CAPTOUCH_CTRL_FIFO_0_DMAREQ_EN_0_MASK                         0x00000002
#define CAPTOUCH_CTRL_FIFO_0_DMAREQ_EN_0_SET(n)                       (((uint32_t)(n) << 1  ) & 0x00000002)
#define CAPTOUCH_CTRL_FIFO_0_DMAREQ_EN_0_CLR                          0xFFFFFFFD

#define CAPTOUCH_CTRL_FIFO_0_FIFO_EN_0_SHIFT                          0
#define CAPTOUCH_CTRL_FIFO_0_FIFO_EN_0_MASK                           0x00000001
#define CAPTOUCH_CTRL_FIFO_0_FIFO_EN_0_SET(n)                         (((uint32_t)(n) << 0  ) & 0x00000001)
#define CAPTOUCH_CTRL_FIFO_0_FIFO_EN_0_CLR                            0xFFFFFFFE

#define CAPTOUCH_FIFO_DATA_0_FIFO_RDATA_0_SHIFT                       0
#define CAPTOUCH_FIFO_DATA_0_FIFO_RDATA_0_MASK                        0xFFFFFFFF
#define CAPTOUCH_FIFO_DATA_0_FIFO_RDATA_0_SET(n)                      (((uint32_t)(n) << 0  ) & 0xFFFFFFFF)
#define CAPTOUCH_FIFO_DATA_0_FIFO_RDATA_0_CLR                         0x00000000

#define CAPTOUCH_CTRL_CONV_1_TW_TRIG_EN_1_SHIFT                       12
#define CAPTOUCH_CTRL_CONV_1_TW_TRIG_EN_1_MASK                        0x00001000
#define CAPTOUCH_CTRL_CONV_1_TW_TRIG_EN_1_SET(n)                      (((uint32_t)(n) << 12 ) & 0x00001000)
#define CAPTOUCH_CTRL_CONV_1_TW_TRIG_EN_1_CLR                         0xFFFFEFFF

#define CAPTOUCH_CTRL_CONV_1_SW_CTRL_CONV_1_SHIFT                     11
#define CAPTOUCH_CTRL_CONV_1_SW_CTRL_CONV_1_MASK                      0x00000800
#define CAPTOUCH_CTRL_CONV_1_SW_CTRL_CONV_1_SET(n)                    (((uint32_t)(n) << 11 ) & 0x00000800)
#define CAPTOUCH_CTRL_CONV_1_SW_CTRL_CONV_1_CLR                       0xFFFFF7FF

#define CAPTOUCH_CTRL_CONV_1_CONV_LOOP_1_SHIFT                        8
#define CAPTOUCH_CTRL_CONV_1_CONV_LOOP_1_MASK                         0x00000700
#define CAPTOUCH_CTRL_CONV_1_CONV_LOOP_1_SET(n)                       (((uint32_t)(n) << 8  ) & 0x00000700)
#define CAPTOUCH_CTRL_CONV_1_CONV_LOOP_1_CLR                          0xFFFFF8FF

#define CAPTOUCH_CTRL_CONV_1_SW_CHNL_SEL_1_SHIFT                      4
#define CAPTOUCH_CTRL_CONV_1_SW_CHNL_SEL_1_MASK                       0x000000F0
#define CAPTOUCH_CTRL_CONV_1_SW_CHNL_SEL_1_SET(n)                     (((uint32_t)(n) << 4  ) & 0x000000F0)
#define CAPTOUCH_CTRL_CONV_1_SW_CHNL_SEL_1_CLR                        0xFFFFFF0F

#define CAPTOUCH_CTRL_CONV_1_SW_TRIG_1_SHIFT                          3
#define CAPTOUCH_CTRL_CONV_1_SW_TRIG_1_MASK                           0x00000008
#define CAPTOUCH_CTRL_CONV_1_SW_TRIG_1_SET(n)                         (((uint32_t)(n) << 3  ) & 0x00000008)
#define CAPTOUCH_CTRL_CONV_1_SW_TRIG_1_CLR                            0xFFFFFFF7

#define CAPTOUCH_CTRL_CONV_1_CAPTOUCH_MODE_1_SHIFT                    1
#define CAPTOUCH_CTRL_CONV_1_CAPTOUCH_MODE_1_MASK                     0x00000006
#define CAPTOUCH_CTRL_CONV_1_CAPTOUCH_MODE_1_SET(n)                   (((uint32_t)(n) << 1  ) & 0x00000006)
#define CAPTOUCH_CTRL_CONV_1_CAPTOUCH_MODE_1_CLR                      0xFFFFFFF9

#define CAPTOUCH_CTRL_CONV_1_CAPTOUCH_EN_1_SHIFT                      0
#define CAPTOUCH_CTRL_CONV_1_CAPTOUCH_EN_1_MASK                       0x00000001
#define CAPTOUCH_CTRL_CONV_1_CAPTOUCH_EN_1_SET(n)                     (((uint32_t)(n) << 0  ) & 0x00000001)
#define CAPTOUCH_CTRL_CONV_1_CAPTOUCH_EN_1_CLR                        0xFFFFFFFE

#define CAPTOUCH_CTRL_INIT_1_DISCHRG_CYCLE_1_SHIFT                    24
#define CAPTOUCH_CTRL_INIT_1_DISCHRG_CYCLE_1_MASK                     0xFF000000
#define CAPTOUCH_CTRL_INIT_1_DISCHRG_CYCLE_1_SET(n)                   (((uint32_t)(n) << 24 ) & 0xFF000000)
#define CAPTOUCH_CTRL_INIT_1_DISCHRG_CYCLE_1_CLR                      0x00FFFFFF

#define CAPTOUCH_CTRL_INIT_1_INIT_CYCLE_1_SHIFT                       16
#define CAPTOUCH_CTRL_INIT_1_INIT_CYCLE_1_MASK                        0x00FF0000
#define CAPTOUCH_CTRL_INIT_1_INIT_CYCLE_1_SET(n)                      (((uint32_t)(n) << 16 ) & 0x00FF0000)
#define CAPTOUCH_CTRL_INIT_1_INIT_CYCLE_1_CLR                         0xFF00FFFF

#define CAPTOUCH_CTRL_INIT_1_TRANS_CYCLE_1_SHIFT                      12
#define CAPTOUCH_CTRL_INIT_1_TRANS_CYCLE_1_MASK                       0x00007000
#define CAPTOUCH_CTRL_INIT_1_TRANS_CYCLE_1_SET(n)                     (((uint32_t)(n) << 12 ) & 0x00007000)
#define CAPTOUCH_CTRL_INIT_1_TRANS_CYCLE_1_CLR                        0xFFFF8FFF

#define CAPTOUCH_CTRL_INIT_1_CHRG_CYCLE_1_SHIFT                       8
#define CAPTOUCH_CTRL_INIT_1_CHRG_CYCLE_1_MASK                        0x00000700
#define CAPTOUCH_CTRL_INIT_1_CHRG_CYCLE_1_SET(n)                      (((uint32_t)(n) << 8  ) & 0x00000700)
#define CAPTOUCH_CTRL_INIT_1_CHRG_CYCLE_1_CLR                         0xFFFFF8FF

#define CAPTOUCH_CTRL_INIT_1_SW_PD_MODE_1_SHIFT                       7
#define CAPTOUCH_CTRL_INIT_1_SW_PD_MODE_1_MASK                        0x00000080
#define CAPTOUCH_CTRL_INIT_1_SW_PD_MODE_1_SET(n)                      (((uint32_t)(n) << 7  ) & 0x00000080)
#define CAPTOUCH_CTRL_INIT_1_SW_PD_MODE_1_CLR                         0xFFFFFF7F

#define CAPTOUCH_CTRL_INIT_1_SW_PD_CTRL_1_SHIFT                       0
#define CAPTOUCH_CTRL_INIT_1_SW_PD_CTRL_1_MASK                        0x0000007F
#define CAPTOUCH_CTRL_INIT_1_SW_PD_CTRL_1_SET(n)                      (((uint32_t)(n) << 0  ) & 0x0000007F)
#define CAPTOUCH_CTRL_INIT_1_SW_PD_CTRL_1_CLR                         0xFFFFFF80

#define CAPTOUCH_CTRL_ADC_1_MAX_CNT_DET_EN_1_SHIFT                    28
#define CAPTOUCH_CTRL_ADC_1_MAX_CNT_DET_EN_1_MASK                     0x10000000
#define CAPTOUCH_CTRL_ADC_1_MAX_CNT_DET_EN_1_SET(n)                   (((uint32_t)(n) << 28 ) & 0x10000000)
#define CAPTOUCH_CTRL_ADC_1_MAX_CNT_DET_EN_1_CLR                      0xEFFFFFFF

#define CAPTOUCH_CTRL_ADC_1_MAX_CNT_1_SHIFT                           16
#define CAPTOUCH_CTRL_ADC_1_MAX_CNT_1_MASK                            0x0FFF0000
#define CAPTOUCH_CTRL_ADC_1_MAX_CNT_1_SET(n)                          (((uint32_t)(n) << 16 ) & 0x0FFF0000)
#define CAPTOUCH_CTRL_ADC_1_MAX_CNT_1_CLR                             0xF000FFFF

#define CAPTOUCH_CTRL_ADC_1_ADC_CHNL_CLR_1_SHIFT                      13
#define CAPTOUCH_CTRL_ADC_1_ADC_CHNL_CLR_1_MASK                       0x00002000
#define CAPTOUCH_CTRL_ADC_1_ADC_CHNL_CLR_1_SET(n)                     (((uint32_t)(n) << 13 ) & 0x00002000)
#define CAPTOUCH_CTRL_ADC_1_ADC_CHNL_CLR_1_CLR                        0xFFFFDFFF

#define CAPTOUCH_CTRL_ADC_1_ADC_CHNL_RDY_1_SHIFT                      12
#define CAPTOUCH_CTRL_ADC_1_ADC_CHNL_RDY_1_MASK                       0x00001000
#define CAPTOUCH_CTRL_ADC_1_ADC_CHNL_RDY_1_SET(n)                     (((uint32_t)(n) << 12 ) & 0x00001000)
#define CAPTOUCH_CTRL_ADC_1_ADC_CHNL_RDY_1_CLR                        0xFFFFEFFF

#define CAPTOUCH_CTRL_ADC_1_ADC_CYCLE_1_SHIFT                         0
#define CAPTOUCH_CTRL_ADC_1_ADC_CYCLE_1_MASK                          0x00000FFF
#define CAPTOUCH_CTRL_ADC_1_ADC_CYCLE_1_SET(n)                        (((uint32_t)(n) << 0  ) & 0x00000FFF)
#define CAPTOUCH_CTRL_ADC_1_ADC_CYCLE_1_CLR                           0xFFFFF000

#define CAPTOUCH_CTRL_HOP_1_HOP_PERIOD_1_SHIFT                        24
#define CAPTOUCH_CTRL_HOP_1_HOP_PERIOD_1_MASK                         0x07000000
#define CAPTOUCH_CTRL_HOP_1_HOP_PERIOD_1_SET(n)                       (((uint32_t)(n) << 24 ) & 0x07000000)
#define CAPTOUCH_CTRL_HOP_1_HOP_PERIOD_1_CLR                          0xF8FFFFFF

#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_7_1_SHIFT                         21
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_7_1_MASK                          0x00E00000
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_7_1_SET(n)                        (((uint32_t)(n) << 21 ) & 0x00E00000)
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_7_1_CLR                           0xFF1FFFFF

#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_6_1_SHIFT                         18
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_6_1_MASK                          0x001C0000
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_6_1_SET(n)                        (((uint32_t)(n) << 18 ) & 0x001C0000)
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_6_1_CLR                           0xFFE3FFFF

#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_5_1_SHIFT                         15
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_5_1_MASK                          0x00038000
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_5_1_SET(n)                        (((uint32_t)(n) << 15 ) & 0x00038000)
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_5_1_CLR                           0xFFFC7FFF

#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_4_1_SHIFT                         12
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_4_1_MASK                          0x00007000
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_4_1_SET(n)                        (((uint32_t)(n) << 12 ) & 0x00007000)
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_4_1_CLR                           0xFFFF8FFF

#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_3_1_SHIFT                         9
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_3_1_MASK                          0x00000E00
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_3_1_SET(n)                        (((uint32_t)(n) << 9  ) & 0x00000E00)
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_3_1_CLR                           0xFFFFF1FF

#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_2_1_SHIFT                         6
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_2_1_MASK                          0x000001C0
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_2_1_SET(n)                        (((uint32_t)(n) << 6  ) & 0x000001C0)
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_2_1_CLR                           0xFFFFFE3F

#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_1_1_SHIFT                         3
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_1_1_MASK                          0x00000038
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_1_1_SET(n)                        (((uint32_t)(n) << 3  ) & 0x00000038)
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_1_1_CLR                           0xFFFFFFC7

#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_0_1_SHIFT                         0
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_0_1_MASK                          0x00000007
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_0_1_SET(n)                        (((uint32_t)(n) << 0  ) & 0x00000007)
#define CAPTOUCH_CTRL_HOP_1_HOP_CNT_0_1_CLR                           0xFFFFFFF8

#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_NUM_1_SHIFT                    28
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_NUM_1_MASK                     0x70000000
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_NUM_1_SET(n)                   (((uint32_t)(n) << 28 ) & 0x70000000)
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_NUM_1_CLR                      0x8FFFFFFF

#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_6_1_SHIFT                      24
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_6_1_MASK                       0x0F000000
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_6_1_SET(n)                     (((uint32_t)(n) << 24 ) & 0x0F000000)
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_6_1_CLR                        0xF0FFFFFF

#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_5_1_SHIFT                      20
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_5_1_MASK                       0x00F00000
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_5_1_SET(n)                     (((uint32_t)(n) << 20 ) & 0x00F00000)
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_5_1_CLR                        0xFF0FFFFF

#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_4_1_SHIFT                      16
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_4_1_MASK                       0x000F0000
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_4_1_SET(n)                     (((uint32_t)(n) << 16 ) & 0x000F0000)
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_4_1_CLR                        0xFFF0FFFF

#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_3_1_SHIFT                      12
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_3_1_MASK                       0x0000F000
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_3_1_SET(n)                     (((uint32_t)(n) << 12 ) & 0x0000F000)
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_3_1_CLR                        0xFFFF0FFF

#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_2_1_SHIFT                      8
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_2_1_MASK                       0x00000F00
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_2_1_SET(n)                     (((uint32_t)(n) << 8  ) & 0x00000F00)
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_2_1_CLR                        0xFFFFF0FF

#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_1_1_SHIFT                      4
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_1_1_MASK                       0x000000F0
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_1_1_SET(n)                     (((uint32_t)(n) << 4  ) & 0x000000F0)
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_1_1_CLR                        0xFFFFFF0F

#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_0_1_SHIFT                      0
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_0_1_MASK                       0x0000000F
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_0_1_SET(n)                     (((uint32_t)(n) << 0  ) & 0x0000000F)
#define CAPTOUCH_CTRL_SCAN_1_SCAN_CHNL_0_1_CLR                        0xFFFFFFF0

#define CAPTOUCH_CTRL_OUT_1_CAPTOUCH_BUSY_1_SHIFT                     16
#define CAPTOUCH_CTRL_OUT_1_CAPTOUCH_BUSY_1_MASK                      0x00010000
#define CAPTOUCH_CTRL_OUT_1_CAPTOUCH_BUSY_1_SET(n)                    (((uint32_t)(n) << 16 ) & 0x00010000)
#define CAPTOUCH_CTRL_OUT_1_CAPTOUCH_BUSY_1_CLR                       0xFFFEFFFF

#define CAPTOUCH_CTRL_OUT_1_CHNL_STATUS_1_SHIFT                       12
#define CAPTOUCH_CTRL_OUT_1_CHNL_STATUS_1_MASK                        0x0000F000
#define CAPTOUCH_CTRL_OUT_1_CHNL_STATUS_1_SET(n)                      (((uint32_t)(n) << 12 ) & 0x0000F000)
#define CAPTOUCH_CTRL_OUT_1_CHNL_STATUS_1_CLR                         0xFFFF0FFF

#define CAPTOUCH_CTRL_OUT_1_CHNL_OUT_1_SHIFT                          0
#define CAPTOUCH_CTRL_OUT_1_CHNL_OUT_1_MASK                           0x00000FFF
#define CAPTOUCH_CTRL_OUT_1_CHNL_OUT_1_SET(n)                         (((uint32_t)(n) << 0  ) & 0x00000FFF)
#define CAPTOUCH_CTRL_OUT_1_CHNL_OUT_1_CLR                            0xFFFFF000

#define CAPTOUCH_CTRL_FIFO_1_ENTRY_VALID_1_SHIFT                      8
#define CAPTOUCH_CTRL_FIFO_1_ENTRY_VALID_1_MASK                       0x00000F00
#define CAPTOUCH_CTRL_FIFO_1_ENTRY_VALID_1_SET(n)                     (((uint32_t)(n) << 8  ) & 0x00000F00)
#define CAPTOUCH_CTRL_FIFO_1_ENTRY_VALID_1_CLR                        0xFFFFF0FF

#define CAPTOUCH_CTRL_FIFO_1_FIFO_THRHLD_1_SHIFT                      4
#define CAPTOUCH_CTRL_FIFO_1_FIFO_THRHLD_1_MASK                       0x00000070
#define CAPTOUCH_CTRL_FIFO_1_FIFO_THRHLD_1_SET(n)                     (((uint32_t)(n) << 4  ) & 0x00000070)
#define CAPTOUCH_CTRL_FIFO_1_FIFO_THRHLD_1_CLR                        0xFFFFFF8F

#define CAPTOUCH_CTRL_FIFO_1_DMAREQ_EN_1_SHIFT                        1
#define CAPTOUCH_CTRL_FIFO_1_DMAREQ_EN_1_MASK                         0x00000002
#define CAPTOUCH_CTRL_FIFO_1_DMAREQ_EN_1_SET(n)                       (((uint32_t)(n) << 1  ) & 0x00000002)
#define CAPTOUCH_CTRL_FIFO_1_DMAREQ_EN_1_CLR                          0xFFFFFFFD

#define CAPTOUCH_CTRL_FIFO_1_FIFO_EN_1_SHIFT                          0
#define CAPTOUCH_CTRL_FIFO_1_FIFO_EN_1_MASK                           0x00000001
#define CAPTOUCH_CTRL_FIFO_1_FIFO_EN_1_SET(n)                         (((uint32_t)(n) << 0  ) & 0x00000001)
#define CAPTOUCH_CTRL_FIFO_1_FIFO_EN_1_CLR                            0xFFFFFFFE

#define CAPTOUCH_FIFO_DATA_1_FIFO_RDATA_1_SHIFT                       0
#define CAPTOUCH_FIFO_DATA_1_FIFO_RDATA_1_MASK                        0xFFFFFFFF
#define CAPTOUCH_FIFO_DATA_1_FIFO_RDATA_1_SET(n)                      (((uint32_t)(n) << 0  ) & 0xFFFFFFFF)
#define CAPTOUCH_FIFO_DATA_1_FIFO_RDATA_1_CLR                         0x00000000

#define CAPTOUCH_IMR_IMR_1_SHIFT                                      8
#define CAPTOUCH_IMR_IMR_1_MASK                                       0x00001F00
#define CAPTOUCH_IMR_IMR_1_SET(n)                                     (((uint32_t)(n) << 8  ) & 0x00001F00)
#define CAPTOUCH_IMR_IMR_1_CLR                                        0xFFFFE0FF

#define CAPTOUCH_IMR_IMR_0_SHIFT                                      0
#define CAPTOUCH_IMR_IMR_0_MASK                                       0x0000001F
#define CAPTOUCH_IMR_IMR_0_SET(n)                                     (((uint32_t)(n) << 0  ) & 0x0000001F)
#define CAPTOUCH_IMR_IMR_0_CLR                                        0xFFFFFFE0

#define CAPTOUCH_ICR_ICR_1_SHIFT                                      8
#define CAPTOUCH_ICR_ICR_1_MASK                                       0x00001F00
#define CAPTOUCH_ICR_ICR_1_SET(n)                                     (((uint32_t)(n) << 8  ) & 0x00001F00)
#define CAPTOUCH_ICR_ICR_1_CLR                                        0xFFFFE0FF

#define CAPTOUCH_ICR_ICR_0_SHIFT                                      0
#define CAPTOUCH_ICR_ICR_0_MASK                                       0x0000001F
#define CAPTOUCH_ICR_ICR_0_SET(n)                                     (((uint32_t)(n) << 0  ) & 0x0000001F)
#define CAPTOUCH_ICR_ICR_0_CLR                                        0xFFFFFFE0

#define CAPTOUCH_ISR_ISR_1_SHIFT                                      8
#define CAPTOUCH_ISR_ISR_1_MASK                                       0x00001F00
#define CAPTOUCH_ISR_ISR_1_SET(n)                                     (((uint32_t)(n) << 8  ) & 0x00001F00)
#define CAPTOUCH_ISR_ISR_1_CLR                                        0xFFFFE0FF

#define CAPTOUCH_ISR_ISR_0_SHIFT                                      0
#define CAPTOUCH_ISR_ISR_0_MASK                                       0x0000001F
#define CAPTOUCH_ISR_ISR_0_SET(n)                                     (((uint32_t)(n) << 0  ) & 0x0000001F)
#define CAPTOUCH_ISR_ISR_0_CLR                                        0xFFFFFFE0

#define CAPTOUCH_IRSR_IRSR_1_SHIFT                                    8
#define CAPTOUCH_IRSR_IRSR_1_MASK                                     0x00001F00
#define CAPTOUCH_IRSR_IRSR_1_SET(n)                                   (((uint32_t)(n) << 8  ) & 0x00001F00)
#define CAPTOUCH_IRSR_IRSR_1_CLR                                      0xFFFFE0FF

#define CAPTOUCH_IRSR_IRSR_0_SHIFT                                    0
#define CAPTOUCH_IRSR_IRSR_0_MASK                                     0x0000001F
#define CAPTOUCH_IRSR_IRSR_0_SET(n)                                   (((uint32_t)(n) << 0  ) & 0x0000001F)
#define CAPTOUCH_IRSR_IRSR_0_CLR                                      0xFFFFFFE0

#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PB_MODE_SHIFT                    31
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PB_MODE_MASK                     0x80000000
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PB_MODE_SET(n)                   (((uint32_t)(n) << 31 ) & 0x80000000)
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PB_MODE_CLR                      0x7FFFFFFF

#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PB_EN_SHIFT                      16
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PB_EN_MASK                       0x3FFF0000
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PB_EN_SET(n)                     (((uint32_t)(n) << 16 ) & 0x3FFF0000)
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PB_EN_CLR                        0xC000FFFF

#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PA_MODE_SHIFT                    15
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PA_MODE_MASK                     0x00008000
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PA_MODE_SET(n)                   (((uint32_t)(n) << 15 ) & 0x00008000)
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PA_MODE_CLR                      0xFFFF7FFF

#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PA_EN_SHIFT                      0
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PA_EN_MASK                       0x00003FFF
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PA_EN_SET(n)                     (((uint32_t)(n) << 0  ) & 0x00003FFF)
#define CAPTOUCH_CTRL_ANASW_SW_ANASW_PA_EN_CLR                        0xFFFFC000

// Register Structure Definition
typedef struct
{
    __IO uint32_t CAPTOUCH_EN    : 1  ; // 0  : 0
    __IO uint32_t CAPTOUCH_MODE  : 2  ; // 2  : 1
    __IO uint32_t SW_TRIG        : 1  ; // 3  : 3
    __IO uint32_t SW_CHNL_SEL    : 4  ; // 7  : 4
    __IO uint32_t CONV_LOOP      : 3  ; // 10 : 8
    __IO uint32_t SW_CTRL_CONV   : 1  ; // 11 : 11
    __IO uint32_t TW_TRIG_EN     : 1  ; // 12 : 12
    __IO uint32_t RESERVED0      : 19 ; // 31 : 13
} CAPTOUCH_CTRL_CONV_FIELD_T;

typedef struct
{
    __IO uint32_t SW_PD_CTRL     : 7  ; // 6  : 0
    __IO uint32_t SW_PD_MODE     : 1  ; // 7  : 7
    __IO uint32_t CHRG_CYCLE     : 3  ; // 10 : 8
    __IO uint32_t RESERVED1      : 1  ; // 11 : 11
    __IO uint32_t TRANS_CYCLE    : 3  ; // 14 : 12
    __IO uint32_t RESERVED0      : 1  ; // 15 : 15
    __IO uint32_t INIT_CYCLE     : 8  ; // 23 : 16
    __IO uint32_t DISCHRG_CYCLE  : 8  ; // 31 : 24
} CAPTOUCH_CTRL_INIT_FIELD_T;

typedef struct
{
    __IO uint32_t ADC_CYCLE      : 12 ; // 11 : 0
    __IO uint32_t ADC_CHNL_RDY   : 1  ; // 12 : 12
    __IO uint32_t ADC_CHNL_CLR   : 1  ; // 13 : 13
    __IO uint32_t RESERVED1      : 2  ; // 15 : 14
    __IO uint32_t MAX_CNT        : 12 ; // 27 : 16
    __IO uint32_t MAX_CNT_DET_EN : 1  ; // 28 : 28
    __IO uint32_t RESERVED0      : 3  ; // 31 : 29
} CAPTOUCH_CTRL_ADC_FIELD_T;

typedef struct
{
    __IO uint32_t HOP_CNT_0      : 3  ; // 2  : 0
    __IO uint32_t HOP_CNT_1      : 3  ; // 5  : 3
    __IO uint32_t HOP_CNT_2      : 3  ; // 8  : 6
    __IO uint32_t HOP_CNT_3      : 3  ; // 11 : 9
    __IO uint32_t HOP_CNT_4      : 3  ; // 14 : 12
    __IO uint32_t HOP_CNT_5      : 3  ; // 17 : 15
    __IO uint32_t HOP_CNT_6      : 3  ; // 20 : 18
    __IO uint32_t HOP_CNT_7      : 3  ; // 23 : 21
    __IO uint32_t HOP_PERIOD     : 3  ; // 26 : 24
    __IO uint32_t RESERVED0      : 5  ; // 31 : 27
} CAPTOUCH_CTRL_HOP_FIELD_T;

typedef struct
{
    __IO uint32_t SCAN_CHNL_0    : 4  ; // 3  : 0
    __IO uint32_t SCAN_CHNL_1    : 4  ; // 7  : 4
    __IO uint32_t SCAN_CHNL_2    : 4  ; // 11 : 8
    __IO uint32_t SCAN_CHNL_3    : 4  ; // 15 : 12
    __IO uint32_t SCAN_CHNL_4    : 4  ; // 19 : 16
    __IO uint32_t SCAN_CHNL_5    : 4  ; // 23 : 20
    __IO uint32_t SCAN_CHNL_6    : 4  ; // 27 : 24
    __IO uint32_t SCAN_CHNL_NUM  : 3  ; // 30 : 28
    __IO uint32_t RESERVED0      : 1  ; // 31 : 31
} CAPTOUCH_CTRL_SCAN_FIELD_T;

typedef struct
{
    __IO uint32_t CHNL_OUT       : 12 ; // 11 : 0
    __IO uint32_t CHNL_STATUS    : 4  ; // 15 : 12
    __IO uint32_t CAPTOUCH_BUSY  : 1  ; // 16 : 16
    __IO uint32_t RESERVED0      : 15 ; // 31 : 17
} CAPTOUCH_CTRL_OUT_FIELD_T;

typedef struct
{
    __IO uint32_t FIFO_EN        : 1  ; // 0  : 0
    __IO uint32_t DMAREQ_EN      : 1  ; // 1  : 1
    __IO uint32_t RESERVED2      : 2  ; // 3  : 2
    __IO uint32_t FIFO_THRHLD    : 3  ; // 6  : 4
    __IO uint32_t RESERVED1      : 1  ; // 7  : 7
    __IO uint32_t ENTRY_VALID    : 4  ; // 11 : 8
    __IO uint32_t RESERVED0      : 20 ; // 31 : 12
} CAPTOUCH_CTRL_FIFO_FIELD_T;

typedef struct
{
    __IO uint32_t FIFO_RDATA     : 32 ; // 31 : 0
} CAPTOUCH_FIFO_DATA_FIELD_T;

typedef struct
{
    __IO uint32_t IMR_0            : 5  ; // 4  : 0
    __IO uint32_t RESERVED1        : 3  ; // 7  : 5
    __IO uint32_t IMR_1            : 5  ; // 12 : 8
    __IO uint32_t RESERVED0        : 19 ; // 31 : 13
} CAPTOUCH_IMR_FIELD_T;

typedef struct
{
    __IO uint32_t ICR_0            : 5  ; // 4  : 0
    __IO uint32_t RESERVED1        : 3  ; // 7  : 5
    __IO uint32_t ICR_1            : 5  ; // 12 : 8
    __IO uint32_t RESERVED0        : 19 ; // 31 : 13
} CAPTOUCH_ICR_FIELD_T;

typedef struct
{
    __IO uint32_t ISR_0            : 5  ; // 4  : 0
    __IO uint32_t RESERVED1        : 3  ; // 7  : 5
    __IO uint32_t ISR_1            : 5  ; // 12 : 8
    __IO uint32_t RESERVED0        : 19 ; // 31 : 13
} CAPTOUCH_ISR_FIELD_T;

typedef struct
{
    __IO uint32_t IRSR_0           : 5  ; // 4  : 0
    __IO uint32_t RESERVED1        : 3  ; // 7  : 5
    __IO uint32_t IRSR_1           : 5  ; // 12 : 8
    __IO uint32_t RESERVED0        : 19 ; // 31 : 13
} CAPTOUCH_IRSR_FIELD_T;

typedef struct
{
    __IO uint32_t SW_ANASW_PA_EN   : 14 ; // 13 : 0
    __IO uint32_t RESERVED1        : 1  ; // 14 : 14
    __IO uint32_t SW_ANASW_PA_MODE : 1  ; // 15 : 15
    __IO uint32_t SW_ANASW_PB_EN   : 14 ; // 29 : 16
    __IO uint32_t RESERVED0        : 1  ; // 30 : 30
    __IO uint32_t SW_ANASW_PB_MODE : 1  ; // 31 : 31
} CAPTOUCH_CTRL_ANASW_FIELD_T;

// Register Map Structure Definition
typedef struct
{
    union
    {
        __IO  uint32_t CTRL_CONV_0               ; // 0x0000
        CAPTOUCH_CTRL_CONV_FIELD_T CTRL_CONV_0_F;
    };

    union
    {
        __IO  uint32_t CTRL_INIT_0               ; // 0x0004
        CAPTOUCH_CTRL_INIT_FIELD_T CTRL_INIT_0_F;
    };

    union
    {
        __IO  uint32_t CTRL_ADC_0                ; // 0x0008
        CAPTOUCH_CTRL_ADC_FIELD_T CTRL_ADC_0_F ;
    };

    union
    {
        __IO  uint32_t CTRL_HOP_0                ; // 0x000C
        CAPTOUCH_CTRL_HOP_FIELD_T CTRL_HOP_0_F ;
    };

    union
    {
        __IO  uint32_t CTRL_SCAN_0               ; // 0x0010
        CAPTOUCH_CTRL_SCAN_FIELD_T CTRL_SCAN_0_F;
    };

    union
    {
        __IO  uint32_t CTRL_OUT_0                ; // 0x0014
        CAPTOUCH_CTRL_OUT_FIELD_T CTRL_OUT_0_F ;
    };

    union
    {
        __IO  uint32_t CTRL_FIFO_0               ; // 0x0018
        CAPTOUCH_CTRL_FIFO_FIELD_T CTRL_FIFO_0_F;
    };

    union
    {
        __IO  uint32_t FIFO_DATA_0               ; // 0x001C
        CAPTOUCH_FIFO_DATA_FIELD_T FIFO_DATA_0_F;
    };

    union
    {
        __IO  uint32_t CTRL_CONV_1               ; // 0x0020
        CAPTOUCH_CTRL_CONV_FIELD_T CTRL_CONV_1_F;
    };

    union
    {
        __IO  uint32_t CTRL_INIT_1               ; // 0x0024
        CAPTOUCH_CTRL_INIT_FIELD_T CTRL_INIT_1_F;
    };

    union
    {
        __IO  uint32_t CTRL_ADC_1                ; // 0x0028
        CAPTOUCH_CTRL_ADC_FIELD_T CTRL_ADC_1_F ;
    };

    union
    {
        __IO  uint32_t CTRL_HOP_1                ; // 0x002C
        CAPTOUCH_CTRL_HOP_FIELD_T CTRL_HOP_1_F ;
    };

    union
    {
        __IO  uint32_t CTRL_SCAN_1               ; // 0x0030
        CAPTOUCH_CTRL_SCAN_FIELD_T CTRL_SCAN_1_F;
    };

    union
    {
        __IO  uint32_t CTRL_OUT_1                ; // 0x0034
        CAPTOUCH_CTRL_OUT_FIELD_T CTRL_OUT_1_F ;
    };

    union
    {
        __IO  uint32_t CTRL_FIFO_1               ; // 0x0038
        CAPTOUCH_CTRL_FIFO_FIELD_T CTRL_FIFO_1_F;
    };

    union
    {
        __IO  uint32_t FIFO_DATA_1               ; // 0x003C
        CAPTOUCH_FIFO_DATA_FIELD_T FIFO_DATA_1_F;
    };

    union
    {
        __IO  uint32_t IMR                       ; // 0x0040
        CAPTOUCH_IMR_FIELD_T IMR_F               ;
    };

    union
    {
        __IO  uint32_t ICR                       ; // 0x0044
        CAPTOUCH_ICR_FIELD_T ICR_F               ;
    };

    union
    {
        __IO  uint32_t ISR                       ; // 0x0048
        CAPTOUCH_ISR_FIELD_T ISR_F               ;
    };

    union
    {
        __IO  uint32_t IRSR                      ; // 0x004C
        CAPTOUCH_IRSR_FIELD_T IRSR_F             ;
    };

    union
    {
        __IO  uint32_t CTRL_ANASW                ; // 0x0050
        CAPTOUCH_CTRL_ANASW_FIELD_T CTRL_ANASW_F ;
    };

} CAPTOUCH_REG_TypeDef;

typedef struct
{

    union
    {
        __IO  uint32_t CTRL_CONV               ; // 0x0000
        CAPTOUCH_CTRL_CONV_FIELD_T CTRL_CONV_F;
    };

    union
    {
        __IO  uint32_t CTRL_INIT               ; // 0x0004
        CAPTOUCH_CTRL_INIT_FIELD_T CTRL_INIT_F;
    };

    union
    {
        __IO  uint32_t CTRL_ADC                ; // 0x0008
        CAPTOUCH_CTRL_ADC_FIELD_T CTRL_ADC_F ;
    };

    union
    {
        __IO  uint32_t CTRL_HOP                ; // 0x000C
        CAPTOUCH_CTRL_HOP_FIELD_T CTRL_HOP_F ;
    };

    union
    {
        __IO  uint32_t CTRL_SCAN               ; // 0x0010
        CAPTOUCH_CTRL_SCAN_FIELD_T CTRL_SCAN_F;
    };

    union
    {
        __IO  uint32_t CTRL_OUT                ; // 0x0014
        CAPTOUCH_CTRL_OUT_FIELD_T CTRL_OUT_F ;
    };

    union
    {
        __IO  uint32_t CTRL_FIFO               ; // 0x0018
        CAPTOUCH_CTRL_FIFO_FIELD_T CTRL_FIFO_F;
    };

    union
    {
        __IO  uint32_t FIFO_DATA               ; // 0x001C
        CAPTOUCH_FIFO_DATA_FIELD_T FIFO_DATA_F;
    };

} CAPTOUCH_BLOCK_REG_TypeDef;

#endif
